Freescale's eGUI: d4d_picture.c File Reference
d4d_picture.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Functions
void D4D_PictOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_PictGetTextBuffer (D4D_OBJECT *pThis)
static void D4D_PictOnDraw (D4D_MESSAGE *pMsg)
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_pictSysFunc
Detailed Description
D4D driver picture object c file.
Author
Michal hanak, Petr Gargulak
Version
0.0.23.0
Date
Oct-2-2013
Definition in file d4d_picture.c.
Function Documentation
D4D_STRING* D4D_PictGetTextBuffer (D4D_OBJECT * pThis)
static void D4D_PictOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 67 of file d4d_picture.c.
References D4D_ComputeGeometry(), D4D_DrawFrame(), D4D_DrawRBmpRect, D4D_GET_PICTURE, D4D_IsEnabled(), D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_PIC_PRTY_DEFAULT, D4D_MESSAGE_S::draw, NULL, D4D_PICTURE::pBmp, D4D_GEOMETRY::pnt, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_OBJECT_S::radius, and D4D_GEOMETRY::sz.
Referenced by D4D_PictOnMessage().
void D4D_PictOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 104 of file d4d_picture.c.
References D4D_MSG_DRAW, D4D_ObjOnMessage(), D4D_PictOnDraw(), and D4D_MESSAGE_S::nMsgId.
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_pictSysFunc
Definition at line 53 of file d4d_picture.c.