Freescale's eGUI: d4d_list_box.c File Reference
d4d_list_box.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_ListBoxOnMessage (D4D_MESSAGE *pMsg)
static void D4D_ListBoxOnInit (D4D_OBJECT *pThis)
static D4D_LIST_BOX_INDEX D4D_GetItemsCount (D4D_LIST_BOX *pListBox)
static D4D_LIST_BOX_INDEX D4D_GetPositionCount (D4D_OBJECT *pThis)
static void D4D_ListBoxValue2Coor (D4D_OBJECT *pThis)
static void D4D_ListBoxOnDraw (D4D_MESSAGE *pMsg)
static void D4D_ListBoxFocusNextItem (D4D_OBJECT *pThis)
static void D4D_ListBoxFocusPreviousItem (D4D_OBJECT *pThis)
static void D4D_ListBoxOnKeyUp (D4D_MESSAGE *pMsg)
void D4D_ListBoxScrollBarsFeedBack (D4D_OBJECT *pThis, D4D_INDEX old_position, D4D_INDEX new_position)
void D4D_ListBoxEnsureVisible (D4D_OBJECT *pThis)
Function ensure that the selected item in list will be scrolled to visible area.
D4D_LIST_BOX_INDEX D4D_ListBoxGetIndex (D4D_OBJECT *pThis)
Function returns the current selected item index.
void D4D_ListBoxSetIndex (D4D_OBJECT *pThis, D4D_LIST_BOX_INDEX ix)
Function select new item by index.
D4D_LIST_BOX_INDEX D4D_ListBoxGetItemCount (D4D_OBJECT_PTR pThis)
Function gets the count of list box items.
D4D_LIST_BOX_INDEX D4D_ListBoxFindUserDataItem (D4D_OBJECT_PTR pThis, void *pUser)
Function finds the index of items with specified user data.
void * D4D_ListBoxGetItemUserData (D4D_OBJECT_PTR pThis)
Function gets the selected item user data.
D4D_TCHAR * D4D_ListBoxGetItemText (D4D_OBJECT_PTR pThis)
Function gets the selected item text.
D4D_TCHAR * D4D_ListBoxGetItemTextIx (D4D_OBJECT_PTR pThis, D4D_LIST_BOX_INDEX ix)
Function gets the text of item choosed by item index.
void D4D_ListBoxChangeItemList (D4D_OBJECT_PTR pThis, const D4D_LIST_BOX_ITEM *pItems)
Function change the items list using by list box.
D4D_LIST_BOX_ITEM * D4D_ListBoxGetItemList (D4D_OBJECT_PTR pThis)
Function gets the current using item list.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_listBoxSysFunc
const D4D_MARGIN listBox_marginDefault
Detailed Description
D4D driver listBox object c file.
Author
Petr Gargulak
Version
0.0.10.0
Date
Oct-16-2013
Definition in file d4d_list_box.c.
Macro Definition Documentation
#define _calc
Definition at line 83 of file d4d_list_box.c.
Referenced by D4D_ListBoxOnDraw(), and D4D_ListBoxValue2Coor().
Function Documentation
static D4D_LIST_BOX_INDEX D4D_GetItemsCount (D4D_LIST_BOX * pListBox) static
Definition at line 93 of file d4d_list_box.c.
References D4D_LIST_BOX::pData, D4D_LIST_BOX_DATA::pItems, and D4D_LIST_BOX_ITEM::pText.
Referenced by D4D_ListBoxEnsureVisible(), D4D_ListBoxFindUserDataItem(), D4D_ListBoxFocusNextItem(), D4D_ListBoxFocusPreviousItem(), D4D_ListBoxGetItemCount(), D4D_ListBoxGetItemTextIx(), D4D_ListBoxOnInit(), D4D_ListBoxSetIndex(), and D4D_ListBoxValue2Coor().
static D4D_LIST_BOX_INDEX D4D_GetPositionCount (D4D_OBJECT * pThis) static
Definition at line 103 of file d4d_list_box.c.
References D4D_MARGIN::bottom, D4D_SIZE::cy, D4D_GET_LIST_BOX, D4D_GetFontHeight(), D4D_LIST_BOX::itemsFontId, D4D_OBJECT_S::pMargin, D4D_LIST_BOX::posCnt, D4D_OBJECT_S::size, and D4D_MARGIN::top.
Referenced by D4D_ListBoxEnsureVisible(), D4D_ListBoxFocusNextItem(), D4D_ListBoxFocusPreviousItem(), D4D_ListBoxOnInit(), and D4D_ListBoxValue2Coor().
static void D4D_ListBoxFocusNextItem (D4D_OBJECT * pThis) static
Definition at line 280 of file d4d_list_box.c.
References D4D_EVENT_ONCHANGE, D4D_FALSE, D4D_GET_LIST_BOX, D4D_GetItemsCount(), D4D_GetPositionCount(), D4D_InvalidateObject(), D4D_ListBoxEnsureVisible(), D4D_LIST_BOX_DATA::ix, D4D_LIST_BOX::OnEvent, and D4D_LIST_BOX::pData.
Referenced by D4D_ListBoxOnKeyUp(), and D4D_ListBoxOnMessage().
static void D4D_ListBoxFocusPreviousItem (D4D_OBJECT * pThis) static
Definition at line 304 of file d4d_list_box.c.
References D4D_EVENT_ONCHANGE, D4D_FALSE, D4D_GET_LIST_BOX, D4D_GetItemsCount(), D4D_GetPositionCount(), D4D_InvalidateObject(), D4D_ListBoxEnsureVisible(), D4D_LIST_BOX_DATA::ix, D4D_LIST_BOX::OnEvent, and D4D_LIST_BOX::pData.
Referenced by D4D_ListBoxOnKeyUp(), and D4D_ListBoxOnMessage().
static void D4D_ListBoxOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 180 of file d4d_list_box.c.
References _calc, D4D_CLR_SCHEME_S::bckgFocus, D4D_STRING_S::buffSize, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ASSERT, D4D_DrawFrame(), D4D_DrawTextRect, D4D_DrawTextRRect, D4D_FillRect(), D4D_FillRRect(), D4D_GET_LIST_BOX, D4D_GetTextLength(), D4D_IsEnabled(), D4D_LIST_BOX_ITEM_FNT_PRTY_DEFAULT, D4D_LIST_BOX_ITEM_TXT_PRTY_DEFAULT, D4D_ListBoxValue2Coor(), D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetForeFillColor(), D4D_ObjectGetScheme(), D4D_SCRATCHPAD_SIZE, D4D_MESSAGE_S::draw, D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, D4D_CLR_SCHEME_S::foreFocus, D4D_LIST_BOX::itemsFontId, D4D_LIST_BOX_DATA::ix, NULL, D4D_LIST_BOX_DATA::page_ix, D4D_LIST_BOX::pData, D4D_LIST_BOX_DATA::pItems, D4D_MESSAGE_S::pObject, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_LIST_BOX_ITEM::pText, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_STRING_S::str_properties, D4D_STR_PROPERTIES_S::text_properties, and D4D_POINT::y.
Referenced by D4D_ListBoxOnMessage().
static void D4D_ListBoxOnInit (D4D_OBJECT * pThis) static
Definition at line 438 of file d4d_list_box.c.
References D4D_EVENT_ONRELOAD, D4D_GET_LIST_BOX, D4D_GetItemsCount(), D4D_GetPositionCount(), D4D_InvalidateObject(), D4D_LIST_BOX_CHILD_SCROLL_BAR_IX, D4D_LIST_BOX_F_SIDEBAR, D4D_LIST_BOX_SCRLBR_STEP, D4D_ListBoxValue2Coor(), D4D_ScrlBrSetPosition(), D4D_ScrlBrSetRange(), D4D_ScrlBrSetStep(), D4D_ShowObject(), D4D_TRUE, D4D_OBJECT_S::initFlags, D4D_LIST_BOX_DATA::ix, D4D_LIST_BOX::OnEvent, D4D_LIST_BOX_DATA::page_ix, D4D_LIST_BOX::pData, and D4D_OBJECT_S::pRelations.
Referenced by D4D_ListBoxChangeItemList(), and D4D_ListBoxOnMessage().
static void D4D_ListBoxOnKeyUp (D4D_MESSAGE * pMsg) static
Definition at line 340 of file d4d_list_box.c.
References D4D_CaptureKeys(), D4D_EVENT_ONCLICK, D4D_GET_LIST_BOX, D4D_GetCapturedObject(), D4D_KEY_SCANCODE_DOWN, D4D_KEY_SCANCODE_ENTER, D4D_KEY_SCANCODE_ESC, D4D_KEY_SCANCODE_UP, D4D_ListBoxFocusNextItem(), D4D_ListBoxFocusPreviousItem(), D4D_MESSAGE_S::key, NULL, D4D_LIST_BOX::OnEvent, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::prm.
Referenced by D4D_ListBoxOnMessage().
void D4D_ListBoxOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 685 of file d4d_list_box.c.
References D4D_GetMouseCoordinates, D4D_GetTouchScreenCoordinates(), D4D_ListBoxFocusNextItem(), D4D_ListBoxFocusPreviousItem(), D4D_ListBoxOnDraw(), D4D_ListBoxOnInit(), D4D_ListBoxOnKeyUp(), D4D_MSG_DRAW, D4D_MSG_KEYUP, D4D_MSG_MOUSE_BTN_LEFT_UP, D4D_MSG_MOUSE_BTN_WHEEL_DOWN, D4D_MSG_MOUSE_BTN_WHEEL_UP, D4D_MSG_ONINIT, D4D_MSG_TOUCHED, D4D_OBJECT_F_NOTINIT, D4D_ObjOnMessage(), D4D_OBJECT_DATA_S::flags, D4D_MESSAGE_S::nMsgId, D4D_OBJECT_S::pData, and D4D_MESSAGE_S::pObject.
void D4D_ListBoxScrollBarsFeedBack (D4D_OBJECT * pThis, D4D_INDEX old_position, D4D_INDEX new_position)
Definition at line 472 of file d4d_list_box.c.
References D4D_FALSE, D4D_GET_LIST_BOX, D4D_InvalidateObject(), D4D_UNUSED, D4D_LIST_BOX_DATA::page_ix, D4D_LIST_BOX::pData, and D4D_OBJECT_S::userData.
static void D4D_ListBoxValue2Coor (D4D_OBJECT * pThis) static
Definition at line 133 of file d4d_list_box.c.
References _calc, D4D_MARGIN::bottom, D4D_GET_LIST_BOX, D4D_GET_LIST_BOX_SCROLL_BAR, D4D_GetClientToScreenPoint(), D4D_GetItemsCount(), D4D_GetPositionCount(), D4D_IsVisible(), D4D_LIST_BOX_SCRLBR_WIDTH, D4D_OBJECT_F_FOCUSRECT, D4D_OBJECT_S::initFlags, D4D_MARGIN::left, D4D_OBJECT_S::pMargin, D4D_OBJECT_S::position, D4D_MARGIN::right, D4D_OBJECT_S::size, D4D_LIST_BOX::textOff, and D4D_MARGIN::top.
Referenced by D4D_ListBoxOnDraw(), and D4D_ListBoxOnInit().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_listBoxSysFunc
Definition at line 56 of file d4d_list_box.c.
const D4D_MARGIN listBox_marginDefault
Definition at line 64 of file d4d_list_box.c.