Freescale's eGUI: d4d_icon.c File Reference
d4d_icon.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_IconOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_IconGetTextBuffer (D4D_OBJECT *pThis)
D4D_ICON_INDEX D4D_IconGetBmpCount (D4D_OBJECT_PTR pThis)
Function returns the icon bitmap count.
static void D4D_IconValue2Coor (D4D_OBJECT *pThis)
static void D4D_IconOnDraw (D4D_MESSAGE *pMsg)
void D4D_IconSetIndex (D4D_OBJECT_PTR pThis, D4D_ICON_INDEX index)
Function sets the new bitmap of icon by icon index.
void D4D_IconChangeIndex (D4D_OBJECT_PTR pThis, sByte incr)
Function sets the new bitmap of icon by icon index difference.
D4D_ICON_INDEX D4D_IconGetIndex (D4D_OBJECT_PTR pThis)
Function returns current visible bitmap index.
void D4D_IconAnimationStart (D4D_OBJECT_PTR pThis)
Function starts the animation of icon.
void D4D_IconAnimationStop (D4D_OBJECT_PTR pThis)
Function stops the animation of icon.
void D4D_IconAnimationSetCounts (D4D_OBJECT_PTR pThis, Word cnt)
Function sets the time tick tresholds for animation speed.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_iconSysFunc
Detailed Description
D4D driver icon object c file.
Author
Petr Gargulak
Version
0.0.48.0
Date
Oct-16-2013
Definition in file d4d_icon.c.
Macro Definition Documentation
#define _calc
Definition at line 70 of file d4d_icon.c.
Referenced by D4D_IconOnDraw(), and D4D_IconValue2Coor().
Function Documentation
D4D_STRING * D4D_IconGetTextBuffer (D4D_OBJECT * pThis)
Get object text buffer
Definition at line 345 of file d4d_icon.c.
References D4D_GET_ICON.
static void D4D_IconOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 91 of file d4d_icon.c.
References _calc, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ALIGN_H_CENTER_MASK, D4D_ALIGN_V_TOP_MASK, D4D_DrawFrame(), D4D_DrawRBmpRect, D4D_DrawTextRect, D4D_GET_ICON, D4D_GetFontHeight(), D4D_GetTextWidth(), D4D_IconValue2Coor(), D4D_IsEnabled(), D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgColor(), D4D_ObjectGetForeColor(), D4D_MESSAGE_S::draw, D4D_STRING_S::fontId, D4D_ICON_DATA::index, NULL, D4D_ICON::pBmpX, D4D_ICON::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_OBJECT_S::radius, and D4D_ICON::textBuff.
Referenced by D4D_IconOnMessage().
void D4D_IconOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 290 of file d4d_icon.c.
References D4D_ICON_DATA::animationEnabled, D4D_FocusSet(), D4D_GET_ICON, D4D_ICON_ANIMATION_TICK_COUNTER, D4D_IconChangeIndex(), D4D_IconOnDraw(), D4D_MSG_DRAW, D4D_MSG_ONINIT, D4D_MSG_TIMETICK, D4D_MSG_TOUCHED, D4D_OBJECT_F_NOTINIT, D4D_ObjOnMessage(), D4D_OBJECT_DATA_S::flags, D4D_MESSAGE_S::nMsgId, D4D_ICON::pData, D4D_OBJECT_S::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::pScreen, D4D_ICON_DATA::tickCounter, and D4D_ICON_DATA::tickCounterTrshld.
static void D4D_IconValue2Coor (D4D_OBJECT * pThis) static
Definition at line 73 of file d4d_icon.c.
References _calc, D4D_ComputeGeometry(), D4D_GET_ICON, D4D_GetClientToScreenPoint(), D4D_OBJECT_S::position, D4D_ICON::txtOff, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_IconOnDraw().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_iconSysFunc
Definition at line 54 of file d4d_icon.c.