Freescale's eGUI: d4d_console.c File Reference
d4d_console.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_ConsoleOnMessage (D4D_MESSAGE *pMsg)
static void D4D_CnslNewLine (D4D_OBJECT_PTR pObj, D4D_BOOL returnCarrier)
static D4D_BOOL D4D_CnslPutCharInt (D4D_OBJECT_PTR pObj, D4D_TCHAR ch)
static void D4D_CnslUpdateScrollbars (D4D_OBJECT *pThis)
static void D4D_CnslOnInit (D4D_MESSAGE *pMsg)
static void D4D_ConsoleTimeTick (D4D_MESSAGE *pMsg)
static D4D_INDEX D4D_CnslFindMaxTextLenght (D4D_TCHAR *pText, D4D_FONT font, D4D_INDEX startOffset, D4D_INDEX maxLenght)
static void D4D_CnslValue2Coor (D4D_OBJECT *pThis)
static void D4D_ConsoleOnDraw (D4D_MESSAGE *pMsg)
void D4D_CnslScrollBarsFeedBack (D4D_OBJECT *pThis, D4D_INDEX old_position, D4D_INDEX new_position)
D4D_BOOL D4D_CnslPutChar (D4D_OBJECT_PTR pObj, D4D_TCHAR ch)
The function puts one char on cursor position and updates cursor.
D4D_BOOL D4D_CnslPutString (D4D_OBJECT_PTR pObj, D4D_TCHAR *pText)
The function puts string on cursor position and updates cursor.
void D4D_CnslClearLine (D4D_OBJECT_PTR pObj, D4D_INDEX line)
The function clear one line in console.
void D4D_CnslGoToXY (D4D_OBJECT_PTR pObj, D4D_POINT newPosition)
The function move cursor on new position if possible.
D4D_POINT D4D_CnslGetCursor (D4D_OBJECT_PTR pObj)
The function returns the cursor position.
void D4D_CnslEnsureVisible (D4D_OBJECT_PTR pObj)
The function update automatically the scroll bars to ensure visible position of cursor.
void D4D_CnslSetScrollBarPosition (D4D_OBJECT_PTR pObj, D4D_INDEX hor, D4D_INDEX ver)
The function move the scroll bars on to new position if it's applicable.
D4D_POINT D4D_CnslGetScrollBarPosition (D4D_OBJECT_PTR pObj)
The function returns the scroll bars position.
void D4D_CnslClearAll (D4D_OBJECT_PTR pObj)
The function clear whole console data.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_consoleSysFunc
Detailed Description
D4D driver console object c file.
Author
Petr Gargulak
Version
0.0.28.0
Date
Oct-15-2013
Definition in file d4d_console.c.
Macro Definition Documentation
#define _calc
Definition at line 79 of file d4d_console.c.
Referenced by D4D_CnslFindMaxTextLenght(), D4D_CnslOnInit(), D4D_CnslUpdateScrollbars(), D4D_CnslValue2Coor(), and D4D_ConsoleOnDraw().
Function Documentation
static D4D_INDEX D4D_CnslFindMaxTextLenght (D4D_TCHAR * pText, D4D_FONT font, D4D_INDEX startOffset, D4D_INDEX maxLenght) static
Definition at line 118 of file d4d_console.c.
References _calc, and D4D_GetCharWidth().
Referenced by D4D_ConsoleOnDraw().
static void D4D_CnslNewLine (D4D_OBJECT_PTR pObj, D4D_BOOL returnCarrier) static
Definition at line 443 of file d4d_console.c.
References D4D_CNSL_DATA_S::cursorPos, D4D_SIZE::cy, D4D_CNSL_FLAGS_CHECKLINE, D4D_CNSL_FLAGS_REDRAWALL, D4D_CnslClearLine(), D4D_CnslUpdateScrollbars(), D4D_GET_CONSOLE, D4D_CNSL_DATA_S::flags, D4D_CNSL_DATA_S::lastLineIx, D4D_CONSOLE::pData, D4D_CONSOLE::txtArrSize, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_CnslPutChar(), and D4D_CnslPutCharInt().
static void D4D_CnslOnInit (D4D_MESSAGE * pMsg) static
Definition at line 297 of file d4d_console.c.
References _calc, D4D_SIZE::cx, D4D_SIZE::cy, D4D_CNSL_SCRLBR_STEP_H, D4D_CNSL_SCRLBR_STEP_V, D4D_CnslValue2Coor(), D4D_FALSE, D4D_GET_CONSOLE, D4D_GET_LIST_BOX_SCROLL_BAR_HOR, D4D_GET_LIST_BOX_SCROLL_BAR_VER, D4D_ScrlBrSetRange(), D4D_ScrlBrSetStep(), D4D_ShowObject(), D4D_TRUE, D4D_MESSAGE_S::pObject, and D4D_CONSOLE::txtArrSize.
Referenced by D4D_ConsoleOnMessage().
static D4D_BOOL D4D_CnslPutCharInt (D4D_OBJECT_PTR pObj, D4D_TCHAR ch) static
THE INTERNAL HELP FUNCTIONS
Definition at line 352 of file d4d_console.c.
References D4D_CNSL_DATA_S::cursorPos, D4D_SIZE::cx, D4D_SIZE::cy, D4D_CNSL_FLAGS_CHECKLINE, D4D_CnslNewLine(), D4D_FALSE, D4D_GET_CONSOLE, D4D_TRUE, D4D_CNSL_DATA_S::flags, D4D_CNSL_DATA_S::lastLineIx, D4D_CONSOLE::pData, D4D_CONSOLE::pTxtArr, D4D_CONSOLE::txtArrSize, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_CnslPutChar().
void D4D_CnslScrollBarsFeedBack (D4D_OBJECT * pThis, D4D_INDEX old_position, D4D_INDEX new_position)
Definition at line 394 of file d4d_console.c.
References D4D_CNSL_FLAGS_REDRAWALL, D4D_FALSE, D4D_GET_CONSOLE_DATA, D4D_GetParentObject(), D4D_InvalidateObject(), and D4D_UNUSED.
static void D4D_CnslUpdateScrollbars (D4D_OBJECT * pThis) static
Definition at line 405 of file d4d_console.c.
References _calc, D4D_CNSL_DATA_S::cursorPos, D4D_CnslValue2Coor(), D4D_GET_CONSOLE_DATA, D4D_GET_LIST_BOX_SCROLL_BAR_HOR, D4D_GET_LIST_BOX_SCROLL_BAR_VER, D4D_OBJECT_F_VISIBLE, D4D_ScrlBrSetPosition(), D4D_CNSL_DATA_S::flags, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_CnslEnsureVisible(), D4D_CnslNewLine(), and D4D_CnslPutChar().
static void D4D_CnslValue2Coor (D4D_OBJECT * pThis) static
Definition at line 82 of file d4d_console.c.
References _calc, D4D_SIZE::cx, D4D_SIZE::cy, D4D_CNSL_SCRLBR_WIDTH, D4D_ComputeGeometry(), D4D_GET_CONSOLE, D4D_GetClientToScreenPoint(), D4D_GetFontHeight(), D4D_GetFontWidth(), D4D_OBJECT_S::position, D4D_OBJECT_S::radius, D4D_CONSOLE::textFontId, and D4D_CONSOLE::txtArrSize.
Referenced by D4D_CnslOnInit(), D4D_CnslUpdateScrollbars(), and D4D_ConsoleOnDraw().
static void D4D_ConsoleOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 145 of file d4d_console.c.
References _calc, D4D_STRING_S::buffSize, D4D_CNSL_DATA_S::cursorPos, D4D_SIZE::cx, D4D_SIZE::cy, D4D_CNSL_CURSOR_HEIGHT, D4D_CNSL_FLAGS_CURSORSTATE, D4D_CNSL_FLAGS_REDRAWALL, D4D_CNSL_FLAGS_REDRAWCURSOR, D4D_CNSL_FLAGS_REDRAWLINE, D4D_CnslFindMaxTextLenght(), D4D_CnslValue2Coor(), D4D_DrawFrame(), D4D_DrawTextRect, D4D_FALSE, D4D_FillRect(), D4D_FillRRect(), D4D_FONT_FLAGS_FNT_WIDTH_PROPORTIONAL, D4D_GET_CONSOLE, D4D_GET_LIST_BOX_SCROLL_BAR_HOR, D4D_GET_LIST_BOX_SCROLL_BAR_VER, D4D_GetCharWidth(), D4D_GetFont(), D4D_GetFontHeight(), D4D_GetTextBuffWidthTab(), D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeFillColor(), D4D_ScrlBrGetPosition(), D4D_TRUE, D4D_MESSAGE_S::draw, D4D_CNSL_DATA_S::flags, D4D_FONT_DESCRIPTOR_S::flags, D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, D4D_CNSL_DATA_S::lastLineIx, NULL, D4D_CONSOLE::pData, D4D_FONT_TYPE::pFontDescriptor, D4D_MESSAGE_S::pObject, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_CONSOLE::pTxtArr, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_STRING_S::str_properties, D4D_STR_PROPERTIES_S::text_properties, D4D_CONSOLE::textFontId, D4D_CONSOLE::txtArrSize, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_ConsoleOnMessage().
void D4D_ConsoleOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 774 of file d4d_console.c.
References D4D_CaptureKeys(), D4D_CnslOnInit(), D4D_ConsoleOnDraw(), D4D_ConsoleTimeTick(), D4D_FALSE, D4D_FocusSet(), D4D_GET_LIST_BOX_SCROLL_BAR_VER, D4D_InvalidateObject(), D4D_KEY_SCANCODE_ENTER, D4D_KEY_SCANCODE_ESC, D4D_MSG_DRAW, D4D_MSG_KEYUP, D4D_MSG_KILLCAPTURE, D4D_MSG_KILLFOCUS, D4D_MSG_MOUSE_BTN_LEFT_UP, D4D_MSG_MOUSE_BTN_WHEEL_DOWN, D4D_MSG_MOUSE_BTN_WHEEL_UP, D4D_MSG_ONINIT, D4D_MSG_SETCAPTURE, D4D_MSG_SETFOCUS, D4D_MSG_TIMETICK, D4D_MSG_TOUCHED, D4D_OBJECT_F_NOTINIT, D4D_OBJECT_F_VISIBLE, D4D_ObjOnMessage(), D4D_ScrlBrChangePosition(), D4D_OBJECT_DATA_S::flags, D4D_MESSAGE_S::key, D4D_MESSAGE_S::nMsgId, NULL, D4D_OBJECT_S::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, and D4D_MESSAGE_S::pScreen.
static void D4D_ConsoleTimeTick (D4D_MESSAGE * pMsg) static
Definition at line 323 of file d4d_console.c.
References D4D_CNSL_CURSOR_BLINK_TICK_COUNTER, D4D_CNSL_FLAGS_CURSORSTATE, D4D_CNSL_FLAGS_REDRAWCURSOR, D4D_FALSE, D4D_GET_CONSOLE, D4D_InvalidateObject(), D4D_CNSL_DATA_S::flags, D4D_CONSOLE::pData, D4D_MESSAGE_S::pObject, and D4D_CNSL_DATA_S::tickCounter.
Referenced by D4D_ConsoleOnMessage().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_consoleSysFunc
Definition at line 62 of file d4d_console.c.