Freescale's eGUI: d4d_font.c File Reference
d4d_font.c File Reference
#include "d4d.h"
#include "common_files/d4d_lldapi.h"
#include "common_files/d4d_private.h"
Functions
static FNT_CHAR_PLACE D4D_LCD_GetCharPlace (const D4D_FONT_DESCRIPTOR *pFontDescriptorStart, D4D_TCHAR ch)
static D4D_INDEX_DELTA D4D_GetCharIndex (D4D_FONT_DESCRIPTOR *pFontDescriptor, D4D_TCHAR ch)
static D4D_FONT_DATA * D4D_GetCharData (FNT_CHAR_PLACE *char_place)
void D4D_SetFontTable (D4D_FONT_TYPE *pFontTable)
D4D_FONT_TYPE * D4D_GetFontTable (void)
D4D_FONT_TYPE * D4D_GetFont (D4D_FONT ix)
D4D_FONT_SIZES D4D_GetFontSize (D4D_FONT ix)
D4D_FONT_SIZE D4D_GetFontHeight (D4D_FONT ix)
D4D_FONT_SIZE D4D_GetFontWidth (D4D_FONT ix)
D4D_FONT_SIZE D4D_GetCharWidth (D4D_FONT ix, D4D_TCHAR ch)
static D4D_BOOL D4D_LCD_GetFntBit (CHAR_PXL_DESC *pPxlDesc)
D4D_COOR D4D_GetNextTab (D4D_TAB *pTab, D4D_COOR pos)
D4D_COOR D4D_LCD_PrintChr (D4D_TCHAR ch, D4D_PRINT_DESC *p_CharDes)
Variables
static D4D_FONT_TYPE * d4d_pFontTable
Detailed Description
D4D driver font c file.
Author
Petr Gargulak
Version
0.0.48.0
Date
Jan-14-2014
Definition in file d4d_font.c.
Function Documentation
D4D_FONT_DATA * D4D_GetCharData (FNT_CHAR_PLACE * char_place) static
Get pointer on bitmap of selected char of used font
Definition at line 554 of file d4d_font.c.
References D4D_FONT_FLAGS_FNT_WIDTH_PROPORTIONAL, and NULL.
Referenced by D4D_LCD_PrintChr().
static D4D_INDEX_DELTA D4D_GetCharIndex (D4D_FONT_DESCRIPTOR * pFontDescriptor, D4D_TCHAR ch) static
Get "real" index in data font table of used font
Definition at line 458 of file d4d_font.c.
References D4D_FONT_DESCRIPTOR_S::charCnt, D4D_FONT_FLAGS_IX_STYLE_NONLINEAR, D4D_FONT_FLAGS_IX_TYPE_MAP, D4D_FONT_DESCRIPTOR_S::flags, NULL, D4D_FONT_DESCRIPTOR_S::pIxTable, and D4D_FONT_DESCRIPTOR_S::startChar.
Referenced by D4D_LCD_GetCharPlace().
D4D_FONT_SIZE D4D_GetCharWidth (D4D_FONT ix, D4D_TCHAR ch)
Get selected font width information
Definition at line 415 of file d4d_font.c.
References D4D_FONT_TYPE::charSpacing, D4D_FONT_FLAGS_FNT_WIDTH_PROPORTIONAL, D4D_GetFont(), D4D_LCD_GetCharPlace(), NULL, D4D_FONT_TYPE::pFontDescriptor, D4D_FONT_TYPE::scale, and D4D_FONT_SIZES::width.
Referenced by D4D_CnslFindMaxTextLenght(), D4D_ConsoleOnDraw(), D4D_EditBoxOnDraw(), D4D_EditBoxSetCursor(), D4D_GetTextBuffWidthTab(), D4D_GetTextMaxLength(), D4D_GetTextWidth(), D4D_LCD_PrintChr(), D4D_LCD_PrintStr(), D4D_TextBoxGetCharsToLine(), and D4D_TextBoxGetWordSpecInt().
D4D_FONT_TYPE* D4D_GetFont (D4D_FONT ix)
Get selected font information
Definition at line 340 of file d4d_font.c.
References D4D_UNUSED, and NULL.
Referenced by D4D_ConsoleOnDraw(), D4D_DrawTextRectTab(), D4D_DrawTextRRectTab(), D4D_DrawTextTabXY(), D4D_GetCharWidth(), D4D_GetFontHeight(), D4D_GetFontWidth(), and D4D_GraphValue2Coor().
D4D_FONT_SIZE D4D_GetFontHeight (D4D_FONT ix)
Get selected font height information
Definition at line 381 of file d4d_font.c.
References D4D_FONT_DESCRIPTOR_S::charFullSize, D4D_FONT_TYPE::charSpacing, D4D_GetFont(), D4D_FONT_SIZES::height, NULL, D4D_FONT_TYPE::pFontDescriptor, and D4D_FONT_TYPE::scale.
Referenced by D4D_CnslValue2Coor(), D4D_ConsoleOnDraw(), D4D_DrawScreenNC(), D4D_DrawTextRectTab(), D4D_DrawTextRRectTab(), D4D_EditBoxOnDraw(), D4D_GaugOnDraw(), D4D_GetFontSize(), D4D_GetPositionCount(), D4D_GetScrHeaderSize(), D4D_GetTitleBarHeight(), D4D_GraphOnDraw(), D4D_GraphPrintLabel(), D4D_GraphValue2Coor(), D4D_IconOnDraw(), D4D_LCD_PrintChr(), D4D_LCD_PrintStr(), D4D_MenuOnDraw(), D4D_MenuValue2Coor(), D4D_SldrOnDraw(), D4D_TextBoxOnDraw(), and D4D_TextBoxValue2Coor().
D4D_FONT_SIZES D4D_GetFontSize (D4D_FONT ix)
Get selected font size information
Definition at line 365 of file d4d_font.c.
References D4D_GetFontHeight(), D4D_GetFontWidth(), D4D_FONT_SIZES::height, and D4D_FONT_SIZES::width.
D4D_FONT_TYPE* D4D_GetFontTable (void)
Definition at line 330 of file d4d_font.c.
References d4d_pFontTable.
D4D_FONT_SIZE D4D_GetFontWidth (D4D_FONT ix)
Get selected font width information
Definition at line 398 of file d4d_font.c.
References D4D_FONT_DESCRIPTOR_S::charFullSize, D4D_FONT_TYPE::charSpacing, D4D_GetFont(), NULL, D4D_FONT_TYPE::pFontDescriptor, D4D_FONT_TYPE::scale, and D4D_FONT_SIZES::width.
Referenced by D4D_CnslValue2Coor(), D4D_GetFontSize(), D4D_GraphGetSizeLblY(), and D4D_MenuOnDraw().
D4D_COOR D4D_GetNextTab (D4D_TAB * pTab, D4D_COOR pos)
Definition at line 618 of file d4d_font.c.
References NULL, D4D_TAB::pTabTable, and D4D_TAB::tabOffset.
Referenced by D4D_GetTextBuffWidthTab(), D4D_LCD_PrintChr(), and D4D_TextBoxGetWordSpecInt().
static FNT_CHAR_PLACE D4D_LCD_GetCharPlace (const D4D_FONT_DESCRIPTOR * pFontDescriptorStart, D4D_TCHAR ch) static
Find the exact descriptor and char ix
Definition at line 502 of file d4d_font.c.
References D4D_FONT_DESCRIPTOR_S::charDefault, D4D_GetCharIndex(), NULL, D4D_FONT_DESCRIPTOR_S::pNext, and D4D_FONT_DESCRIPTOR_S::startChar.
Referenced by D4D_GetCharWidth(), and D4D_LCD_PrintChr().
static D4D_BOOL D4D_LCD_GetFntBit (CHAR_PXL_DESC * pPxlDesc) static
Get "real" index in data font table of used font
Definition at line 585 of file d4d_font.c.
References D4D_FONT_PACK_BITORDER_LITTLEEND, D4D_FONT_PACK_COMPRESSED_ON, D4D_FONT_PACK_SCANBASED_COLUMN, and D4D_FONT_PACK_SCANPREFERRED_COLUMN.
Referenced by D4D_LCD_PrintChr().
D4D_COOR D4D_LCD_PrintChr (D4D_TCHAR ch, D4D_PRINT_DESC * p_CharDes)
Print the Char in ASCII in simple format up to 8 columns
Definition at line 645 of file d4d_font.c.
References D4D_FONT_TYPE::charSpacing, D4D_PRINT_DESC::colorBack, D4D_PRINT_DESC::colorText, D4D_FNT_PRTY_TRANSPARENT_MASK, D4D_FONT_FLAGS_FNT_WIDTH_PROPORTIONAL, D4D_GetCharData(), D4D_GetCharWidth(), D4D_GetFontHeight(), D4D_GetNextTab(), D4D_LCD_Box(), D4D_LCD_GetCharPlace(), D4D_LCD_GetFntBit(), D4D_LLD_LCD, D4DLCD_FUNCTIONS_S::D4DLCD_Send_PixelColor, D4DLCD_FUNCTIONS_S::D4DLCD_SetWindow, D4D_FONT_SIZES::height, D4D_FONT_TYPE::ix_font, NULL, D4D_FONT_TYPE::pFontDescriptor, D4D_PRINT_DESC::pFontType, D4D_PRINT_DESC::properties, D4D_PRINT_DESC::pTab, D4D_FONT_TYPE::scale, D4D_FONT_SIZES::width, D4D_PRINT_DESC::x, and D4D_PRINT_DESC::y.
Referenced by D4D_LCD_PrintStr().
void D4D_SetFontTable (D4D_FONT_TYPE * pFontTable)
Change the Font Table
Definition at line 314 of file d4d_font.c.
References d4d_FontTable, and NULL.
Variable Documentation
D4D_FONT_TYPE* d4d_pFontTable static
Definition at line 78 of file d4d_font.c.
Referenced by D4D_GetFontTable().