Freescale's eGUI: d4d_menu.c File Reference
d4d_menu.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_MenuOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_MenuGetTextBuffer (D4D_OBJECT *pThis)
static void D4D_MenuOnInit (D4D_MESSAGE *pMsg)
static D4D_MENU_INDEX D4D_GetItemsCount (D4D_MENU *pMenu)
static D4D_SIZE D4D_GetIconsMaxSize (D4D_MENU *pMenu)
static D4D_COOR D4D_GetTitleBarHeight (D4D_OBJECT *pThis)
static void D4D_MenuValue2Coor (D4D_OBJECT *pThis)
static void D4D_MenuOnDraw (D4D_MESSAGE *pMsg)
static void D4D_MenuFocusNextItem (D4D_OBJECT *pThis)
static void D4D_MenuFocusPreviousItem (D4D_OBJECT *pThis)
static void D4D_MenuOnKeyDown (D4D_MESSAGE *pMsg)
static void D4D_MenuOnKeyUp (D4D_MESSAGE *pMsg)
static D4D_BOOL D4D_MenuScrollBarSetup (D4D_OBJECT *pObject)
void D4D_MenuScrollBarsFeedBack (D4D_OBJECT *pThis, D4D_INDEX old_position, D4D_INDEX new_position)
D4D_MENU_INDEX D4D_MenuGetIndex (D4D_OBJECT *pThis)
Function returns the current selected item index.
void D4D_MenuSetIndex (D4D_OBJECT *pThis, D4D_MENU_INDEX ix)
Function select new item by index.
D4D_MENU_INDEX D4D_MenuGetItemCount (D4D_OBJECT_PTR pThis)
Function gets the count of menu items.
D4D_MENU_INDEX D4D_MenuFindUserDataItem (D4D_OBJECT_PTR pThis, void *pUser)
Function finds the index of items with specified user data.
void * D4D_MenuGetItemUserData (D4D_OBJECT_PTR pThis)
Function gets the selected item user data.
D4D_STRING * D4D_MenuGetItemText (D4D_OBJECT_PTR pThis)
Function gets the selected item text.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_menuSysFunc
Detailed Description
D4D driver menu object c file.
Author
Petr Gargulak
Version
0.0.51.0
Date
Jan-14-2014
Definition in file d4d_menu.c.
Macro Definition Documentation
#define _calc
Definition at line 78 of file d4d_menu.c.
Referenced by D4D_MenuFocusNextItem(), D4D_MenuFocusPreviousItem(), D4D_MenuOnDraw(), D4D_MenuScrollBarSetup(), and D4D_MenuValue2Coor().
Function Documentation
static D4D_SIZE D4D_GetIconsMaxSize (D4D_MENU * pMenu) static
Definition at line 89 of file d4d_menu.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_GetBmpHeight(), D4D_GetBmpWidth(), D4D_GetItemsCount(), NULL, D4D_MENU_ITEM::pIcon, and D4D_MENU::pItems.
Referenced by D4D_MenuValue2Coor().
static D4D_MENU_INDEX D4D_GetItemsCount (D4D_MENU * pMenu) static
Definition at line 141 of file d4d_menu.c.
References D4D_MENU_ITEM::pIcon, D4D_MENU::pItems, D4D_STRING_S::pText, and D4D_MENU_ITEM::text.
Referenced by D4D_GetIconsMaxSize(), D4D_MenuFindUserDataItem(), D4D_MenuGetItemCount(), D4D_MenuSetIndex(), and D4D_MenuValue2Coor().
static D4D_COOR D4D_GetTitleBarHeight (D4D_OBJECT * pThis) static
Definition at line 111 of file d4d_menu.c.
References D4D_GET_MENU, D4D_GetBmpHeight(), D4D_GetFontHeight(), D4D_MENU_F_INDEX, D4D_STRING_S::fontId, D4D_MENU::indexFontId, D4D_OBJECT_S::initFlags, NULL, D4D_MENU::pIcon, D4D_STRING_S::pText, D4D_OBJECT_S::radius, and D4D_MENU::title_text.
Referenced by D4D_MenuValue2Coor().
static void D4D_MenuFocusNextItem (D4D_OBJECT * pThis) static
Definition at line 360 of file d4d_menu.c.
References _calc, D4D_GET_MENU, D4D_GET_MENU_SCROLL_BAR_HOR, D4D_MenuValue2Coor(), D4D_ScrlBrSetPosition(), D4D_MENU_DATA::ix, D4D_MENU_DATA::page_ix, and D4D_MENU::pData.
Referenced by D4D_MenuOnKeyDown(), and D4D_MenuOnMessage().
static void D4D_MenuFocusPreviousItem (D4D_OBJECT * pThis) static
Definition at line 394 of file d4d_menu.c.
References _calc, D4D_GET_MENU, D4D_GET_MENU_SCROLL_BAR_HOR, D4D_MenuValue2Coor(), D4D_ScrlBrSetPosition(), D4D_MENU_DATA::ix, D4D_MENU_DATA::page_ix, and D4D_MENU::pData.
Referenced by D4D_MenuOnKeyDown(), and D4D_MenuOnMessage().
D4D_STRING * D4D_MenuGetTextBuffer (D4D_OBJECT * pThis)
Get object text buffer
Definition at line 796 of file d4d_menu.c.
References D4D_GET_MENU.
static void D4D_MenuOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 205 of file d4d_menu.c.
References _calc, D4D_CLR_SCHEME_S::bckgFocus, D4D_STRING_S::buffSize, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ASSERT, D4D_DrawFrame(), D4D_DrawRBmp, D4D_DrawTextRect, D4D_FillRRect(), D4D_GET_MENU, D4D_GET_MENU_SCROLL_BAR_HOR, D4D_GetBmpHeight(), D4D_GetFontHeight(), D4D_GetFontWidth(), D4D_GetTextLength(), D4D_GetTextWidth(), D4D_IsEnabled(), D4D_LINE_THIN, D4D_LineToXY(), D4D_MENU_F_INDEX, D4D_MENU_ITEM_FNT_PRTY_DEFAULT, D4D_MENU_ITEM_TXT_PRTY_DEFAULT, D4D_MENU_IX_FNT_PRTY_DEFAULT, D4D_MENU_IX_TXT_PRTY_DEFAULT, D4D_MENU_SCRLBR_WIDTH, D4D_MenuValue2Coor(), D4D_MoveToXY(), D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_OBJECT_F_VISIBLE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeFillColor(), D4D_ObjectGetScheme(), D4D_SCRATCHPAD_SIZE, D4D_MESSAGE_S::draw, D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, D4D_CLR_SCHEME_S::foreFocus, D4D_MENU::indexFontId, D4D_OBJECT_S::initFlags, D4D_MENU::itemsFontId, D4D_MENU_DATA::ix, NULL, D4D_MENU_DATA::page_ix, D4D_MENU::pData, D4D_MENU_ITEM::pIcon, D4D_MENU::pIcon, D4D_MENU::pItems, D4D_MESSAGE_S::pObject, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_STRING_S::str_properties, D4D_MENU_ITEM::text, D4D_STR_PROPERTIES_S::text_properties, D4D_MENU::title_text, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_MenuOnMessage().
static void D4D_MenuOnInit (D4D_MESSAGE * pMsg) static
Definition at line 586 of file d4d_menu.c.
References D4D_GET_MENU_SCROLL_BAR_HOR, D4D_InvalidateObject(), D4D_MenuScrollBarSetup(), D4D_TRUE, D4D_OBJECT_S::pData, D4D_MESSAGE_S::pObject, and D4D_OBJECT_DATA_S::pScreen.
Referenced by D4D_MenuOnMessage().
static void D4D_MenuOnKeyDown (D4D_MESSAGE * pMsg) static
Definition at line 432 of file d4d_menu.c.
References D4D_FALSE, D4D_GetCapturedObject(), D4D_InvalidateObject(), D4D_KEY_SCANCODE_DOWN, D4D_KEY_SCANCODE_UP, D4D_MenuFocusNextItem(), D4D_MenuFocusPreviousItem(), D4D_MESSAGE_S::key, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::prm.
Referenced by D4D_MenuOnMessage().
static void D4D_MenuOnKeyUp (D4D_MESSAGE * pMsg) static
Definition at line 455 of file d4d_menu.c.
References D4D_CaptureKeys(), D4D_FALSE, D4D_GET_MENU, D4D_GetCapturedObject(), D4D_InvalidateObject(), D4D_KEY_SCANCODE_ENTER, D4D_KEY_SCANCODE_ESC, D4D_MENU_DATA::ix, D4D_MESSAGE_S::key, NULL, D4D_MENU::OnClicked, D4D_MENU::pData, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::prm.
Referenced by D4D_MenuOnMessage().
void D4D_MenuOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 737 of file d4d_menu.c.
References D4D_GetMouseCoordinates, D4D_GetTouchScreenCoordinates(), D4D_MenuFocusNextItem(), D4D_MenuFocusPreviousItem(), D4D_MenuOnDraw(), D4D_MenuOnInit(), D4D_MenuOnKeyDown(), D4D_MenuOnKeyUp(), D4D_MSG_DRAW, D4D_MSG_KEYDOWN, D4D_MSG_KEYUP, D4D_MSG_MOUSE_BTN_LEFT_UP, D4D_MSG_MOUSE_BTN_WHEEL_DOWN, D4D_MSG_MOUSE_BTN_WHEEL_UP, D4D_MSG_ONINIT, D4D_MSG_TOUCH_AUTO, D4D_MSG_TOUCHED, D4D_OBJECT_F_NOTINIT, D4D_ObjOnMessage(), D4D_OBJECT_DATA_S::flags, D4D_MESSAGE_S::nMsgId, D4D_OBJECT_S::pData, and D4D_MESSAGE_S::pObject.
static D4D_BOOL D4D_MenuScrollBarSetup (D4D_OBJECT * pObject) static
Definition at line 548 of file d4d_menu.c.
References _calc, D4D_SIZE::cx, D4D_SIZE::cy, D4D_FALSE, D4D_GET_MENU_SCROLL_BAR_HOR, D4D_GetScreenToClientPoint(), D4D_LimitU, D4D_MENU_F_SIDEBAR, D4D_MENU_SCRLBR_STEP, D4D_MENU_SCRLBR_WIDTH, D4D_MenuValue2Coor(), D4D_OBJECT_F_VISIBLE, D4D_ScrlBrSetPosition(), D4D_ScrlBrSetRange(), D4D_ScrlBrSetStep(), D4D_TRUE, D4D_OBJECT_DATA_S::flags, D4D_OBJECT_S::initFlags, D4D_OBJECT_S::pData, D4D_OBJECT_S::position, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_MenuOnInit().
void D4D_MenuScrollBarsFeedBack (D4D_OBJECT * pThis, D4D_INDEX old_position, D4D_INDEX new_position)
Definition at line 597 of file d4d_menu.c.
References D4D_FALSE, D4D_GET_MENU, D4D_GetParentObject(), D4D_InvalidateObject(), D4D_UNUSED, D4D_MENU_DATA::ix, D4D_MENU_DATA::page_ix, and D4D_MENU::pData.
static void D4D_MenuValue2Coor (D4D_OBJECT * pThis) static
Definition at line 154 of file d4d_menu.c.
References _calc, D4D_SIZE::cy, D4D_ComputeGeometry(), D4D_GET_MENU, D4D_GetClientToScreenPoint(), D4D_GetFontHeight(), D4D_GetIconsMaxSize(), D4D_GetItemsCount(), D4D_GetTitleBarHeight(), D4D_MENU_F_INDEX, D4D_SprintDecU8(), D4D_OBJECT_S::initFlags, D4D_MENU::itemsFontId, D4D_MENU_DATA::ix, D4D_MENU::pData, D4D_MENU::posCnt, D4D_OBJECT_S::position, D4D_OBJECT_S::size, and D4D_MENU::textOff.
Referenced by D4D_MenuFocusNextItem(), D4D_MenuFocusPreviousItem(), D4D_MenuOnDraw(), and D4D_MenuScrollBarSetup().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_menuSysFunc
Definition at line 56 of file d4d_menu.c.