Freescale's eGUI: d4d_slider.c File Reference
d4d_slider.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_SldrOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_SldrGetTextBuffer (D4D_OBJECT *pThis)
static D4D_COLOR D4D_SldrComputeColorBar (D4D_OBJECT *pThis, D4D_SLIDER_VALUE value)
static void D4D_SldrValue2Coor (D4D_OBJECT *pThis)
static void D4D_SldrOnDraw (D4D_MESSAGE *pMsg)
static void D4D_SldrOnKeyUp (D4D_MESSAGE *pMsg)
void D4D_SldrSetValue (D4D_OBJECT_PTR pThis, D4D_SLIDER_VALUE value)
Function Sets the slider value.
D4D_SLIDER_VALUE D4D_SldrGetValue (D4D_OBJECT_PTR pThis)
Function Gets the slider value.
void D4D_SldrSetBarColor (D4D_OBJECT_PTR pThis, D4D_COLOR color)
Function Sets the slider bar color.
D4D_COLOR D4D_SldrGetBarColor (D4D_OBJECT_PTR pThis)
void D4D_SldrChangeValue (D4D_OBJECT_PTR pThis, D4D_SLIDER_VALUE incr)
Function change the slider value by signed increment.
void D4D_SldrSetLimits (D4D_OBJECT_PTR pThis, const D4D_SLIDER_LIMITS *pLimits)
Function set the new limits of slider object.
void D4D_SldrGetLimits (D4D_OBJECT_PTR pThis, D4D_SLIDER_LIMITS *pLimits)
Function get the current limits of slider object.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_sliderSysFunc
Detailed Description
D4D driver slider object c file.
Author
Petr Gargulak
Version
0.0.68.0
Date
Jan-14-2014
Definition in file d4d_slider.c.
Macro Definition Documentation
#define _calc
Definition at line 77 of file d4d_slider.c.
Referenced by D4D_SldrOnDraw(), and D4D_SldrValue2Coor().
Function Documentation
static D4D_COLOR D4D_SldrComputeColorBar (D4D_OBJECT * pThis, D4D_SLIDER_VALUE value) static
Definition at line 462 of file d4d_slider.c.
References D4D_CLR_SCHEME_SLDR::barEnd, D4D_CLR_SCHEME_SLDR::barStart, D4D_GET_SLIDER, D4D_GetCrossColor(), D4D_MulDivUU8(), D4D_ObjectGetScheme(), D4D_SLIDER_DATA::limits, D4D_CLR_SCHEME_S::objectDepend, D4D_SLIDER::pData, D4D_CLR_SCHEME_OBJ::slider, D4D_SLIDER_LIMITS::valueMax, D4D_SLIDER_LIMITS::valueMin, and D4D_SLIDER_LIMITS::valueOrg.
Referenced by D4D_SldrOnMessage(), and D4D_SldrSetValue().
D4D_STRING * D4D_SldrGetTextBuffer (D4D_OBJECT * pThis)
Get object text buffer
Definition at line 712 of file d4d_slider.c.
References D4D_GET_SLIDER.
static void D4D_SldrOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 292 of file d4d_slider.c.
References _calc, D4D_CLR_SCHEME_SLDR::barBckg, D4D_SLIDER_DATA::colorBar, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ASSERT, D4D_COLOR_SLDR_BAR_START, D4D_DrawFrame(), D4D_DrawRBmp, D4D_DrawTextRect, D4D_FillRRect(), D4D_FillRRectColorScale(), D4D_GET_SLIDER, D4D_GetFontHeight(), D4D_GetGreyScale(), D4D_GetTextWidth(), D4D_IsEnabled(), D4D_LINE_THIN, D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgColor(), D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetScheme(), D4D_RRect(), D4D_SCRATCHPAD_SIZE, D4D_SLDR_F_BAR_SCALECOLOR, D4D_SLDR_F_TEXT_AUTOCOLOR, D4D_SldrValue2Coor(), D4D_MESSAGE_S::draw, D4D_STRING_S::fontId, D4D_OBJECT_S::initFlags, NULL, D4D_CLR_SCHEME_S::objectDepend, D4D_SLIDER::pBmpBkgd, D4D_SLIDER::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_CLR_SCHEME_OBJ::slider, D4D_SLIDER::textBuff, D4D_SLIDER::txtOff, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_SldrOnMessage().
static void D4D_SldrOnKeyUp (D4D_MESSAGE * pMsg) static
Definition at line 390 of file d4d_slider.c.
References D4D_CaptureKeys(), D4D_GET_SLIDER, D4D_GetCapturedObject(), D4D_KEY_SCANCODE_DOWN, D4D_KEY_SCANCODE_ENTER, D4D_KEY_SCANCODE_ESC, D4D_KEY_SCANCODE_LEFT, D4D_KEY_SCANCODE_RIGHT, D4D_KEY_SCANCODE_UP, D4D_SldrChangeValue(), D4D_MESSAGE_S::key, D4D_SLIDER_DATA::limits, NULL, D4D_SLIDER::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, and D4D_SLIDER_LIMITS::step.
Referenced by D4D_SldrOnMessage().
void D4D_SldrOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 630 of file d4d_slider.c.
References D4D_CLR_SCHEME_SLDR::barFore, D4D_CaptureKeys(), D4D_GET_SLIDER, D4D_GetMouseCoordinates, D4D_GetTouchScreenCoordinates(), D4D_MSG_DRAW, D4D_MSG_KEYUP, D4D_MSG_KILLFOCUS, D4D_MSG_MOUSE_BTN_LEFT_UP, D4D_MSG_MOUSE_BTN_WHEEL_DOWN, D4D_MSG_MOUSE_BTN_WHEEL_UP, D4D_MSG_ONINIT, D4D_MSG_TOUCH_AUTO, D4D_MSG_TOUCHED, D4D_OBJECT_F_NOTINIT, D4D_ObjectGetScheme(), D4D_ObjOnMessage(), D4D_SLDR_AUTOTOUCHTICKS, D4D_SLDR_F_AUTOTOUCH_OFF, D4D_SLDR_F_BAR_AUTOCOLOR, D4D_SLDR_F_BAR_SCALECOLOR, D4D_SldrChangeValue(), D4D_SldrComputeColorBar(), D4D_SldrOnDraw(), D4D_SldrOnKeyUp(), D4D_OBJECT_DATA_S::flags, D4D_OBJECT_S::initFlags, D4D_SLIDER_DATA::limits, D4D_MESSAGE_S::nMsgId, NULL, D4D_CLR_SCHEME_S::objectDepend, D4D_OBJECT_S::pData, D4D_SLIDER::pData, D4D_MESSAGE_S::pObject, D4D_CLR_SCHEME_OBJ::slider, and D4D_SLIDER_LIMITS::step.
static void D4D_SldrValue2Coor (D4D_OBJECT * pThis) static
Definition at line 87 of file d4d_slider.c.
References _calc, D4D_SLIDER::barOff, D4D_SLIDER::barSize, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ComputeGeometry(), D4D_DIR_DOWN, D4D_DIR_LEFT, D4D_DIR_RIGHT, D4D_DIR_UP, D4D_FALSE, D4D_GET_SLIDER, D4D_GetClientToScreenPoint(), D4D_LimitU, D4D_MulDivUU, D4D_RndCornerGetNonPrintedPxl(), D4D_SLDR_BAR_OFF_LENGTH, D4D_SLDR_BAR_OFF_WIDTH, D4D_TRUE, D4D_SLIDER_DATA::limits, D4D_SLIDER::pData, D4D_OBJECT_S::position, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_SLIDER_DATA::value, D4D_SLIDER_LIMITS::valueMax, D4D_SLIDER_LIMITS::valueMin, D4D_SLIDER_LIMITS::valueOrg, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_SldrOnDraw().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_sliderSysFunc
Definition at line 53 of file d4d_slider.c.