Freescale's eGUI: d4d_string.c File Reference
d4d_string.c File Reference
#include "d4d.h"
#include "common_files/d4d_lldapi.h"
#include "common_files/d4d_private.h"
Functions
D4D_TCHAR * D4D_GetInternalStringPointer (const D4D_TCHAR *originTxt)
The function gets the real internal pointer to string.
Byte D4D_SprintDecU32 (LWord val, D4D_TCHAR *pText, D4D_TCHAR fill)
The function convert decimal unsigned 32 bit number to string.
Byte D4D_SprintDecS32 (sLWord val, D4D_TCHAR *pText, D4D_TCHAR fill)
The function convert decimal signed 32 bit number to string.
Byte D4D_SprintDecU16 (Word val, D4D_TCHAR *pText, D4D_TCHAR fill)
The function convert decimal unsigned 16 bit number to string.
Byte D4D_SprintDecS16 (sWord val, D4D_TCHAR *pText, D4D_TCHAR fill)
The function convert decimal signed 16 bit number to string.
Byte D4D_SprintDecU8 (Byte val, D4D_TCHAR *pText, D4D_TCHAR fill)
The function convert decimal unsigned 8 bit number to string.
Byte D4D_SprintDecS8 (sByte val, D4D_TCHAR *pText, D4D_TCHAR fill)
The function convert decimal signed 8 bit number to string.
D4D_INDEX D4D_GetTextLength (D4D_TCHAR *pText)
The function returns lenght of text.
D4D_COOR D4D_GetTextWidth (D4D_FONT ix, D4D_TCHAR *pText)
The function returns width of text in pixels.
D4D_COOR D4D_GetTextBuffWidthTab (D4D_STRING *text_buffer, D4D_TAB *pTab)
The function returns width of text in pixels, also with tab table.
D4D_INDEX D4D_GetTextMaxLength (D4D_STRING *pString, D4D_COOR maxWidth)
The function find out the maximal text length that fits to maximal pixel width.
void D4D_SetText (D4D_OBJECT_PTR pObject, D4D_TCHAR *pText)
The function change the text in main object text buffer.
void D4D_ChangeText (D4D_STRING *pBuff, D4D_TCHAR *pNewText, D4D_TCHAR fillChar)
void D4D_LCD_PrintStr (D4D_PRINT_DESC *p_StrDes)
Detailed Description
D4D driver font c file.
Author
Petr Gargulak
Version
0.0.3.0
Date
Jan-14-2014
Definition in file d4d_string.c.
Function Documentation
void D4D_ChangeText (D4D_STRING * pBuff, D4D_TCHAR * pNewText, D4D_TCHAR fillChar)
change text in the buffer
Definition at line 599 of file d4d_string.c.
References D4D_STRING_S::buffSize, D4D_GetTextLength(), and D4D_STRING_S::pText.
Referenced by D4D_SetText().
void D4D_LCD_PrintStr (D4D_PRINT_DESC * p_StrDes)
Print the String in ASCII in simple format up to 8 columns
Definition at line 635 of file d4d_string.c.
References D4D_STRING_S::buffSize, D4D_PRINT_DESC::colorBack, D4D_PRINT_DESC::colorText, D4D_DEFSTR, D4D_EXTSRC_BUFF_SIZE, d4d_extsrcBuffer, d4d_extsrcLocale, D4D_FALSE, D4D_FillRectXY(), D4D_FNT_PRTY_STRIKETHROUGH_MASK, D4D_FNT_PRTY_STRIKETHROUGH_SHIFT, D4D_FNT_PRTY_TRANSPARENT_MASK, D4D_FNT_PRTY_UNDERLINE_DOT_MASK, D4D_FNT_PRTY_UNDERLINE_LINE_MASK, D4D_FNT_PRTY_UNDERLINE_MASK, D4D_GetCharWidth(), D4D_GetFontHeight(), D4D_GetInternalStringPointer(), D4D_GetTextBuffWidthTab(), D4D_GetTextLength(), D4D_GetTextWidth(), D4D_LCD_PrintChr(), D4D_LLD_LCD, D4D_TRUE, D4DLCD_FLSH_ELEMENT, D4DLCD_FUNCTIONS_S::D4DLCD_FlushBuffer, D4DLOCALE_FUNCTIONS_S::D4DLOCALE_TranslateStr, D4D_STRING_S::fontId, D4D_FONT_SIZES::height, D4D_FONT_TYPE::ix_font, D4D_PRINT_DESC::maxWidth, NULL, D4D_FONT_TYPE::pFontDescriptor, D4D_PRINT_DESC::pFontType, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_PRINT_DESC::properties, D4D_PRINT_DESC::pTab, D4D_STRING_S::pText, D4D_PRINT_DESC::pText, D4D_FONT_TYPE::scale, D4D_TAB::tabOffset, D4D_PRINT_DESC::textLength, D4D_PRINT_DESC::textOffset, D4D_FONT_SIZES::width, D4D_PRINT_DESC::x, and D4D_PRINT_DESC::y.
Referenced by D4D_DrawTextRectTab(), D4D_DrawTextRRectTab(), and D4D_DrawTextTabXY().