Freescale's eGUI: d4d_screen.c File Reference
d4d_screen.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
#include "common_files/d4d_lldapi.h"
Functions
static D4D_COOR D4D_GetScrHeaderTitleOffset (D4D_SCREEN *pScreen)
static D4D_BOOL D4D_GetScrHeaderExitBtnCoor (D4D_SCREEN *pScreen, D4D_POINT *resultPos, D4D_SIZE *resultSize)
static void D4D_DrawScreenNC (D4D_SCREEN *pScreen, D4D_BOOL active)
static D4D_OBJECT * D4D_FindObject (D4D_SCREEN *pScreen, D4D_OBJECT_PTR pObject)
static void D4D_ChangeScreen (D4D_SCREEN *pNewScreen, D4D_SCREEN *pOldScreen)
D4D_SCREEN * D4D_GetActiveScreen (void)
Returns pointer to current active screen.
void D4D_ActivateScreen (D4D_SCREEN *pNewScreen, D4D_BOOL bReplaceCurrent)
The function activate the new screen.
void D4D_EscapeScreen (void)
The function return to previous screen recorded in the history.
void D4D_EscapeToBaseScreen (void)
The function return to base screen recorded in the history.
void D4D_InitScreen (D4D_SCREEN *pScreen)
The function inits the screen and its objects for first time case.
void D4D_InvalidateScreen (D4D_SCREEN *pScreen, D4D_BOOL bComplete)
The function mark the screen and its abject as "redraw pending".
D4D_OBJECT_PTR D4D_GetFocusedObject (D4D_SCREEN *pScreen)
The function returns pointer to object that is focused in given screen.
void D4D_FocusNextObject (D4D_SCREEN *pScreen, D4D_BOOL bInitialSearch)
The function change focus to the next object in the given screen.
void D4D_FocusPrevObject (D4D_SCREEN *pScreen)
The function change focus to the previous object in the given screen.
void D4D_FocusSet (D4D_SCREEN *pScreen, D4D_OBJECT_PTR pObject)
The function set the obejct focus to new object.
void D4D_SetScreenFontProperties (D4D_SCREEN *pScreen, D4D_FONT_PROPERTIES property)
The function sets the screen font properties.
void D4D_SetScreenTextProperties (D4D_SCREEN *pScreen, D4D_TEXT_PROPERTIES property)
The function sets the screen text properties.
D4D_POINT D4D_GetClientToScreenPoint (D4D_OBJECT *pObject, D4D_POINT *nClientPoint)
The function convert client point on the screen to the global screen point.
D4D_POINT D4D_GetScreenToClientPoint (D4D_OBJECT *pObject, D4D_POINT *nScreenPoint)
The function convert global screen point on the screen to the client point.
D4D_BOOL D4D_ScrCheckCoor (D4D_SCREEN *pScreen, D4D_POINT *point)
The function check if the coordination are in screen area.
D4D_OBJECT * D4D_GetLastObject (D4D_SCREEN *pScreen)
The function returns the pointer to last object in the screen.
D4D_COOR D4D_GetScrHeaderSize (D4D_SCREEN *pScreen)
static void D4D_RedrawScreenObject (D4D_OBJECT *pObject, D4D_BOOL complete)
void D4D_RedrawScreen (D4D_SCREEN *pScreen)
void D4D_HandleTimeTicks (D4D_SCREEN *pScreen)
D4D_BOOL D4D_ScrCheckExitBtnCoor (D4D_SCREEN *pScreen, D4D_POINT *point)
Variables
D4D_MARGIN d4d_screenMarginDflt
Detailed Description
D4D driver screen functions c file.
Author
Petr Gargulak
Version
0.0.44.0
Date
Jan-14-2014
Definition in file d4d_screen.c.
Function Documentation
static void D4D_ChangeScreen (D4D_SCREEN * pNewScreen, D4D_SCREEN * pOldScreen) static
Change the active screen
Definition at line 702 of file d4d_screen.c.
References D4D_ClearKeysBuffer(), D4D_DrawScreenNC(), D4D_FALSE, D4D_InitScreen(), D4D_InvalidateScreen(), D4D_MouseChangedScreen, D4D_MSG_KILLFOCUS, D4D_MSG_SETFOCUS, D4D_OBJECT_F_REDRAWSTATE, D4D_SendMessage(), D4D_SetObjectFlags(), D4D_TRUE, D4D_SCREEN_DATA::focusedObject, D4D_MESSAGE_S::nMsgId, NULL, D4D_SCREEN_S::OnActivate, D4D_SCREEN_S::OnDeactivate, D4D_SCREEN_S::pData, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_ActivateScreen(), D4D_EscapeScreen(), and D4D_EscapeToBaseScreen().
static void D4D_DrawScreenNC (D4D_SCREEN * pScreen, D4D_BOOL active) static
Redraw non client screen area - Header, background, title, etc.
Definition at line 864 of file d4d_screen.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_Bevel(), D4D_BEVEL_RAISED, D4D_BEVEL_WIDTH, D4D_DrawRBmp, D4D_DrawText, D4D_FillRRect(), D4D_GetBmpHeight(), D4D_GetFontHeight(), D4D_GetGreyScale(), D4D_GetScrHeaderExitBtnCoor(), D4D_GetScrHeaderSize(), D4D_GetScrHeaderTitleOffset(), D4D_LINE_THIN, D4D_LineTo(), D4D_MoveTo(), D4D_RBox(), D4D_RRect(), D4D_SCR_EXITBTN_CROSS_SIZE, D4D_SCR_F_BCKG, D4D_SCR_F_BEVEL, D4D_SCR_F_EXIT, D4D_SCR_F_OUTLINE, D4D_SCR_F_TITLEBAR, D4D_SCR_TITLE_OFF_X, D4D_ScreenGetScheme(), D4D_CLR_SCHEME_SCR::desktop, D4D_CLR_SCHEME_SCR::exitBtnBckg, D4D_CLR_SCHEME_SCR::exitBtnFore, D4D_SCREEN_S::flags, D4D_STRING_S::fontId, NULL, D4D_CLR_SCHEME_SCR::outline, D4D_SCREEN_S::pIcon, D4D_GEOMETRY::pnt, D4D_SCREEN_S::position, D4D_STRING_S::pText, D4D_SCREEN_S::radius, D4D_CLR_SCHEME_S::screen, D4D_SCREEN_S::size, D4D_GEOMETRY::sz, D4D_SCREEN_S::textBuff, D4D_CLR_SCHEME_SCR::title_bar, D4D_CLR_SCHEME_SCR::title_text, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_ChangeScreen(), and D4D_RedrawScreen().
static D4D_OBJECT * D4D_FindObject (D4D_SCREEN * pScreen, D4D_OBJECT_PTR pObject) static
Find object's index
Definition at line 676 of file d4d_screen.c.
References D4D_FindNextObject(), D4D_TRUE, D4D_SCREEN_DATA::focusedObject, NULL, and D4D_SCREEN_S::pData.
Referenced by D4D_FocusSet().
D4D_OBJECT* D4D_GetLastObject (D4D_SCREEN * pScreen)
The function returns the pointer to last object in the screen.
Parameters
pScreen - the pointer to screen
Returns
pointer to last screen object
Note
It's useful if the last object should be find
Definition at line 656 of file d4d_screen.c.
References NULL, and D4D_SCREEN_S::pObjects.
Referenced by D4D_FindPreviousObjectOnScreen().
static D4D_BOOL D4D_GetScrHeaderExitBtnCoor (D4D_SCREEN * pScreen, D4D_POINT * resultPos, D4D_SIZE * resultSize) static
Compute position of exit button on screen header title
Definition at line 818 of file d4d_screen.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_BEVEL_WIDTH, D4D_FALSE, D4D_GetScrHeaderSize(), D4D_SCR_F_BEVEL, D4D_SCR_F_OUTLINE, D4D_SCR_TITLE_EXITBTN_MIN_SIZE, D4D_SCR_TITLE_EXITBTN_OFFSET, D4D_TRUE, D4D_SCREEN_S::flags, NULL, D4D_SCREEN_S::position, D4D_SCREEN_S::size, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_DrawScreenNC(), and D4D_ScrCheckExitBtnCoor().
D4D_COOR D4D_GetScrHeaderSize (D4D_SCREEN * pScreen)
Compute size of screen header
Definition at line 767 of file d4d_screen.c.
References D4D_GetBmpHeight(), D4D_GetFontHeight(), D4D_SCR_F_TITLEBAR, D4D_SCR_HEADER_SIZE_MIN_SIZE, D4D_SCR_TITLE_OFF_Y, D4D_SCREEN_S::flags, D4D_STRING_S::fontId, NULL, D4D_SCREEN_S::pIcon, D4D_STRING_S::pText, and D4D_SCREEN_S::textBuff.
Referenced by D4D_DrawScreenNC(), D4D_GetClientScreenSize(), D4D_GetClientToScreenPoint(), D4D_GetScreenToClientPoint(), D4D_GetScrHeaderExitBtnCoor(), and D4D_ScrCheckCoor().
static D4D_COOR D4D_GetScrHeaderTitleOffset (D4D_SCREEN * pScreen) static
Compute offset of screen header title
Definition at line 795 of file d4d_screen.c.
References D4D_GetBmpWidth(), D4D_SCR_TITLE_OFF_X, NULL, D4D_SCREEN_S::pIcon, and D4D_SCREEN_S::radius.
Referenced by D4D_DrawScreenNC().
void D4D_HandleTimeTicks (D4D_SCREEN * pScreen)
Handle the timeticks events of eGUI
Definition at line 1107 of file d4d_screen.c.
References d4d_msg, D4D_MSG_TIMETICK, D4D_OBJECT_F_TIMETICK, D4D_OBJECT_F_VISIBLE, D4D_SendMessageMask(), D4D_SYSTEM_F_TIMETICK, d4d_systemFlags, D4D_MESSAGE_S::nMsgId, NULL, D4D_MESSAGE_S::pObject, D4D_SCREEN_S::pObjects, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_Poll().
void D4D_RedrawScreen (D4D_SCREEN * pScreen)
Redraw the screen based on redraw flags
Definition at line 1058 of file d4d_screen.c.
References D4D_DrawScreenNC(), D4D_LLD_LCD, d4d_msg, D4D_MSG_DRAW, D4D_MSG_DRAWDONE, D4D_RedrawScreenObject(), D4D_SCR_FINT_CHECKOBJECTS, D4D_SCR_FINT_REDRAWC, D4D_SendMessage(), D4D_TRUE, D4DLCD_FLSH_SCR_END, D4DLCD_FLSH_SCR_START, D4DLCD_FUNCTIONS_S::D4DLCD_FlushBuffer, D4D_SCREEN_DATA::flags, D4D_MESSAGE_S::nMsgId, NULL, D4D_SCREEN_S::pData, D4D_MESSAGE_S::pObject, D4D_SCREEN_S::pObjects, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_Poll().
static void D4D_RedrawScreenObject (D4D_OBJECT * pObject, D4D_BOOL complete) static
Redraw all objects that need it on given screen
Definition at line 995 of file d4d_screen.c.
References D4D_MSG_DRAW, D4D_MSG_DRAWDONE, D4D_OBJECT_DRAWFLAGS_CAPTURING, D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_FOCUSED, D4D_OBJECT_DRAWFLAGS_STATE, D4D_OBJECT_F_REDRAW, D4D_OBJECT_F_REDRAWC, D4D_OBJECT_F_REDRAWSTATE, D4D_OBJECT_F_TABSTOP, D4D_OBJECT_F_VISIBLE, D4D_OBJECT_USR_DATA_CHILD_IX, d4d_pKeysCapturer, D4D_SendMessage(), D4D_MESSAGE_S::draw, D4D_OBJECT_DATA_S::flags, D4D_SCREEN_DATA::focusedObject, D4D_MESSAGE_S::nMsgId, D4D_OBJECT_S::pData, D4D_SCREEN_S::pData, D4D_MESSAGE_S::pObject, D4D_OBJECT_S::pRelations, D4D_MESSAGE_S::prm, D4D_OBJECT_DATA_S::pScreen, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_RedrawScreen().
D4D_BOOL D4D_ScrCheckExitBtnCoor (D4D_SCREEN * pScreen, D4D_POINT * point)
Check if the coordination are in range of exit button
Definition at line 1134 of file d4d_screen.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_FALSE, D4D_GetScrHeaderExitBtnCoor(), D4D_TRUE, D4D_POINT::x, and D4D_POINT::y.
Variable Documentation
D4D_MARGIN d4d_screenMarginDflt
Definition at line 59 of file d4d_screen.c.