Freescale's eGUI: d4d_check_box.c File Reference
d4d_check_box.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_CheckBoxOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_CheckBoxGetTextBuffer (D4D_OBJECT *pThis)
static void D4D_CheckBoxValue2Coor (D4D_OBJECT *pThis)
static void D4D_CheckBoxOnDraw (D4D_MESSAGE *pMsg)
static void D4D_CheckBoxOnKeyDown (D4D_MESSAGE *pMsg)
static void D4D_CheckBoxOnKeyUp (D4D_MESSAGE *pMsg)
static void D4D_CheckBoxKillFocus (D4D_MESSAGE *pMsg)
void D4D_CheckBoxSetValue (D4D_OBJECT_PTR pThis, D4D_BOOL value)
Function Sets the the check box value.
D4D_BOOL D4D_CheckBoxGetValue (D4D_OBJECT_PTR pThis)
Function Gets the the check box value.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_checkBoxSysFunc
Detailed Description
D4D driver check box object c file.
Author
Petr Gargulak
Version
0.0.43.0
Date
Oct-14-2013
Definition in file d4d_check_box.c.
Macro Definition Documentation
#define _calc
Definition at line 70 of file d4d_check_box.c.
Referenced by D4D_CheckBoxOnDraw(), and D4D_CheckBoxValue2Coor().
Function Documentation
D4D_STRING * D4D_CheckBoxGetTextBuffer (D4D_OBJECT * pThis)
Get object text buffer
Definition at line 392 of file d4d_check_box.c.
References D4D_GET_CHECKBOX.
static void D4D_CheckBoxKillFocus (D4D_MESSAGE * pMsg) static
Definition at line 246 of file d4d_check_box.c.
References D4D_CHECKBOX_STATUS_PRESSED_MASK, D4D_GET_CHECKBOX_STATUS, and D4D_MESSAGE_S::pObject.
Referenced by D4D_CheckBoxOnMessage().
static void D4D_CheckBoxOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 122 of file d4d_check_box.c.
References _calc, D4D_CLR_SCHEME_OBJ::checkBox, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ALIGN_H_CENTER_MASK, D4D_ALIGN_V_CENTER_MASK, D4D_CHECKBOX_F_ICON_RECTANGLE, D4D_CHECKBOX_STATUS_CHECKED_MASK, D4D_CheckBoxValue2Coor(), D4D_DrawFrame(), D4D_DrawRBmpRect, D4D_DrawTextRect, D4D_FillRRect(), D4D_GET_CHECKBOX, D4D_GET_CHECKBOX_STATUS, D4D_IsEnabled(), D4D_LINE_THICK, D4D_LINE_THIN, D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgColor(), D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetScheme(), D4D_RBox(), D4D_RRect(), D4D_MESSAGE_S::draw, D4D_CLR_SCHEME_CHECKB::iconBckg, D4D_OBJECT_S::initFlags, NULL, D4D_CLR_SCHEME_S::objectDepend, D4D_CHECKBOX::pBmpChecked, D4D_CHECKBOX::pBmpUnChecked, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_CHECKBOX::textBuff, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_CheckBoxOnMessage().
static void D4D_CheckBoxOnKeyDown (D4D_MESSAGE * pMsg) static
Definition at line 197 of file d4d_check_box.c.
References D4D_CHECKBOX_STATUS_PRESSED_MASK, D4D_FALSE, D4D_GET_CHECKBOX_STATUS, D4D_InvalidateObject(), D4D_KEY_SCANCODE_ENTER, D4D_MESSAGE_S::key, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::prm.
Referenced by D4D_CheckBoxOnMessage().
static void D4D_CheckBoxOnKeyUp (D4D_MESSAGE * pMsg) static
Definition at line 215 of file d4d_check_box.c.
References D4D_CHECKBOX_STATUS_CHECKED_MASK, D4D_CHECKBOX_STATUS_PRESSED_MASK, D4D_FALSE, D4D_GET_CHECKBOX, D4D_GET_CHECKBOX_STATUS, D4D_InvalidateObject(), D4D_KEY_SCANCODE_ENTER, D4D_MESSAGE_S::key, D4D_CHECKBOX::OnChange, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::prm.
Referenced by D4D_CheckBoxOnMessage().
void D4D_CheckBoxOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 352 of file d4d_check_box.c.
References D4D_CheckBoxKillFocus(), D4D_CheckBoxOnDraw(), D4D_CheckBoxOnKeyDown(), D4D_CheckBoxOnKeyUp(), D4D_GetMouseHoverObject, D4D_MSG_DRAW, D4D_MSG_KEYDOWN, D4D_MSG_KEYUP, D4D_MSG_KILLFOCUS, D4D_MSG_MOUSE_BTN_LEFT_UP, D4D_MSG_TOUCHED, D4D_ObjOnMessage(), D4D_MESSAGE_S::nMsgId, and D4D_MESSAGE_S::pObject.
static void D4D_CheckBoxValue2Coor (D4D_OBJECT * pThis) static
Definition at line 74 of file d4d_check_box.c.
References _calc, D4D_SIZE::cx, D4D_SIZE::cy, D4D_CHECKBOX_TEXT_OFFSET, D4D_ComputeGeometry(), D4D_GET_CHECKBOX, D4D_GetBmpSize(), D4D_GetClientToScreenPoint(), D4D_CHECKBOX::pBmpChecked, D4D_OBJECT_S::position, D4D_STRING_S::pText, D4D_OBJECT_S::radius, and D4D_CHECKBOX::textBuff.
Referenced by D4D_CheckBoxOnDraw().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_checkBoxSysFunc
Definition at line 53 of file d4d_check_box.c.