Freescale's eGUI: d4d_graph.c File Reference
d4d_graph.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_GraphOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_GraphGetTextBuffer (D4D_OBJECT *pThis)
static void D4D_GraphUpdateTempPosX (D4D_OBJECT *pThis)
static void D4D_GraphValue2Coor (D4D_OBJECT *pThis)
static D4D_COOR D4D_GraphGetSizeLblY (D4D_OBJECT *pThis)
static D4D_COOR D4D_GraphGetGridCoorX (D4D_OBJECT *pThis, Byte gridIx)
static D4D_COOR D4D_GraphGetGridCoorY (D4D_OBJECT *pThis, Byte gridIx)
static void D4D_GraphPrintLabel (D4D_OBJECT *pThis, D4D_BOOL axisX, Byte gridIx, D4D_GRAPH_SAMPLE_IX sampleIx)
static void D4D_GraphDrawEmptyGraph (D4D_OBJECT *pThis)
static void D4D_GraphOnDraw (D4D_MESSAGE *pMsg)
D4D_BOOL D4D_GraphAddTraceData (D4D_OBJECT_PTR pObj, D4D_INDEX trace_ix, D4D_GRAPH_VALUE value)
The function add new data to one trace.
void D4D_GraphAddTracesData (D4D_OBJECT_PTR pObj, D4D_GRAPH_VALUE *pValues)
The function add new data to all traces.
void D4D_GraphClearAll (D4D_OBJECT_PTR pObj)
The function clears all internal data of graph object.
LWord D4D_GraphGetSampleIndex (D4D_OBJECT_PTR pObj)
The function returns the current data sample index.
D4D_COOR D4D_GraphGetSizeX (D4D_OBJECT_PTR pObj)
The function returns the size of graph traces in axis X.
D4D_BOOL D4D_GraphSetScaleX (D4D_OBJECT_PTR pObj, Byte mul, Byte div)
Function sets the new scale of axis X of the graph.
D4D_BOOL D4D_GraphSetDataWidth (D4D_OBJECT_PTR pObj, D4D_INDEX samples)
Function sets the new scale of the axis X of the graph.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_graphSysFunc
Detailed Description
D4D driver graph object c file.
Author
Petr Gargulak
Version
0.0.36.0
Date
Jan-14-2014
Definition in file d4d_graph.c.
Macro Definition Documentation
#define _calc
Definition at line 74 of file d4d_graph.c.
Referenced by D4D_GraphDrawEmptyGraph(), D4D_GraphGetGridCoorX(), D4D_GraphGetGridCoorY(), D4D_GraphGetSizeX(), D4D_GraphOnDraw(), D4D_GraphOnMessage(), D4D_GraphPrintLabel(), D4D_GraphSetScaleX(), D4D_GraphUpdateTempPosX(), and D4D_GraphValue2Coor().
Function Documentation
static void D4D_GraphDrawEmptyGraph (D4D_OBJECT * pThis) static
Definition at line 262 of file d4d_graph.c.
References _calc, D4D_BoxXY(), D4D_FALSE, D4D_GET_GRAPH, D4D_GetGreyScale(), D4D_GraphGetGridCoorX(), D4D_GraphGetGridCoorY(), D4D_GraphPrintLabel(), D4D_IsEnabled(), D4D_LINE_THIN, D4D_LineToXY(), D4D_MoveToXY(), D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeFillColor(), D4D_ObjectGetScheme(), D4D_TRUE, D4D_GRAPH_DATA::dataShowX, D4D_CLR_SCHEME_OBJ::graph, D4D_GRAPH::grid, D4D_CLR_SCHEME_GRAPH::grid, D4D_CLR_SCHEME_S::objectDepend, D4D_GRAPH::pData, D4D_GRAPH_GRID::x_cnt, D4D_GRAPH_DATA::xPosCnt, and D4D_GRAPH_GRID::y_cnt.
Referenced by D4D_GraphOnDraw().
static D4D_COOR D4D_GraphGetGridCoorX (D4D_OBJECT * pThis, Byte gridIx) static
Definition at line 183 of file d4d_graph.c.
References _calc, D4D_GET_GRAPH, D4D_MulDivUU16(), D4D_GRAPH::grid, and D4D_GRAPH_GRID::x_cnt.
Referenced by D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), and D4D_GraphPrintLabel().
static D4D_COOR D4D_GraphGetGridCoorY (D4D_OBJECT * pThis, Byte gridIx) static
Definition at line 189 of file d4d_graph.c.
References _calc, D4D_GET_GRAPH, D4D_MulDivUU16(), D4D_GRAPH::grid, and D4D_GRAPH_GRID::y_cnt.
Referenced by D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), and D4D_GraphPrintLabel().
static D4D_COOR D4D_GraphGetSizeLblY (D4D_OBJECT * pThis) static
Definition at line 161 of file d4d_graph.c.
References D4D_FALSE, D4D_GET_GRAPH, D4D_GetFontWidth(), D4D_GetTextLength(), D4D_GRAPH::grid, D4D_GRAPH::labelFont, NULL, D4D_GRAPH::OnNeedLabelText, and D4D_GRAPH_GRID::y_cnt.
Referenced by D4D_GraphOnDraw(), and D4D_GraphOnMessage().
D4D_STRING * D4D_GraphGetTextBuffer (D4D_OBJECT * pThis)
Get object text buffer
Definition at line 840 of file d4d_graph.c.
References D4D_GET_GRAPH.
static void D4D_GraphOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 312 of file d4d_graph.c.
References _calc, D4D_GRAPH_TRACE::color, D4D_GRAPH_DATA::columnDrawed, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ASSERT, D4D_DrawFrame(), D4D_DrawTextRect, D4D_FillRectTo(), D4D_FillRectToXY(), D4D_FillRRect(), D4D_GET_GRAPH, D4D_GetFontHeight(), D4D_GetGreyScale(), D4D_GRAPH_F_MODE_MASK, D4D_GRAPH_F_MODE_NORMAL, D4D_GRAPH_F_MODE_ROLLOVER, D4D_GRAPH_F_VALUE_Y_LEFT, D4D_GRAPH_F_VALUE_Y_RIGHT, D4D_GRAPH_TRACE_TYPE_AREA, D4D_GRAPH_TRACE_TYPE_AREA_INV, D4D_GRAPH_TRACE_TYPE_DOT, D4D_GRAPH_TRACE_TYPE_LINE, D4D_GRAPH_TRACE_TYPE_MASK, D4D_GraphDrawEmptyGraph(), D4D_GraphGetGridCoorX(), D4D_GraphGetGridCoorY(), D4D_GraphGetSizeLblY(), D4D_GraphPrintLabel(), D4D_GraphUpdateTempPosX(), D4D_GraphValue2Coor(), D4D_IsEnabled(), D4D_LINE_THIN, D4D_LineTo(), D4D_MoveTo(), D4D_MoveToXY(), D4D_MulDivUU, D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetForeFillColor(), D4D_ObjectGetScheme(), D4D_SCRATCHPAD_SIZE, D4D_TRUE, D4D_GRAPH::dataLenght, D4D_GRAPH_DATA::dataShowX, D4D_MESSAGE_S::draw, D4D_GRAPH_DATA::drigDrawedX, D4D_STRING_S::fontId, D4D_CLR_SCHEME_OBJ::graph, D4D_GRAPH::grid, D4D_CLR_SCHEME_GRAPH::grid, D4D_GRAPH_DATA::initData, D4D_OBJECT_S::initFlags, D4D_GRAPH_DATA::lastDataPos, D4D_GRAPH_DATA::lastShowPos, D4D_GRAPH_DATA::lblSizeY, D4D_GRAPH_TRACE::line, NULL, D4D_CLR_SCHEME_S::objectDepend, D4D_GRAPH_TRACE::pData, D4D_GRAPH::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_GRAPH::textBuff, D4D_GRAPH::traces, D4D_GRAPH_TRACE::type, D4D_POINT::x, D4D_GRAPH_GRID::x_cnt, D4D_GRAPH_DATA::xPosCnt, D4D_POINT::y, and D4D_GRAPH_GRID::y_cnt.
Referenced by D4D_GraphOnMessage().
void D4D_GraphOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 800 of file d4d_graph.c.
References _calc, D4D_FocusSet(), D4D_GET_GRAPH, D4D_GRAPH_F_VALUE_Y_LEFT, D4D_GRAPH_F_VALUE_Y_RIGHT, D4D_GraphGetSizeLblY(), D4D_GraphOnDraw(), D4D_GraphValue2Coor(), D4D_MSG_DRAW, D4D_MSG_ONINIT, D4D_MSG_TOUCHED, D4D_OBJECT_F_NOTINIT, D4D_ObjOnMessage(), D4D_OBJECT_DATA_S::flags, D4D_OBJECT_S::initFlags, D4D_MESSAGE_S::nMsgId, D4D_OBJECT_S::pData, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::pScreen.
static void D4D_GraphPrintLabel (D4D_OBJECT * pThis, D4D_BOOL axisX, Byte gridIx, D4D_GRAPH_SAMPLE_IX sampleIx) static
Definition at line 196 of file d4d_graph.c.
References _calc, D4D_STRING_S::buffSize, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ALIGN_H_CENTER_MASK, D4D_DrawTextRect, D4D_GET_GRAPH, D4D_GetFontHeight(), D4D_GetTextLength(), D4D_GRAPH_LBL_FNT_PRTY_DEFAULT, D4D_GraphGetGridCoorX(), D4D_GraphGetGridCoorY(), D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeFillColor(), D4D_SprintDecU16(), D4D_SprintDecU8(), D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, D4D_GRAPH::grid, D4D_GRAPH::labelFont, D4D_GRAPH_DATA::lblSizeY, NULL, D4D_GRAPH::OnNeedLabelText, D4D_GRAPH::pData, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_STRING_S::pText, D4D_STRING_S::str_properties, D4D_STR_PROPERTIES_S::text_properties, D4D_POINT::x, D4D_GRAPH_GRID::x_cnt, D4D_POINT::y, and D4D_GRAPH_GRID::y_cnt.
Referenced by D4D_GraphDrawEmptyGraph(), and D4D_GraphOnDraw().
static void D4D_GraphUpdateTempPosX (D4D_OBJECT * pThis) static
Definition at line 76 of file d4d_graph.c.
References _calc, D4D_GET_GRAPH, D4D_MulDivUU16(), D4D_GRAPH_DATA::dataShowX, D4D_GRAPH::pData, and D4D_GRAPH_DATA::xPosCnt.
Referenced by D4D_GraphOnDraw().
static void D4D_GraphValue2Coor (D4D_OBJECT * pThis) static
Definition at line 89 of file d4d_graph.c.
References _calc, D4D_ComputeGeometry(), D4D_GET_GRAPH, D4D_GetClientToScreenPoint(), D4D_GetFont(), D4D_GetFontHeight(), D4D_GRAPH_BORDER_OFF, D4D_GRAPH_F_VALUE_X_BOTT, D4D_GRAPH_F_VALUE_X_TOP, D4D_GRAPH_F_VALUE_Y_LEFT, D4D_GRAPH_F_VALUE_Y_RIGHT, D4D_GRAPH_VALUE_OFF, D4D_STRING_S::fontId, D4D_OBJECT_S::initFlags, D4D_GRAPH::labelFont, D4D_GRAPH_DATA::lblSizeY, NULL, D4D_GRAPH_TRACE::pData, D4D_GRAPH::pData, D4D_OBJECT_S::position, D4D_STRING_S::pText, D4D_OBJECT_S::radius, D4D_GRAPH::textBuff, and D4D_GRAPH::traces.
Referenced by D4D_GraphGetSizeX(), D4D_GraphOnDraw(), D4D_GraphOnMessage(), and D4D_GraphSetScaleX().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_graphSysFunc
Definition at line 53 of file d4d_graph.c.