Freescale's eGUI: d4d_math.c File Reference
d4d_math.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Functions
static Byte D4D_Divide8 (Word num, Byte div)
Fast 16/8=8 divide operation with rounding and saturation.
static Word D4D_Divide16 (LWord num, Word div)
Byte D4D_MulDivUU8 (Byte u1, Byte u2, Byte d)
Simple proportion unsigned calculation - 8 bit.
sByte D4D_MulDivSU8 (sByte s, Byte u, Byte d)
Simple proportion signed calculation - 8 bit.
Word D4D_MulDivUU16 (Word u1, Word u2, Word d)
Simple proportion unsigned calculation - 16 bit.
sWord D4D_MulDivSU16 (sWord s, Word u, Word d)
Simple proportion signed calculation - 8 bit.
Byte D4D_Abs (sByte num)
Calculation of absolute value - 8 bit.
Word D4D_Abs16 (sWord num)
Calculation of absolute value - 16 bit.
LWord D4D_Abs32 (sLWord num)
Calculation of absolute value - 32 bit.
Word D4D_LimitU16 (Word val, Word min, Word max)
Calculation of limitation value (unsigned) - 16 bit.
sWord D4D_LimitS16 (sWord val, sWord min, sWord max)
Calculation of limitation value (signed) - 16 bit.
Byte D4D_LimitU8 (Byte val, Byte min, Byte max)
Calculation of limitation value (unsigned) - 8 bit.
sByte D4D_LimitS8 (sByte val, sByte min, sByte max)
Calculation of limitation value (signed) - 8 bit.
sByte D4D_Sin (Byte x)
Sine calculation using lookup table.
sByte D4D_Cos (Byte x)
Cosine calculation using lookup table.
Variables
const sByte d4d_sinTbl [64]
Detailed Description
D4D driver math functions c file.
Author
Michal hanak, Petr Gargulak
Version
0.0.28.0
Date
Oct-2-2013
Definition in file d4d_math.c.
Function Documentation
static Word D4D_Divide16 (LWord num, Word div) static
Definition at line 181 of file d4d_math.c.
Referenced by D4D_MulDivSU16(), and D4D_MulDivUU16().
static Byte D4D_Divide8 (Word num, Byte div) static
Fast 16/8=8 divide operation with rounding and saturation.
Parameters
num The 16-bit numerator to be divided
div The 8-bit denominator
This function divides a given 16-bit value by a 8-bit divisor and returns 8-bit quotient. Half of the divisor is added to divident before the division so the result is rounded.
Returns
This function returns the 8-bit quotient. Returned value is 255 when overflow occurs.
Definition at line 138 of file d4d_math.c.
References D4D_UNUSED.
Referenced by D4D_MulDivSU8(), and D4D_MulDivUU8().
Variable Documentation
const sByte d4d_sinTbl[64]
Definition at line 49 of file d4d_math.c.
Referenced by D4D_Cos(), and D4D_Sin().