Freescale's eGUI: d4d_font.h File Reference
d4d_font.h File Reference
Macros
#define D4D_FNT_EXTSRC_SUPPORT
This macro is used to enable external fonts resource support. If not defined, the external font resource support is disabled as a default.
#define D4D_FNT_PRTY_UNDERLINE_MASK
Font Underline property masks.
#define D4D_FNT_PRTY_UNDERLINE_NONE_MASK
None Underline Text Property mask.
#define D4D_FNT_PRTY_UNDERLINE_LINE_MASK
One Line Underline Text Property mask.
#define D4D_FNT_PRTY_UNDERLINE_DOT_MASK
Dot Line Underline Text Property mask.
#define D4D_FNT_PRTY_UNDERLINE_RES_MASK
Reserved - Underline Text Property mask.
#define D4D_FNT_PRTY_STRIKETHROUGH_MASK
Font Strike through property masks.
#define D4D_FNT_PRTY_STRIKETHROUGH_NONE_MASK
None Strike Through Text Property mask.
#define D4D_FNT_PRTY_STRIKETHROUGH_SINGLE_MASK
One Line Strike Through Text Property mask.
#define D4D_FNT_PRTY_STRIKETHROUGH_DOUBLE_MASK
Two Lines Strike Through Text Property mask.
#define D4D_FNT_PRTY_STRIKETHROUGH_TRIPLE_MASK
Three Lines Strike Through Text Property mask.
#define D4D_FNT_PRTY_STRIKETHROUGH_SHIFT
Strike through property bits shift.
#define D4D_FNT_PRTY_TRANSPARENT_MASK
#define D4D_FNT_PRTY_TRANSPARENT_NO_MASK
#define D4D_FNT_PRTY_TRANSPARENT_YES_MASK
#define D4D_FONT_PACK_BITORDER
#define D4D_FONT_PACK_BITORDER_BIGEND
#define D4D_FONT_PACK_BITORDER_LITTLEEND
#define D4D_FONT_PACK_SCANBASED
#define D4D_FONT_PACK_SCANBASED_ROW
#define D4D_FONT_PACK_SCANBASED_COLUMN
#define D4D_FONT_PACK_SCANPREFERRED
#define D4D_FONT_PACK_SCANPREFERRED_ROW
#define D4D_FONT_PACK_SCANPREFERRED_COLUMN
#define D4D_FONT_PACK_COMPRESSED
#define D4D_FONT_PACK_COMPRESSED_OFF
#define D4D_FONT_PACK_COMPRESSED_ON
#define D4D_FONT_PACK_DATA_LEN
#define D4D_FONT_PACK_DATA_LEN_8B
#define D4D_FONT_PACK_DATA_LEN_16B
#define D4D_FONT_PACK_DATA_LEN_32B
#define D4D_FONT_FLAGS_IX_STYLE
#define D4D_FONT_FLAGS_IX_STYLE_LINEAR
#define D4D_FONT_FLAGS_IX_STYLE_NONLINEAR
#define D4D_FONT_FLAGS_IX_TYPE
#define D4D_FONT_FLAGS_IX_TYPE_LOOKUP
#define D4D_FONT_FLAGS_IX_TYPE_MAP
#define D4D_FONT_FLAGS_FNT_WIDTH
#define D4D_FONT_FLAGS_FNT_WIDTH_MONOSPACE
#define D4D_FONT_FLAGS_FNT_WIDTH_PROPORTIONAL
#define D4D_DECLARE_USR_FONT_TABLE_BEGIN(name)
#define D4D_DECLARE_FONT_TABLE_BEGIN
#define D4D_DECLARE_FONT(fontId, font_descriptor, xScale, yScale, charSpace, lineSpace)
#define D4D_DECLARE_FONT_FILE(fontId, fileName, xScale, yScale, charSpace, lineSpace)
#define D4D_DECLARE_FONT_TABLE_END
Typedefs
typedef Byte D4D_FONT_PROPERTIES
typedef Byte D4D_FONT_PACK
typedef Byte D4D_FONT_FLAGS
typedef Byte D4D_FONT_IX
typedef Byte D4D_FONT_REV
typedef Word D4D_FONT_OFFSET
typedef Byte D4D_FONT_DATA
typedef Byte D4D_FONT
typedef Byte D4D_FONT_SIZE
typedef Word D4D_FONT_DSIZE
typedef struct
D4D_FONT_DESCRIPTOR_S D4D_FONT_DESCRIPTOR
Functions
void D4D_SetFontTable (D4D_FONT_TYPE *pFontTable)
D4D_FONT_TYPE * D4D_GetFontTable (void)
D4D_FONT_TYPE * D4D_GetFont (D4D_FONT ix)
D4D_FONT_SIZES D4D_GetFontSize (D4D_FONT ix)
D4D_FONT_SIZE D4D_GetFontHeight (D4D_FONT ix)
D4D_FONT_SIZE D4D_GetFontWidth (D4D_FONT ix)
D4D_FONT_SIZE D4D_GetCharWidth (D4D_FONT ix, D4D_TCHAR ch)
D4D_TCHAR D4D_GetChar (D4D_FONT_TYPE *pFontType, D4D_FONT_IX ix)
D4D_COOR D4D_GetNextTab (D4D_TAB *pTab, D4D_COOR pos)
Variables
const D4D_FONT_TYPE d4d_FontTable []
Detailed Description
D4D Driver fonts header file.
Author
Petr Gargulak
Version
0.0.35.0
Date
Oct-2-2013
Definition in file d4d_font.h.
Macro Definition Documentation
#define D4D_DECLARE_FONT (fontId, font_descriptor, xScale, yScale, charSpace, lineSpace)
Definition at line 240 of file d4d_font.h.
#define D4D_DECLARE_FONT_FILE (fontId, fileName, xScale, yScale, charSpace, lineSpace)
Definition at line 243 of file d4d_font.h.
#define D4D_DECLARE_FONT_TABLE_BEGIN
Definition at line 236 of file d4d_font.h.
#define D4D_DECLARE_FONT_TABLE_END
Definition at line 247 of file d4d_font.h.
#define D4D_DECLARE_USR_FONT_TABLE_BEGIN (name)
Definition at line 234 of file d4d_font.h.
#define D4D_FONT_FLAGS_FNT_WIDTH
Definition at line 152 of file d4d_font.h.
#define D4D_FONT_FLAGS_FNT_WIDTH_MONOSPACE
Definition at line 153 of file d4d_font.h.
#define D4D_FONT_FLAGS_FNT_WIDTH_PROPORTIONAL
Definition at line 154 of file d4d_font.h.
Referenced by D4D_ConsoleOnDraw(), D4D_GetCharData(), D4D_GetCharWidth(), and D4D_LCD_PrintChr().
#define D4D_FONT_FLAGS_IX_STYLE
Definition at line 144 of file d4d_font.h.
#define D4D_FONT_FLAGS_IX_STYLE_LINEAR
Definition at line 145 of file d4d_font.h.
#define D4D_FONT_FLAGS_IX_STYLE_NONLINEAR
Definition at line 146 of file d4d_font.h.
Referenced by D4D_GetCharIndex().
#define D4D_FONT_FLAGS_IX_TYPE
Definition at line 148 of file d4d_font.h.
#define D4D_FONT_FLAGS_IX_TYPE_LOOKUP
Definition at line 149 of file d4d_font.h.
#define D4D_FONT_FLAGS_IX_TYPE_MAP
Definition at line 150 of file d4d_font.h.
Referenced by D4D_GetCharIndex().
#define D4D_FONT_PACK_BITORDER
Definition at line 123 of file d4d_font.h.
#define D4D_FONT_PACK_BITORDER_BIGEND
Definition at line 124 of file d4d_font.h.
#define D4D_FONT_PACK_BITORDER_LITTLEEND
Definition at line 125 of file d4d_font.h.
Referenced by D4D_LCD_GetFntBit().
#define D4D_FONT_PACK_COMPRESSED
Definition at line 135 of file d4d_font.h.
#define D4D_FONT_PACK_COMPRESSED_OFF
Definition at line 136 of file d4d_font.h.
#define D4D_FONT_PACK_COMPRESSED_ON
Definition at line 137 of file d4d_font.h.
Referenced by D4D_LCD_GetFntBit().
#define D4D_FONT_PACK_DATA_LEN
Definition at line 139 of file d4d_font.h.
#define D4D_FONT_PACK_DATA_LEN_16B
Definition at line 141 of file d4d_font.h.
#define D4D_FONT_PACK_DATA_LEN_32B
Definition at line 142 of file d4d_font.h.
#define D4D_FONT_PACK_DATA_LEN_8B
Definition at line 140 of file d4d_font.h.
#define D4D_FONT_PACK_SCANBASED
Definition at line 127 of file d4d_font.h.
#define D4D_FONT_PACK_SCANBASED_COLUMN
Definition at line 129 of file d4d_font.h.
Referenced by D4D_LCD_GetFntBit().
#define D4D_FONT_PACK_SCANBASED_ROW
Definition at line 128 of file d4d_font.h.
#define D4D_FONT_PACK_SCANPREFERRED
Definition at line 131 of file d4d_font.h.
#define D4D_FONT_PACK_SCANPREFERRED_COLUMN
Definition at line 133 of file d4d_font.h.
Referenced by D4D_LCD_GetFntBit().
#define D4D_FONT_PACK_SCANPREFERRED_ROW
Definition at line 132 of file d4d_font.h.
Typedef Documentation
typedef Byte D4D_FONT
Definition at line 171 of file d4d_font.h.
typedef Byte D4D_FONT_DATA
Definition at line 170 of file d4d_font.h.
typedef struct D4D_FONT_DESCRIPTOR_S D4D_FONT_DESCRIPTOR
typedef Word D4D_FONT_DSIZE
Definition at line 175 of file d4d_font.h.
typedef Byte D4D_FONT_FLAGS
Definition at line 159 of file d4d_font.h.
typedef Byte D4D_FONT_IX
Definition at line 165 of file d4d_font.h.
typedef Word D4D_FONT_OFFSET
Definition at line 169 of file d4d_font.h.
typedef Byte D4D_FONT_PACK
Definition at line 158 of file d4d_font.h.
typedef Byte D4D_FONT_REV
Definition at line 166 of file d4d_font.h.
typedef Byte D4D_FONT_SIZE
Definition at line 174 of file d4d_font.h.
Function Documentation
D4D_TCHAR D4D_GetChar (D4D_FONT_TYPE * pFontType, D4D_FONT_IX ix)
D4D_FONT_SIZE D4D_GetCharWidth (D4D_FONT ix, D4D_TCHAR ch)
Get selected font width information
Definition at line 415 of file d4d_font.c.
References D4D_FONT_TYPE::charSpacing, D4D_FONT_FLAGS_FNT_WIDTH_PROPORTIONAL, D4D_GetFont(), D4D_LCD_GetCharPlace(), NULL, D4D_FONT_TYPE::pFontDescriptor, D4D_FONT_TYPE::scale, and D4D_FONT_SIZES::width.
Referenced by D4D_CnslFindMaxTextLenght(), D4D_ConsoleOnDraw(), D4D_EditBoxOnDraw(), D4D_EditBoxSetCursor(), D4D_GetTextBuffWidthTab(), D4D_GetTextMaxLength(), D4D_GetTextWidth(), D4D_LCD_PrintChr(), D4D_LCD_PrintStr(), D4D_TextBoxGetCharsToLine(), and D4D_TextBoxGetWordSpecInt().
D4D_FONT_TYPE* D4D_GetFont (D4D_FONT ix)
Get selected font information
Definition at line 340 of file d4d_font.c.
References D4D_UNUSED, and NULL.
Referenced by D4D_ConsoleOnDraw(), D4D_DrawTextRectTab(), D4D_DrawTextRRectTab(), D4D_DrawTextTabXY(), D4D_GetCharWidth(), D4D_GetFontHeight(), D4D_GetFontWidth(), and D4D_GraphValue2Coor().
D4D_FONT_SIZE D4D_GetFontHeight (D4D_FONT ix)
Get selected font height information
Definition at line 381 of file d4d_font.c.
References D4D_FONT_DESCRIPTOR_S::charFullSize, D4D_FONT_TYPE::charSpacing, D4D_GetFont(), D4D_FONT_SIZES::height, NULL, D4D_FONT_TYPE::pFontDescriptor, and D4D_FONT_TYPE::scale.
Referenced by D4D_CnslValue2Coor(), D4D_ConsoleOnDraw(), D4D_DrawScreenNC(), D4D_DrawTextRectTab(), D4D_DrawTextRRectTab(), D4D_EditBoxOnDraw(), D4D_GaugOnDraw(), D4D_GetFontSize(), D4D_GetPositionCount(), D4D_GetScrHeaderSize(), D4D_GetTitleBarHeight(), D4D_GraphOnDraw(), D4D_GraphPrintLabel(), D4D_GraphValue2Coor(), D4D_IconOnDraw(), D4D_LCD_PrintChr(), D4D_LCD_PrintStr(), D4D_MenuOnDraw(), D4D_MenuValue2Coor(), D4D_SldrOnDraw(), D4D_TextBoxOnDraw(), and D4D_TextBoxValue2Coor().
D4D_FONT_SIZES D4D_GetFontSize (D4D_FONT ix)
Get selected font size information
Definition at line 365 of file d4d_font.c.
References D4D_GetFontHeight(), D4D_GetFontWidth(), D4D_FONT_SIZES::height, and D4D_FONT_SIZES::width.
D4D_FONT_TYPE* D4D_GetFontTable (void)
Definition at line 330 of file d4d_font.c.
References d4d_pFontTable.
D4D_FONT_SIZE D4D_GetFontWidth (D4D_FONT ix)
Get selected font width information
Definition at line 398 of file d4d_font.c.
References D4D_FONT_DESCRIPTOR_S::charFullSize, D4D_FONT_TYPE::charSpacing, D4D_GetFont(), NULL, D4D_FONT_TYPE::pFontDescriptor, D4D_FONT_TYPE::scale, and D4D_FONT_SIZES::width.
Referenced by D4D_CnslValue2Coor(), D4D_GetFontSize(), D4D_GraphGetSizeLblY(), and D4D_MenuOnDraw().
D4D_COOR D4D_GetNextTab (D4D_TAB * pTab, D4D_COOR pos)
Definition at line 618 of file d4d_font.c.
References NULL, D4D_TAB::pTabTable, and D4D_TAB::tabOffset.
Referenced by D4D_GetTextBuffWidthTab(), D4D_LCD_PrintChr(), and D4D_TextBoxGetWordSpecInt().
void D4D_SetFontTable (D4D_FONT_TYPE * pFontTable)
Change the Font Table
Definition at line 314 of file d4d_font.c.
References d4d_FontTable, and NULL.
Variable Documentation
const D4D_FONT_TYPE d4d_FontTable[]
Referenced by D4D_SetFontTable().