Freescale's eGUI: d4d_imgdec_bmp.h File Reference
d4d_imgdec_bmp.h File Reference
Macros
#define D4D_BITMAP_SIGNATURE
#define D4D_BITMAPHEADER_SIZE
#define D4D_BITMAPINFOHEADER_SIZE
#define D4D_TMP_PBITMAPHEADER
#define D4D_TMP_PBITMAPINFOHEADER
Typedefs
typedef struct D4D_RGBA_S D4D_RGBA
typedef struct D4D_BGRA_S D4D_BGRA
typedef union D4D_LONG_S D4D_LONG
Enumerations
enum D4D_BITMAPCOMPRESSION { D4D_BC_RGB, D4D_BC_RLE8, D4D_BC_RLE4, D4D_BC_BITFIELDS, D4D_BC_JPEG, D4D_BC_PNG }
Functions
void D4D_ImgDecBmpDraw (D4D_COOR x, D4D_COOR y, D4D_CHAR *pFileName, D4D_BOOL greyScale, D4D_COOR radius)
D4D_COOR D4D_ImgDecBmpGetWidth (D4D_CHAR *pFileName)
D4D_COOR D4D_ImgDecBmpGetHeight (D4D_CHAR *pFileName)
D4D_SIZE D4D_ImgDecBmpGetSize (D4D_CHAR *pFileName)
int D4D_ImgDecBmpGetHeader (D4D_CHAR *pFileName, void *pBuff, int max_size)
D4D_BOOL D4D_PrintScreenToBMP (D4D_CHAR *pFileName)
The function convert screen into BMP file.
Detailed Description
D4D driver external bmp files decoder header file.
Author
Petr Gargulak
Version
0.0.8.0
Date
Oct-2-2013
Definition in file d4d_imgdec_bmp.h.
Macro Definition Documentation
#define D4D_BITMAP_SIGNATURE
Definition at line 134 of file d4d_imgdec_bmp.h.
Referenced by D4D_ImgDecBmpDraw(), and D4D_ImgDecBmpGetHeader().
#define D4D_BITMAPHEADER_SIZE
Definition at line 139 of file d4d_imgdec_bmp.h.
Referenced by D4D_ImgDecBmpDraw(), and D4D_ImgDecBmpGetHeader().
#define D4D_BITMAPINFOHEADER_SIZE
Definition at line 141 of file d4d_imgdec_bmp.h.
Referenced by D4D_ImgDecBmpDraw(), D4D_ImgDecBmpGetHeader(), and D4D_ImgDecBmpGetSize().
#define D4D_TMP_PBITMAPHEADER
Definition at line 143 of file d4d_imgdec_bmp.h.
Referenced by D4D_ImgDecBmpDraw(), and D4D_ImgDecBmpGetHeader().
#define D4D_TMP_PBITMAPINFOHEADER
Definition at line 145 of file d4d_imgdec_bmp.h.
Typedef Documentation
typedef struct D4D_BGRA_S D4D_BGRA
typedef union D4D_LONG_S D4D_LONG
typedef struct D4D_RGBA_S D4D_RGBA
Enumeration Type Documentation
enum D4D_BITMAPCOMPRESSION
Enumerator
D4D_BC_RGB
D4D_BC_RLE8
D4D_BC_RLE4
D4D_BC_BITFIELDS
D4D_BC_JPEG
D4D_BC_PNG
Definition at line 88 of file d4d_imgdec_bmp.h.
Function Documentation
void D4D_ImgDecBmpDraw (D4D_COOR x, D4D_COOR y, D4D_CHAR * pFileName, D4D_BOOL greyScale, D4D_COOR radius)
Draw BMP image file
Definition at line 67 of file d4d_imgdec_bmp.c.
References D4D_BITMAPINFOHEADER::bitspp, D4D_BGRA_S::Blue, D4D_BITMAPINFOHEADER::bmpBytesz, D4D_LONG_S::Bytes, COLOR, COLOR_IX, D4D_LONG_S::complete, D4D_BITMAPINFOHEADER::compressType, COUNTER, D4D_ASSERT, D4D_BC_BITFIELDS, D4D_BC_JPEG, D4D_BC_PNG, D4D_BC_RGB, D4D_BC_RLE4, D4D_BC_RLE8, D4D_BITMAP_SIGNATURE, D4D_BITMAPHEADER_SIZE, D4D_BITMAPINFOHEADER_SIZE, D4D_BoxXY(), D4D_COLOR_RGB, D4D_COLOR_RGB555_GET_B, D4D_COLOR_RGB555_GET_G, D4D_COLOR_RGB555_GET_R, D4D_EXTSRC_BUFF_SIZE, d4d_extsrcBuffer, D4D_FALSE, D4D_FileClose, D4D_FileRead, D4D_FileSeek, D4D_GetActiveScreen(), D4D_LCD_PutPixel(), D4D_LINE_THIN, D4D_LLD_LCD, D4D_MemAlloc, D4D_MemFree, D4D_PrintPixel(), D4D_RBoxXY(), D4D_READ16L, D4D_READ32L, D4D_RndCornerGetNonPrintedPxl(), D4D_ScreenGetScheme(), D4D_SEEK_CUR, D4D_SEEK_SET, D4D_TMP_PBITMAPHEADER, D4D_TRUE, D4DLCD_FLSH_ELEMENT, D4DLCD_FUNCTIONS_S::D4DLCD_FlushBuffer, D4DLCD_FUNCTIONS_S::D4DLCD_Send_PixelColor, D4DLCD_FUNCTIONS_S::D4DLCD_SetWindow, D4D_BGRA_S::Green, D4D_BITMAPINFOHEADER::headerSz, D4D_BITMAPINFOHEADER::height, D4D_BITMAPINFOHEADER::hres, D4D_LONG_S::ll, D4D_LONG_S::low, D4D_BITMAPINFOHEADER::ncolors, D4D_BITMAPINFOHEADER::nimpcolors, D4D_BITMAPINFOHEADER::nplanes, NULL, OFFSET_X, OFFSET_Y, D4D_BGRA_S::Red, D4D_BITMAPINFOHEADER::vres, D4D_BITMAPINFOHEADER::width, and D4D_LONG_S::Words.
int D4D_ImgDecBmpGetHeader (D4D_CHAR * pFileName, void * pBuff, int max_size)
Get header - BMP image file
Definition at line 783 of file d4d_imgdec_bmp.c.
References D4D_ASSERT, D4D_BITMAP_SIGNATURE, D4D_BITMAPHEADER_SIZE, D4D_BITMAPINFOHEADER_SIZE, D4D_EXTSRC_BUFF_SIZE, d4d_extsrcBuffer, D4D_FileClose, D4D_FileRead, D4D_READ16L, D4D_READ32L, D4D_TMP_PBITMAPHEADER, and NULL.
Referenced by D4D_ImgDecBmpGetSize().
D4D_COOR D4D_ImgDecBmpGetHeight (D4D_CHAR * pFileName)
Get height - BMP image file
Definition at line 741 of file d4d_imgdec_bmp.c.
References D4D_SIZE::cy, and D4D_ImgDecBmpGetSize().
D4D_SIZE D4D_ImgDecBmpGetSize (D4D_CHAR * pFileName)
Get size - BMP image file
Definition at line 754 of file d4d_imgdec_bmp.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_BITMAPINFOHEADER_SIZE, D4D_ImgDecBmpGetHeader(), d4d_size_zero, D4D_BITMAPINFOHEADER::height, and D4D_BITMAPINFOHEADER::width.
Referenced by D4D_ImgDecBmpGetHeight(), and D4D_ImgDecBmpGetWidth().
D4D_COOR D4D_ImgDecBmpGetWidth (D4D_CHAR * pFileName)
Get width - BMP image file
Definition at line 729 of file d4d_imgdec_bmp.c.
References D4D_SIZE::cx, and D4D_ImgDecBmpGetSize().
D4D_BOOL D4D_PrintScreenToBMP (D4D_CHAR * pFileName)
The function convert screen into BMP file.
Parameters
pFileName - pointer file name string
Returns
D4D_TRUE - The BMP file has been saved, D4D_FALSE - error in creating BMP file
Note
The eGUI external buffer size MUST be >= 64
Definition at line 862 of file d4d_imgdec_bmp.c.
References D4D_COLOR_GET_B, D4D_COLOR_GET_G, D4D_COLOR_GET_R, D4D_EXTSRC_BUFF_SIZE, d4d_extsrcBuffer, D4D_FALSE, D4D_FileClose, D4D_FileWrite, D4D_LCD_GetOrientation(), D4D_LLD_LCD, D4D_ORIENT_PORTRAIT, D4D_ORIENT_PORTRAIT180, D4D_SCREEN_SIZE_LONGER_SIDE, D4D_SCREEN_SIZE_SHORTER_SIDE, D4D_TRUE, D4D_UNUSED, D4D_WRITE16L, D4D_WRITE32L, D4DLCD_FUNCTIONS_S::D4DLCD_Read_PixelColor, D4DLCD_FUNCTIONS_S::D4DLCD_SetWindow, and NULL.