Freescale's eGUI: d4d_progress_bar.c File Reference
d4d_progress_bar.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_PrgrsBarOnMessage (D4D_MESSAGE *pMsg)
static D4D_COLOR D4D_PrgrsBarComputeColorBar (D4D_OBJECT *pThis, D4D_PROGRESS_BAR_VALUE value)
static void D4D_PrgrsBarValue2Coor (D4D_OBJECT *pThis)
static void D4D_PrgrsBarOnDraw (D4D_MESSAGE *pMsg)
void D4D_PrgrsBarSetValue (D4D_OBJECT_PTR pThis, D4D_PROGRESS_BAR_VALUE value)
D4D_PROGRESS_BAR_VALUE D4D_PrgrsBarGetValue (D4D_OBJECT_PTR pThis)
void D4D_PrgrsBarSetBarColor (D4D_OBJECT_PTR pThis, D4D_COLOR color)
D4D_COLOR D4D_PrgrsBarGetBarColor (D4D_OBJECT_PTR pThis)
void D4D_PrgrsBarChangeValue (D4D_OBJECT_PTR pThis, D4D_PROGRESS_BAR_VALUE incr)
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_progress_barSysFunc
Detailed Description
D4D driver progress_bar object c file.
Author
Petr Gargulak
Version
0.0.11.0
Date
Feb-19-2013
Definition in file d4d_progress_bar.c.
Macro Definition Documentation
#define _calc
Definition at line 74 of file d4d_progress_bar.c.
Referenced by D4D_PrgrsBarOnDraw(), and D4D_PrgrsBarValue2Coor().
Function Documentation
void D4D_PrgrsBarChangeValue (D4D_OBJECT_PTR pThis, D4D_PROGRESS_BAR_VALUE incr)
Definition at line 265 of file d4d_progress_bar.c.
References D4D_COLOR_PRGRS_BAR_MAX_VAL, D4D_GET_PROGRESS_BAR, and D4D_PrgrsBarSetValue().
static D4D_COLOR D4D_PrgrsBarComputeColorBar (D4D_OBJECT * pThis, D4D_PROGRESS_BAR_VALUE value) static
Definition at line 185 of file d4d_progress_bar.c.
References D4D_CLR_SCHEME_PRGRS_BAR::barEnd, D4D_CLR_SCHEME_PRGRS_BAR::barFore, D4D_COLOR_PRGRS_BAR_MAX_VAL, D4D_GetCrossColor(), D4D_MulDivUU8(), D4D_ObjectGetScheme(), D4D_CLR_SCHEME_S::objectDepend, and D4D_CLR_SCHEME_OBJ::progressBar.
Referenced by D4D_PrgrsBarOnMessage(), and D4D_PrgrsBarSetValue().
D4D_COLOR D4D_PrgrsBarGetBarColor (D4D_OBJECT_PTR pThis)
Definition at line 252 of file d4d_progress_bar.c.
References D4D_PROGRESS_BAR_DATA::colorBar, D4D_GET_PROGRESS_BAR, and D4D_PROGRESS_BAR::pData.
D4D_PROGRESS_BAR_VALUE D4D_PrgrsBarGetValue (D4D_OBJECT_PTR pThis)
Definition at line 223 of file d4d_progress_bar.c.
References D4D_GET_PROGRESS_BAR, D4D_PROGRESS_BAR::pData, and D4D_PROGRESS_BAR_DATA::value.
static void D4D_PrgrsBarOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 137 of file d4d_progress_bar.c.
References _calc, D4D_CLR_SCHEME_PRGRS_BAR::barBckg, D4D_CLR_SCHEME_PRGRS_BAR::barFore, D4D_PROGRESS_BAR_DATA::colorBar, D4D_ASSERT, D4D_DIR_RIGHT, D4D_DrawFrame(), D4D_FillRRectColorScaleXY(), D4D_FillRRectXY(), D4D_GET_PROGRESS_BAR, D4D_GetGreyScale(), D4D_IsEnabled(), D4D_LINE_THIN, D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetScheme(), D4D_PRGRS_BAR_F_BAR_SCALECOLOR, D4D_PrgrsBarValue2Coor(), D4D_RBox(), D4D_SCRATCHPAD_SIZE, D4D_MESSAGE_S::draw, D4D_PROGRESS_BAR_DATA::drawActiveOnly, D4D_OBJECT_S::initFlags, D4D_CLR_SCHEME_S::objectDepend, D4D_PROGRESS_BAR::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_CLR_SCHEME_OBJ::progressBar, D4D_OBJECT_S::radius, and D4D_OBJECT_S::size.
Referenced by D4D_PrgrsBarOnMessage().
void D4D_PrgrsBarOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 296 of file d4d_progress_bar.c.
References D4D_CLR_SCHEME_PRGRS_BAR::barFore, D4D_GET_PROGRESS_BAR, D4D_MSG_DRAW, D4D_MSG_ONINIT, D4D_OBJECT_F_NOTINIT, D4D_ObjectGetScheme(), D4D_ObjOnMessage(), D4D_PRGRS_BAR_F_BAR_AUTOCOLOR, D4D_PRGRS_BAR_F_BAR_SCALECOLOR, D4D_PrgrsBarComputeColorBar(), D4D_PrgrsBarOnDraw(), D4D_OBJECT_DATA_S::flags, D4D_OBJECT_S::initFlags, D4D_MESSAGE_S::nMsgId, D4D_CLR_SCHEME_S::objectDepend, D4D_OBJECT_S::pData, D4D_MESSAGE_S::pObject, and D4D_CLR_SCHEME_OBJ::progressBar.
void D4D_PrgrsBarSetBarColor (D4D_OBJECT_PTR pThis, D4D_COLOR color)
Definition at line 235 of file d4d_progress_bar.c.
References D4D_PROGRESS_BAR_DATA::colorBar, D4D_FALSE, D4D_GET_PROGRESS_BAR, D4D_InvalidateObject(), D4D_PRGRS_BAR_F_BAR_AUTOCOLOR, D4D_PRGRS_BAR_F_BAR_SCALECOLOR, D4D_OBJECT_S::initFlags, and D4D_PROGRESS_BAR::pData.
void D4D_PrgrsBarSetValue (D4D_OBJECT_PTR pThis, D4D_PROGRESS_BAR_VALUE value)
Definition at line 199 of file d4d_progress_bar.c.
References D4D_PROGRESS_BAR_DATA::colorBar, D4D_FALSE, D4D_GET_PROGRESS_BAR, D4D_InvalidateObject(), D4D_PRGRS_BAR_F_BAR_AUTOCOLOR, D4D_PRGRS_BAR_F_BAR_SCALECOLOR, D4D_PrgrsBarComputeColorBar(), D4D_TRUE, D4D_PROGRESS_BAR_DATA::drawActiveOnly, D4D_OBJECT_S::initFlags, D4D_PROGRESS_BAR::pData, and D4D_PROGRESS_BAR_DATA::value.
Referenced by D4D_PrgrsBarChangeValue().
static void D4D_PrgrsBarValue2Coor (D4D_OBJECT * pThis) static
Definition at line 86 of file d4d_progress_bar.c.
References _calc, D4D_COLOR_PRGRS_BAR_MAX_VAL, D4D_ComputeGeometry(), D4D_GET_PROGRESS_BAR, D4D_GetClientToScreenPoint(), D4D_MulDivUU, D4D_PRGRS_BAR_BAR_OFF, D4D_PROGRESS_BAR::pData, D4D_OBJECT_S::position, D4D_OBJECT_S::radius, and D4D_PROGRESS_BAR_DATA::value.
Referenced by D4D_PrgrsBarOnDraw().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_progress_barSysFunc
Definition at line 52 of file d4d_progress_bar.c.