Freescale's eGUI: d4d_gauge.c File Reference
d4d_gauge.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Typedefs
typedef struct D4D_GAUGE_VAL2PT_S D4D_GAUGE_VAL2PT
Functions
void D4D_GaugOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_GaugeGetTextBuffer (D4D_OBJECT *pThis)
static D4D_POINT D4D_GaugeGetAnglePoint (D4D_GAUGE *pGaug, D4D_GAUGE_VALUE value)
static void D4D_GaugValue2Point (D4D_OBJECT *pThis)
static void D4D_GaugOnDraw (D4D_MESSAGE *pMsg)
void D4D_GaugSetValue (D4D_OBJECT_PTR pThis, D4D_GAUGE_VALUE value)
The function sets the new value of gauge.
D4D_GAUGE_VALUE D4D_GaugGetValue (D4D_OBJECT_PTR pThis)
The function gets the current value of gauge.
void D4D_GaugSetLimits (D4D_OBJECT_PTR pThis, const D4D_GAUGE_LIMITS *pLimits)
The function sets the new limits values of gauge.
void D4D_GaugGetLimits (D4D_OBJECT_PTR pThis, D4D_GAUGE_LIMITS *pLimits)
The function gets the values of gauge limit structure.
void D4D_GaugSetDir (D4D_OBJECT_PTR pThis, D4D_TREND trend)
The function set the trend/direction of gauge.
D4D_TREND D4D_GaugGetDir (D4D_OBJECT_PTR pThis)
The function gets the trend/direction of gauge object.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_gaugeSysFunc
Detailed Description
D4D driver gauge object c file.
Author
Petr Gargulak
Version
0.0.57.0
Date
Oct-15-2013
Definition in file d4d_gauge.c.
Macro Definition Documentation
#define _calc
Definition at line 74 of file d4d_gauge.c.
Referenced by D4D_GaugeGetAnglePoint(), D4D_GaugOnDraw(), and D4D_GaugValue2Point().
Typedef Documentation
typedef struct D4D_GAUGE_VAL2PT_S D4D_GAUGE_VAL2PT
Function Documentation
static D4D_POINT D4D_GaugeGetAnglePoint (D4D_GAUGE * pGaug, D4D_GAUGE_VALUE value) static
Definition at line 84 of file d4d_gauge.c.
References _calc, D4D_GAUGE_LIMITS::angleMax, D4D_GAUGE_LIMITS::angleMin, D4D_CLOCK_WISE, D4D_Cos(), D4D_MulDivSU, D4D_MulDivUU8(), D4D_Sin(), D4D_GAUGE_DATA::limits, D4D_GAUGE::pData, D4D_GAUGE::pointerLen, D4D_GAUGE_DATA::trend, D4D_GAUGE_LIMITS::valueMax, D4D_GAUGE_LIMITS::valueMin, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GaugValue2Point().
D4D_STRING * D4D_GaugeGetTextBuffer (D4D_OBJECT * pThis)
Get object text buffer
Definition at line 397 of file d4d_gauge.c.
References D4D_GET_GAUGE.
static void D4D_GaugOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 145 of file d4d_gauge.c.
References _calc, D4D_CLR_SCHEME_S::bckg, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ALIGN_H_CENTER_MASK, D4D_ALIGN_V_CENTER_MASK, D4D_ASSERT, D4D_DrawFrame(), D4D_DrawRBmpRect, D4D_DrawTextRect, D4D_FillCircle(), D4D_FillRRect(), D4D_GAUGE_F_HUB, D4D_GAUGE_F_REDRAW_TEXT, D4D_GAUGE_F_THICK_POINTER, D4D_GAUGE_HUB_RADIUS, D4D_GaugValue2Point(), D4D_GET_GAUGE, D4D_GetFontHeight(), D4D_GetGreyScale(), D4D_GetTextWidth(), D4D_IsEnabled(), D4D_LINE_THICK, D4D_LINE_THIN, D4D_LineTo(), D4D_MoveTo(), D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetScheme(), D4D_SCRATCHPAD_SIZE, D4D_MESSAGE_S::draw, D4D_STRING_S::fontId, D4D_CLR_SCHEME_OBJ::gauge, D4D_CLR_SCHEME_GAUG::hub, D4D_OBJECT_S::initFlags, NULL, D4D_CLR_SCHEME_S::objectDepend, D4D_GAUGE::pBmpBkgd, D4D_GAUGE::pData, D4D_MESSAGE_S::pObject, D4D_CLR_SCHEME_GAUG::pointer, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_GAUGE::textBuff, D4D_GAUGE::txtOff, D4D_GAUGE_DATA::value, D4D_GAUGE_DATA::valueLast, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GaugOnMessage().
void D4D_GaugOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 374 of file d4d_gauge.c.
References D4D_FocusSet(), D4D_GaugOnDraw(), D4D_MSG_DRAW, D4D_MSG_TOUCHED, D4D_ObjOnMessage(), D4D_MESSAGE_S::nMsgId, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::pScreen.
static void D4D_GaugValue2Point (D4D_OBJECT * pThis) static
Definition at line 116 of file d4d_gauge.c.
References _calc, D4D_ComputeGeometry(), D4D_GaugeGetAnglePoint(), D4D_GET_GAUGE, D4D_GetClientToScreenPoint(), D4D_GAUGE::hubOff, D4D_GAUGE::pData, D4D_OBJECT_S::position, D4D_GAUGE_DATA::value, D4D_GAUGE_DATA::valueLast, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GaugOnDraw().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_gaugeSysFunc
Definition at line 55 of file d4d_gauge.c.