Freescale's eGUI: d4d_low.c File Reference
d4d_low.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
#include "common_files/d4d_lldapi.h"
Functions
static void D4D_LCD_QPlot4points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_LINETYPE line_type, D4D_COLOR color, D4D_QUADRANT quadrant)
static void D4D_LCD_QPlot4pointsfill (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_COLOR color, D4D_QUADRANT quadrant)
static void D4D_LCD_QPlot8points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color, D4D_QUADRANT quadrant)
D4D_BOOL D4D_LCD_Init (void)
D4D_ORIENTATION D4D_LCD_GetOrientation (void)
void D4D_LCD_SetOrientation (D4D_ORIENTATION new_orientation)
D4D_COOR D4D_DisplayWidth (void)
D4D_COOR D4D_DisplayHeight (void)
void D4D_LCD_SwapCoor (D4D_COOR *c1, D4D_COOR *c2)
void D4D_LCD_PutPixel (D4D_COOR x1, D4D_COOR y1, D4D_LINETYPE line_type, D4D_COLOR color)
void D4D_LCD_Box (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color)
void D4D_LCD_Rect (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE line_type, D4D_COLOR color)
void D4D_LCD_Line (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE line_type, D4D_COLOR color)
static void D4D_LCD_Plot4points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_LINETYPE line_type, D4D_COLOR color)
static void D4D_LCD_Plot4pointsfill (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_COLOR color)
static void D4D_LCD_Plot8points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color)
void D4D_LCD_Circle (D4D_COOR cx, D4D_COOR cy, D4D_COOR radius, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color)
void D4D_LCD_RBox (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color, D4D_COOR radius)
void D4D_LCD_RRect (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE line_type, D4D_COLOR color, D4D_COOR radius)
void D4D_LCD_QCircle (D4D_COOR cx, D4D_COOR cy, D4D_COOR radius, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color, D4D_QUADRANT quadrant)
void D4D_TCH_Calibrate (D4D_COLOR fore, D4D_COLOR bckg)
void D4D_TCH_DrawCalibrationPoint (D4D_COOR X, D4D_COOR Y, D4D_COLOR Color)
Variables
static D4D_ORIENTATION d4d_orientation
Detailed Description
D4D driver low level graphic function c file.
Author
Petr Gargulak
Version
0.0.53.0
Date
Jan-14-2014
Definition in file d4d_low.c.
Function Documentation
D4D_COOR D4D_DisplayHeight (void)
Definition at line 167 of file d4d_low.c.
References D4D_ORIENT_PORTRAIT, D4D_ORIENT_PORTRAIT180, d4d_orientation, D4D_SCREEN_SIZE_LONGER_SIDE, and D4D_SCREEN_SIZE_SHORTER_SIDE.
Referenced by D4D_ClearScreen().
D4D_COOR D4D_DisplayWidth (void)
Definition at line 159 of file d4d_low.c.
References D4D_ORIENT_PORTRAIT, D4D_ORIENT_PORTRAIT180, d4d_orientation, D4D_SCREEN_SIZE_LONGER_SIDE, and D4D_SCREEN_SIZE_SHORTER_SIDE.
Referenced by D4D_ClearScreen().
void D4D_LCD_Box (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color)
Definition at line 212 of file d4d_low.c.
References D4D_LCD_SwapCoor(), D4D_LLD_LCD, D4DLCD_FLSH_ELEMENT, D4DLCD_FUNCTIONS_S::D4DLCD_FlushBuffer, D4DLCD_FUNCTIONS_S::D4DLCD_Send_PixelColor, and D4DLCD_FUNCTIONS_S::D4DLCD_SetWindow.
Referenced by D4D_BoxToXY(), D4D_BoxXY(), D4D_ClearScreen(), D4D_FillRect(), D4D_FillRectColorScaleXY(), D4D_FillRectTo(), D4D_FillRectToXY(), D4D_FillRectXY(), D4D_FillRRectColorScaleXY(), D4D_LCD_Line(), D4D_LCD_Plot4pointsfill(), D4D_LCD_PrintChr(), D4D_LCD_QPlot4pointsfill(), and D4D_LCD_RBox().
void D4D_LCD_Circle (D4D_COOR cx, D4D_COOR cy, D4D_COOR radius, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color)
Definition at line 368 of file d4d_low.c.
References D4D_LCD_Plot8points().
Referenced by D4D_Circle(), D4D_CircleXY(), D4D_FillCircle(), and D4D_FillCircleXY().
D4D_ORIENTATION D4D_LCD_GetOrientation (void)
Definition at line 147 of file d4d_low.c.
References d4d_orientation.
Referenced by D4D_PrintScreenToBMP().
D4D_BOOL D4D_LCD_Init (void)
Initialize
Definition at line 86 of file d4d_low.c.
References D4D_FALSE, D4D_LCD_SetOrientation(), D4D_LLD_LCD, D4D_LLD_MOUSE, D4D_LLD_TCH, D4D_ORIENT_PORTRAIT, D4D_TRUE, D4DLCD_FUNCTIONS_S::D4DLCD_DeInit, D4DLCD_FUNCTIONS_S::D4DLCD_Delay_ms, D4DLCD_FUNCTIONS_S::D4DLCD_FlushBuffer, D4DLCD_FUNCTIONS_S::D4DLCD_Init, D4DLCD_FUNCTIONS_S::D4DLCD_Read_PixelColor, D4DLCD_FUNCTIONS_S::D4DLCD_Send_PixelColor, D4DLCD_FUNCTIONS_S::D4DLCD_SetOrientation, D4DLCD_FUNCTIONS_S::D4DLCD_SetWindow, NULL, and D4D_TOUCHSCREEN_CALIB::ScreenCalibrated.
Referenced by D4D_Init().
void D4D_LCD_Line (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE line_type, D4D_COLOR color)
Definition at line 246 of file d4d_low.c.
References D4D_Abs16(), D4D_LCD_Box(), D4D_LCD_PutPixel(), D4D_LCD_SwapCoor(), and D4D_LINE_THICK.
Referenced by D4D_LCD_Rect(), D4D_LCD_RRect(), D4D_LineTo(), and D4D_LineToXY().
static void D4D_LCD_Plot4points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_LINETYPE line_type, D4D_COLOR color) static
Definition at line 336 of file d4d_low.c.
References D4D_LCD_PutPixel().
Referenced by D4D_LCD_Plot8points().
static void D4D_LCD_Plot4pointsfill (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_COLOR color) static
Definition at line 344 of file d4d_low.c.
References D4D_LCD_Box().
Referenced by D4D_LCD_Plot8points().
static void D4D_LCD_Plot8points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color) static
Definition at line 351 of file d4d_low.c.
References D4D_LCD_Plot4points(), and D4D_LCD_Plot4pointsfill().
Referenced by D4D_LCD_Circle().
void D4D_LCD_PutPixel (D4D_COOR x1, D4D_COOR y1, D4D_LINETYPE line_type, D4D_COLOR color)
Definition at line 192 of file d4d_low.c.
References D4D_LINE_THICK, D4D_LLD_LCD, D4DLCD_FLSH_ELEMENT, D4DLCD_FUNCTIONS_S::D4DLCD_FlushBuffer, D4DLCD_FUNCTIONS_S::D4DLCD_Send_PixelColor, and D4DLCD_FUNCTIONS_S::D4DLCD_SetWindow.
Referenced by D4D_ImgDecBmpDraw(), D4D_LCD_Line(), D4D_LCD_Plot4points(), D4D_LCD_QCircle(), D4D_LCD_QPlot4points(), D4D_PutPixel(), D4D_PutPixelTo(), and D4D_PutPixelXY().
void D4D_LCD_QCircle (D4D_COOR cx, D4D_COOR cy, D4D_COOR radius, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color, D4D_QUADRANT quadrant)
Definition at line 574 of file d4d_low.c.
References D4D_LCD_PutPixel(), and D4D_LCD_QPlot8points().
Referenced by D4D_FillQuadrant(), D4D_FillQuadrantXY(), D4D_LCD_RBox(), D4D_LCD_RRect(), D4D_Quadrant(), and D4D_QuadrantXY().
static void D4D_LCD_QPlot4points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_LINETYPE line_type, D4D_COLOR color, D4D_QUADRANT quadrant) static
Definition at line 521 of file d4d_low.c.
References D4D_LCD_PutPixel(), D4D_QUAD_1, D4D_QUAD_2, D4D_QUAD_3, and D4D_QUAD_4.
Referenced by D4D_LCD_QPlot8points().
static void D4D_LCD_QPlot4pointsfill (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_COLOR color, D4D_QUADRANT quadrant) static
Definition at line 540 of file d4d_low.c.
References D4D_LCD_Box(), D4D_QUAD_1, D4D_QUAD_2, D4D_QUAD_3, and D4D_QUAD_4.
Referenced by D4D_LCD_QPlot8points().
static void D4D_LCD_QPlot8points (D4D_COOR cx, D4D_COOR cy, D4D_COOR x, D4D_COOR y, D4D_BOOL fill, D4D_LINETYPE line_type, D4D_COLOR color, D4D_QUADRANT quadrant) static
Definition at line 560 of file d4d_low.c.
References D4D_LCD_QPlot4points(), and D4D_LCD_QPlot4pointsfill().
Referenced by D4D_LCD_QCircle().
void D4D_LCD_RBox (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color, D4D_COOR radius)
Definition at line 410 of file d4d_low.c.
References D4D_LCD_Box(), D4D_LCD_QCircle(), D4D_LCD_SwapCoor(), D4D_LINE_THIN, D4D_QUAD_1, D4D_QUAD_2, D4D_QUAD_3, D4D_QUAD_4, and D4D_TRUE.
Referenced by D4D_FillRRect(), D4D_FillRRectTo(), D4D_FillRRectToXY(), D4D_FillRRectXY(), D4D_RBoxToXY(), and D4D_RBoxXY().
void D4D_LCD_Rect (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE line_type, D4D_COLOR color)
Definition at line 238 of file d4d_low.c.
References D4D_LCD_Line().
Referenced by D4D_BoxToXY(), D4D_BoxXY(), D4D_LCD_RRect(), D4D_Rect(), D4D_RectTo(), D4D_RectToXY(), and D4D_RectXY().
void D4D_LCD_RRect (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE line_type, D4D_COLOR color, D4D_COOR radius)
Definition at line 466 of file d4d_low.c.
References D4D_FALSE, D4D_LCD_Line(), D4D_LCD_QCircle(), D4D_LCD_Rect(), D4D_LCD_SwapCoor(), D4D_QUAD_1, D4D_QUAD_2, D4D_QUAD_3, and D4D_QUAD_4.
Referenced by D4D_RBoxToXY(), D4D_RBoxXY(), D4D_RRect(), D4D_RRectTo(), D4D_RRectToXY(), and D4D_RRectXY().
void D4D_LCD_SetOrientation (D4D_ORIENTATION new_orientation)
Definition at line 152 of file d4d_low.c.
References D4D_LLD_LCD, d4d_orientation, and D4DLCD_FUNCTIONS_S::D4DLCD_SetOrientation.
Referenced by D4D_LCD_Init(), and D4D_SetOrientation().
void D4D_LCD_SwapCoor (D4D_COOR * c1, D4D_COOR * c2)
Definition at line 176 of file d4d_low.c.
Referenced by D4D_LCD_Box(), D4D_LCD_Line(), D4D_LCD_RBox(), and D4D_LCD_RRect().
void D4D_TCH_Calibrate (D4D_COLOR fore, D4D_COLOR bckg)
Definition at line 927 of file d4d_low.c.
References D4D_UNUSED.
void D4D_TCH_DrawCalibrationPoint (D4D_COOR X, D4D_COOR Y, D4D_COLOR Color)
Definition at line 933 of file d4d_low.c.
References D4D_UNUSED.
Variable Documentation
D4D_ORIENTATION d4d_orientation static
Include headers
Global variables
Local variables
Definition at line 68 of file d4d_low.c.
Referenced by D4D_DisplayHeight(), D4D_DisplayWidth(), D4D_LCD_GetOrientation(), and D4D_LCD_SetOrientation().