Freescale's eGUI: d4d_group_box.c File Reference
d4d_group_box.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Functions
void D4D_GroupBoxOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_GroupBoxGetTextBuffer (D4D_OBJECT *pThis)
static void D4D_GroupBoxOnDraw (D4D_MESSAGE *pMsg)
Variables
D4D_MARGIN groupBox_marginDefault
const D4D_OBJECT_SYS_FUNCTION d4d_groupBoxSysFunc
Detailed Description
D4D driver groupBox object c file.
Author
Petr Gargulak
Version
0.0.4.0
Date
Oct-2-2013
Definition in file d4d_group_box.c.
Function Documentation
D4D_STRING* D4D_GroupBoxGetTextBuffer (D4D_OBJECT * pThis)
static void D4D_GroupBoxOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 75 of file d4d_group_box.c.
References D4D_MARGIN::bottom, D4D_SIZE::cx, D4D_SIZE::cy, D4D_BEVEL_BCKG_INTENSITY, D4D_BEVEL_WIDTH, D4D_ChangeColorIntesity(), D4D_DrawFrame(), D4D_DrawTextRect, D4D_FillRRect(), D4D_GET_GROUP_BOX, D4D_GetClientToScreenPoint(), D4D_GetTextWidth(), D4D_GROUP_BOX_F_CONTENT_OUTLINE, D4D_GROUP_BOX_TEXT_OFFSET, D4D_LINE_THIN, D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_OBJECT_F_BEVEL_MASK, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_Rect(), D4D_RRect(), D4D_MESSAGE_S::draw, D4D_STRING_S::fontId, D4D_OBJECT_S::initFlags, D4D_MARGIN::left, D4D_OBJECT_S::pMargin, D4D_MESSAGE_S::pObject, D4D_OBJECT_S::position, D4D_MESSAGE_S::prm, D4D_STRING_S::pText, D4D_OBJECT_S::radius, D4D_MARGIN::right, D4D_OBJECT_S::size, D4D_GROUP_BOX::textBuff, D4D_MARGIN::top, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GroupBoxOnMessage().
void D4D_GroupBoxOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 185 of file d4d_group_box.c.
References D4D_GroupBoxOnDraw(), D4D_MSG_DRAW, D4D_ObjOnMessage(), and D4D_MESSAGE_S::nMsgId.
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_groupBoxSysFunc
Definition at line 61 of file d4d_group_box.c.
D4D_MARGIN groupBox_marginDefault
Definition at line 53 of file d4d_group_box.c.