Freescale's eGUI: d4d_imgdec_d4d.c File Reference
d4d_imgdec_d4d.c File Reference
#include "d4d.h"
#include "common_files/d4d_lldapi.h"
#include "common_files/d4d_private.h"
#include "common_files/d4d_imgdec_d4d.h"
#include "common_files/d4d_imgdec_d4dint.h"
Functions
void D4D_ImgDecExtD4DDraw (D4D_COOR x, D4D_COOR y, D4D_CHAR *pFileName, D4D_BOOL greyScale, D4D_COOR radius)
D4D_COOR D4D_ImgDecExtD4DGetWidth (D4D_CHAR *pFileName)
D4D_COOR D4D_ImgDecExtD4DGetHeight (D4D_CHAR *pFileName)
D4D_SIZE D4D_ImgDecExtD4DGetSize (D4D_CHAR *pFileName)
int D4D_ImgDecExtD4DGetHeader (D4D_CHAR *pFileName, void *pBuff, int max_size)
Detailed Description
D4D driver external pictures d4d decoder functions c file.
Author
Petr Gargulak
Version
0.0.13.0
Date
Feb-19-2013
Definition in file d4d_imgdec_d4d.c.
Function Documentation
void D4D_ImgDecExtD4DDraw (D4D_COOR x, D4D_COOR y, D4D_CHAR * pFileName, D4D_BOOL greyScale, D4D_COOR radius)
Definition at line 91 of file d4d_imgdec_d4d.c.
References D4D_D4DBMP_DECODE_S::compress, D4D_D4DBMP_DECODE_S::curSubPxl, D4D_ASSERT, D4D_BMP_16MNOPAL, D4D_BMP_256KNOPAL, D4D_BMP_256NOPAL, D4D_BMP_65536NOPAL, D4D_BMP_CLR_DEPTH_MASK, D4D_BMP_COMPRESS_MASK, D4D_BMP_PAL_16, D4D_BMP_PAL_2, D4D_BMP_PAL_256, D4D_BMP_TYPE_MASK, D4D_BoxXY(), D4D_CompareStrings(), D4D_EXTSRC_BUFF_SIZE, D4D_EXTSRC_HEADER_D4D_SIZE, d4d_extsrcBuffer, D4D_FileClose, D4D_FileRead, D4D_FileSeek, D4D_GetActiveScreen(), D4D_LINE_THIN, D4D_LineToXY(), D4D_LLD_LCD, D4D_MemAlloc, D4D_MemFree, D4D_MoveToXY(), D4D_RBoxXY(), D4D_RndCornerGetNonPrintedPxl(), D4D_ScreenGetScheme(), D4D_SEEK_SET, D4D_UNUSED, D4DLCD_FLSH_ELEMENT, D4DLCD_FUNCTIONS_S::D4DLCD_FlushBuffer, D4DLCD_FUNCTIONS_S::D4DLCD_Send_PixelColor, D4DLCD_FUNCTIONS_S::D4DLCD_SetWindow, D4D_D4DBMP_DECODE_S::dataCnt, D4D_D4DBMP_DECODE_S::dataIx, D4D_D4DBMP_DECODE_S::GetDataFunc, D4D_D4DBMP_DECODE_S::GetPxlDecoder, D4D_D4DBMP_DECODE_S::greyScale, D4D_D4DBMP_DECODE_S::ix, NULL, D4D_D4DBMP_DECODE_S::pBmp, D4D_D4DBMP_DECODE_S::pFile, D4D_D4DBMP_DECODE_S::pPalette, and D4D_D4DBMP_DECODE_S::rptCnt.
int D4D_ImgDecExtD4DGetHeader (D4D_CHAR * pFileName, void * pBuff, int max_size)
Get header - BMP image file
Definition at line 506 of file d4d_imgdec_d4d.c.
References D4D_EXTSRC_HEADER_D4D_SIZE, D4D_FileClose, D4D_FileRead, and NULL.
D4D_COOR D4D_ImgDecExtD4DGetHeight (D4D_CHAR * pFileName)
Get height - BMP image file
Definition at line 451 of file d4d_imgdec_d4d.c.
References D4D_SIZE::cy, and D4D_ImgDecExtD4DGetSize().
D4D_SIZE D4D_ImgDecExtD4DGetSize (D4D_CHAR * pFileName)
Get size - BMP image file
Definition at line 464 of file d4d_imgdec_d4d.c.
References D4D_SIZE::cx, D4D_SIZE::cy, d4d_extsrcBuffer, D4D_FileClose, D4D_FileRead, D4D_FileSeek, D4D_READ16L, D4D_SEEK_SET, d4d_size_zero, and NULL.
Referenced by D4D_ImgDecExtD4DGetHeight(), and D4D_ImgDecExtD4DGetWidth().
D4D_COOR D4D_ImgDecExtD4DGetWidth (D4D_CHAR * pFileName)
Internal Bitmap support
Get width - BMP image file
Definition at line 439 of file d4d_imgdec_d4d.c.
References D4D_SIZE::cx, and D4D_ImgDecExtD4DGetSize().