Freescale's eGUI: d4d_text_box.c File Reference
d4d_text_box.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
void D4D_TextBoxOnMessage (D4D_MESSAGE *pMsg)
D4D_STRING * D4D_TextBoxGetTextBuffer (D4D_OBJECT *pThis)
static D4D_BOOL D4D_TextBoxScrollBarSetup (D4D_OBJECT *pObject)
static D4D_INDEX D4D_TextBoxGetMaxLineChars (D4D_TCHAR *pText, D4D_INDEX offset, D4D_TAB *pTab, D4D_COOR len, D4D_FONT fnt)
static D4D_BOOL D4D_TextBoxGetWordSpec (D4D_TXTBX_WORD_DESC *wordDesc)
static D4D_BOOL D4D_TextBoxGetCharsToLine (D4D_TXTBX_WORD_DESC *wordDesc)
static D4D_INDEX D4D_TextBoxGetLineCount (D4D_OBJECT *pThis)
static D4D_INDEX D4D_TextBoxFindLineStartChar (D4D_OBJECT *pThis, D4D_INDEX line)
static void D4D_TextBoxOnInit (D4D_OBJECT *pObject)
static void D4D_TextBoxValue2Coor (D4D_OBJECT *pThis)
static D4D_BOOL D4D_TextBoxGetWordSpecInt (D4D_TCHAR ch, D4D_TXTBX_WORD_DESC *wordDesc)
static void D4D_TextBoxOnDraw (D4D_MESSAGE *pMsg)
void D4D_TextBoxScrollBarsFeedBack (D4D_OBJECT *pThis, D4D_INDEX old_position, D4D_INDEX new_position)
void D4D_TextBoxRefreshAll (D4D_OBJECT *pObject)
The function reinitialize whole object.
void D4D_TextBoxChangeText (D4D_OBJECT *pObject, D4D_TCHAR *pText)
The function change the text of the text box.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_textboxSysFunc
Detailed Description
D4D driver textbox object c file.
Author
Petr Gargulak
Version
0.0.29.0
Date
Jan-14-2014
Definition in file d4d_text_box.c.
Macro Definition Documentation
#define _calc
Definition at line 93 of file d4d_text_box.c.
Referenced by D4D_TextBoxFindLineStartChar(), D4D_TextBoxGetLineCount(), D4D_TextBoxOnDraw(), D4D_TextBoxScrollBarSetup(), and D4D_TextBoxValue2Coor().
Function Documentation
static D4D_INDEX D4D_TextBoxFindLineStartChar (D4D_OBJECT * pThis, D4D_INDEX line) static
Definition at line 391 of file d4d_text_box.c.
References _calc, D4D_GET_TEXTBOX, D4D_TextBoxGetMaxLineChars(), D4D_TextBoxValue2Coor(), NULL, D4D_TEXTBOX::pData, D4D_TEXTBOX::pTabTable, D4D_TAB::pTabTable, D4D_TXTBX_DATA_S::pTxtArr, D4D_TAB::tabOffset, and D4D_TEXTBOX::textFontId.
Referenced by D4D_TextBoxScrollBarsFeedBack().
static D4D_BOOL D4D_TextBoxGetCharsToLine (D4D_TXTBX_WORD_DESC * wordDesc) static
Definition at line 248 of file d4d_text_box.c.
References D4D_EXTSRC_BUFF_SIZE, d4d_extsrcBuffer, d4d_extsrcLocale, D4D_FALSE, D4D_GetCharWidth(), D4D_GetInternalStringPointer(), D4D_TRUE, D4DLOCALE_FUNCTIONS_S::D4DLOCALE_TranslateStr, and NULL.
Referenced by D4D_TextBoxGetMaxLineChars().
static D4D_INDEX D4D_TextBoxGetLineCount (D4D_OBJECT * pThis) static
Definition at line 358 of file d4d_text_box.c.
References _calc, D4D_GET_TEXTBOX, D4D_TextBoxGetMaxLineChars(), NULL, D4D_TEXTBOX::pData, D4D_TEXTBOX::pTabTable, D4D_TAB::pTabTable, D4D_TXTBX_DATA_S::pTxtArr, D4D_TAB::tabOffset, and D4D_TEXTBOX::textFontId.
Referenced by D4D_TextBoxScrollBarSetup(), and D4D_TextBoxValue2Coor().
static D4D_INDEX D4D_TextBoxGetMaxLineChars (D4D_TCHAR * pText, D4D_INDEX offset, D4D_TAB * pTab, D4D_COOR len, D4D_FONT fnt) static
Definition at line 318 of file d4d_text_box.c.
References D4D_TextBoxGetCharsToLine(), and D4D_TextBoxGetWordSpec().
Referenced by D4D_TextBoxFindLineStartChar(), D4D_TextBoxGetLineCount(), and D4D_TextBoxOnDraw().
D4D_STRING* D4D_TextBoxGetTextBuffer (D4D_OBJECT * pThis)
static D4D_BOOL D4D_TextBoxGetWordSpec (D4D_TXTBX_WORD_DESC * wordDesc) static
Definition at line 178 of file d4d_text_box.c.
References D4D_EXTSRC_BUFF_SIZE, d4d_extsrcBuffer, d4d_extsrcLocale, D4D_FALSE, D4D_GetInternalStringPointer(), D4D_TextBoxGetWordSpecInt(), D4D_TRUE, D4DLOCALE_FUNCTIONS_S::D4DLOCALE_TranslateStr, and NULL.
Referenced by D4D_TextBoxGetMaxLineChars().
static D4D_BOOL D4D_TextBoxGetWordSpecInt (D4D_TCHAR ch, D4D_TXTBX_WORD_DESC * wordDesc) static
Definition at line 128 of file d4d_text_box.c.
References D4D_FALSE, D4D_GetCharWidth(), D4D_GetNextTab(), and D4D_TRUE.
Referenced by D4D_TextBoxGetWordSpec().
static void D4D_TextBoxOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 461 of file d4d_text_box.c.
References _calc, D4D_STRING_S::buffSize, D4D_SIZE::cx, D4D_SIZE::cy, D4D_DrawFrame(), D4D_DrawTextRectTab(), D4D_FALSE, D4D_FillRRect(), D4D_GET_TEXTBOX, D4D_GetFontHeight(), D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeFillColor(), D4D_TextBoxGetMaxLineChars(), D4D_TextBoxValue2Coor(), D4D_TRUE, D4D_MESSAGE_S::draw, D4D_TXTBX_DATA_S::firstShowedCharIx, D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, NULL, D4D_TEXTBOX::pData, D4D_MESSAGE_S::pObject, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_MESSAGE_S::prm, D4D_TEXTBOX::pTabTable, D4D_TAB::pTabTable, D4D_STRING_S::pText, D4D_TXTBX_DATA_S::pTxtArr, D4D_OBJECT_S::radius, D4D_TXTBX_DATA_S::redrawText, D4D_OBJECT_S::size, D4D_STRING_S::str_properties, D4D_TAB::tabOffset, D4D_STR_PROPERTIES_S::text_properties, D4D_TEXTBOX::textFontId, and D4D_POINT::y.
Referenced by D4D_TextBoxOnMessage().
static void D4D_TextBoxOnInit (D4D_OBJECT * pObject) static
Definition at line 535 of file d4d_text_box.c.
References D4D_GET_TEXTBOX, D4D_InvalidateObject(), D4D_TextBoxScrollBarSetup(), D4D_TRUE, D4D_TXTBX_DATA_S::firstShowedCharIx, and D4D_TEXTBOX::pData.
Referenced by D4D_TextBoxChangeText(), D4D_TextBoxOnMessage(), and D4D_TextBoxRefreshAll().
void D4D_TextBoxOnMessage (D4D_MESSAGE * pMsg)
THE INTERNAL API FUNCTIONS
Definition at line 647 of file d4d_text_box.c.
References D4D_CaptureKeys(), D4D_FocusSet(), D4D_GET_TEXTBOX_SCROLL_BAR_HOR, D4D_KEY_SCANCODE_ENTER, D4D_KEY_SCANCODE_ESC, D4D_MSG_DRAW, D4D_MSG_KEYUP, D4D_MSG_KILLCAPTURE, D4D_MSG_KILLFOCUS, D4D_MSG_MOUSE_BTN_LEFT_UP, D4D_MSG_MOUSE_BTN_WHEEL_DOWN, D4D_MSG_MOUSE_BTN_WHEEL_UP, D4D_MSG_ONINIT, D4D_MSG_SETCAPTURE, D4D_MSG_SETFOCUS, D4D_MSG_TOUCHED, D4D_OBJECT_F_NOTINIT, D4D_OBJECT_F_VISIBLE, D4D_ObjOnMessage(), D4D_ScrlBrChangePosition(), D4D_TextBoxOnDraw(), D4D_TextBoxOnInit(), D4D_OBJECT_DATA_S::flags, D4D_MESSAGE_S::key, D4D_MESSAGE_S::nMsgId, NULL, D4D_OBJECT_S::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, and D4D_MESSAGE_S::pScreen.
static D4D_BOOL D4D_TextBoxScrollBarSetup (D4D_OBJECT * pObject) static
Definition at line 430 of file d4d_text_box.c.
References _calc, D4D_FALSE, D4D_GET_TEXTBOX_SCROLL_BAR_HOR, D4D_OBJECT_F_VISIBLE, D4D_ScrlBrSetPosition(), D4D_ScrlBrSetRange(), D4D_ScrlBrSetStep(), D4D_TextBoxGetLineCount(), D4D_TextBoxValue2Coor(), D4D_TRUE, and D4D_TXTBX_SCRLBR_STEP.
Referenced by D4D_TextBoxOnInit().
void D4D_TextBoxScrollBarsFeedBack (D4D_OBJECT * pThis, D4D_INDEX old_position, D4D_INDEX new_position)
THE INTERNAL HELP FUNCTIONS
Definition at line 557 of file d4d_text_box.c.
References D4D_FALSE, D4D_GET_TEXTBOX_DATA, D4D_GetParentObject(), D4D_InvalidateObject(), D4D_TextBoxFindLineStartChar(), D4D_TRUE, D4D_UNUSED, D4D_TXTBX_DATA_S::firstShowedCharIx, and D4D_TXTBX_DATA_S::redrawText.
static void D4D_TextBoxValue2Coor (D4D_OBJECT * pThis) static
Definition at line 95 of file d4d_text_box.c.
References _calc, D4D_ComputeGeometry(), D4D_GET_TEXTBOX, D4D_GET_TEXTBOX_SCROLL_BAR_HOR, D4D_GetClientToScreenPoint(), D4D_GetFontHeight(), D4D_OBJECT_F_VISIBLE, D4D_ROUND_CORNER_ENABLE, D4D_TextBoxGetLineCount(), D4D_TRUE, D4D_TXTBX_SCRLBR_WIDTH, D4D_OBJECT_S::position, D4D_OBJECT_S::radius, and D4D_TEXTBOX::textFontId.
Referenced by D4D_TextBoxFindLineStartChar(), D4D_TextBoxOnDraw(), and D4D_TextBoxScrollBarSetup().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_textboxSysFunc
Definition at line 77 of file d4d_text_box.c.