Freescale's eGUI: d4d_extsrc.c File Reference
d4d_extsrc.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
#include "common_files/d4d_lldapi.h"
Functions
int D4D_StrLen (register const D4D_CHAR *s)
The function returns length of string terminated by zero.
D4D_CHAR * D4D_StrCopy (register D4D_CHAR *sd, register const D4D_CHAR *ss)
The function copy string one string to other one (terminated by zero)
D4D_CHAR * D4D_StrCopyUnicode2Ascii (register D4D_CHAR *sd, register const D4D_WCHAR *ss)
The function copy string one string (UNICODE) to other one (STANDARD 8 bit)(terminated by zero)
D4D_WCHAR * D4D_StrCopyAscii2Unicode (register D4D_WCHAR *sd, register const D4D_CHAR *ss)
The function copy string one string (STANDARD 8 bit) to other one (UNICODE)(terminated by zero)
D4D_CHAR * D4D_StrCat (register D4D_CHAR *sd, register const D4D_CHAR *ss)
The function concatenate strings (terminated by zero)
D4D_WCHAR * D4D_StrCatUnicode (register D4D_WCHAR *sd, register const D4D_WCHAR *ss)
The function concatenate strings (terminated by zero) (UNICODE version)
int D4D_CompareStrings (const D4D_CHAR *s1, const D4D_CHAR *s2)
The function copare two strings (terminated by zero)
int D4D_CompareStringsUnicode (const D4D_WCHAR *s1, const D4D_WCHAR *s2)
The function copare two strings (terminated by zero) (UNICODE version)
void D4D_ToUpper (D4D_CHAR *s)
The function convert all small alpha characters to upper in string(terminated by zero)
LWord D4D_SwapLong (LWord n)
The function swap bytes in Long.
Word D4D_SwapWord (Word n)
The function swap bytes in Word.
Detailed Description
D4D driver extscr functions c file.
Author
Michal hanak, Petr Gargulak
Version
0.0.12.0
Date
Oct-2-2013
Definition in file d4d_extsrc.c.
Function Documentation
int D4D_CompareStrings (const D4D_CHAR * s1, const D4D_CHAR * s2)
The function copare two strings (terminated by zero)
Parameters
s1 - first string
s2 - second string
Returns
0 - strings are identical, <>0 - strings are different
Note
If the D4D_STD_STRING_H_INCLUDE is defined, the library strcmp() function is called. Only 1 Byte wide char is handled (not UNICODE).
Definition at line 250 of file d4d_extsrc.c.
Referenced by D4D_GetImgSrcType(), and D4D_ImgDecExtD4DDraw().
int D4D_CompareStringsUnicode (const D4D_WCHAR * s1, const D4D_WCHAR * s2)
The function copare two strings (terminated by zero) (UNICODE version)
Parameters
s1 - first string
s2 - second string
Returns
0 - strings are identical, <>0 - strings are different
Note
The strings MUST have type D4D_WCHAR*.
Definition at line 283 of file d4d_extsrc.c.
D4D_CHAR* D4D_StrCat (register D4D_CHAR * sd, register const D4D_CHAR * ss)
The function concatenate strings (terminated by zero)
Parameters
sd - destination string
ss - source string
Returns
pointer to destination string
Note
If the D4D_STD_STRING_H_INCLUDE is defined, the library strcat() function is called. Only 1 Byte wide char is handled (not UNICODE).
Definition at line 204 of file d4d_extsrc.c.
D4D_WCHAR* D4D_StrCatUnicode (register D4D_WCHAR * sd, register const D4D_WCHAR * ss)
The function concatenate strings (terminated by zero) (UNICODE version)
Parameters
sd - destination string
ss - source string
Returns
pointer to destination string
Note
Handling just only UNICODE strings.
Definition at line 229 of file d4d_extsrc.c.
D4D_CHAR* D4D_StrCopy (register D4D_CHAR * sd, register const D4D_CHAR * ss)
The function copy string one string to other one (terminated by zero)
Parameters
sd - destination string
ss - source string
Returns
pointer to destination string
Note
If the D4D_STD_STRING_H_INCLUDE is defined, the library strcpy() function is called. Only 1 Byte wide char is handled (not UNICODE).
Definition at line 147 of file d4d_extsrc.c.
D4D_WCHAR* D4D_StrCopyAscii2Unicode (register D4D_WCHAR * sd, register const D4D_CHAR * ss)
The function copy string one string (STANDARD 8 bit) to other one (UNICODE)(terminated by zero)
Parameters
sd - destination string
ss - source string
Returns
pointer to destination string
Note
Is used to convert strings from Unicode to standard ASCII.
Definition at line 186 of file d4d_extsrc.c.
D4D_CHAR* D4D_StrCopyUnicode2Ascii (register D4D_CHAR * sd, register const D4D_WCHAR * ss)
The function copy string one string (UNICODE) to other one (STANDARD 8 bit)(terminated by zero)
Parameters
sd - destination string
ss - source string
Returns
pointer to destination string
Note
Is used to convert strings from standard ASCII to Unicode.
Definition at line 169 of file d4d_extsrc.c.
int D4D_StrLen (register const D4D_CHAR * s)
The function returns length of string terminated by zero.
Parameters
s - input string
Returns
length of string
Note
If the D4D_STD_STRING_H_INCLUDE is defined, the library strlen() function is called. Only 1 Byte wide char is handled (not UNICODE).
Definition at line 121 of file d4d_extsrc.c.
LWord D4D_SwapLong (LWord n)
The function swap bytes in Long.
Parameters
n - input long number
Returns
swapped input long number
Note
Is Used to handling endianism.
Definition at line 328 of file d4d_extsrc.c.
Word D4D_SwapWord (Word n)
The function swap bytes in Word.
Parameters
n - input word number
Returns
swapped input word number
Note
Is Used to handling endianism.
Definition at line 345 of file d4d_extsrc.c.
Referenced by D4D_ImgDecIntD4DDraw(), D4D_ImgDecIntD4DGetHeader(), D4D_ImgDecIntD4DGetHeight(), D4D_ImgDecIntD4DGetSize(), and D4D_ImgDecIntD4DGetWidth().
void D4D_ToUpper (D4D_CHAR * s)
The function convert all small alpha characters to upper in string(terminated by zero)
Parameters
s - input string
Returns
none
Note
Only 1 Byte wide char is handled (not UNICODE).
Definition at line 311 of file d4d_extsrc.c.
Referenced by D4D_GetImgSrcType().