Freescale's eGUI: d4d_scroll_bar.c File Reference
d4d_scroll_bar.c File Reference
#include "d4d.h"
#include "common_files/d4d_private.h"
Macros
#define _calc
Functions
static void D4D_ScrlBrOnMessage (D4D_MESSAGE *pMsg)
static void D4D_ScrlBrOnKeyDown (D4D_MESSAGE *pMsg)
static void D4D_ScrlBrDrawArrow (D4D_POINT *ppt, D4D_COOR size, D4D_DIRECTION dir, D4D_COLOR color)
static void D4D_ScrlBrValue2Coor (D4D_OBJECT *pThis)
static void D4D_ScrlBrOnDraw (D4D_MESSAGE *pMsg)
void D4D_ScrlBrSetRange (D4D_OBJECT_PTR pObj, D4D_INDEX minimum, D4D_INDEX maximum)
The function sets the range of scroll bar scale.
void D4D_ScrlBrSetStep (D4D_OBJECT_PTR pObj, D4D_INDEX page, D4D_INDEX step)
The function sets the step and page of scroll bar scale.
void D4D_ScrlBrSetPosition (D4D_OBJECT_PTR pObj, D4D_INDEX position)
The function sets the scroll bar position.
D4D_INDEX D4D_ScrlBrGetPosition (D4D_OBJECT_PTR pObj)
The function gets the scroll bar position.
void D4D_ScrlBrChangePosition (D4D_OBJECT_PTR pObj, D4D_INDEX_DELTA change)
The function change the scroll bar position.
Variables
const D4D_OBJECT_SYS_FUNCTION d4d_scroll_barSysFunc
Detailed Description
D4D driver scroll_bar object c file.
Author
Petr Gargulak
Version
0.0.21.0
Date
Jan-14-2014
Definition in file d4d_scroll_bar.c.
Macro Definition Documentation
#define _calc
Definition at line 80 of file d4d_scroll_bar.c.
Referenced by D4D_ScrlBrOnDraw(), and D4D_ScrlBrValue2Coor().
Function Documentation
void D4D_ScrlBrDrawArrow (D4D_POINT * ppt, D4D_COOR size, D4D_DIRECTION dir, D4D_COLOR color) static
THE INTERNAL HELP FUNCTIONS
Definition at line 241 of file d4d_scroll_bar.c.
References D4D_DIR_DOWN, D4D_DIR_LEFT, D4D_DIR_RIGHT, D4D_FALSE, D4D_LINE_THIN, D4D_LineTo(), D4D_MoveTo(), D4D_PutPixel(), D4D_SwapCoor(), D4D_TRUE, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_ScrlBrOnDraw().
static void D4D_ScrlBrOnDraw (D4D_MESSAGE * pMsg) static
Definition at line 162 of file d4d_scroll_bar.c.
References _calc, D4D_SIZE::cx, D4D_SIZE::cy, D4D_DIR_DOWN, D4D_DIR_LEFT, D4D_DIR_RIGHT, D4D_DIR_UP, D4D_DrawFrame(), D4D_FillRect(), D4D_FillRRect(), D4D_LINE_THIN, D4D_OBJECT_DRAWFLAGS_COMPLETE, D4D_OBJECT_DRAWFLAGS_STATE, D4D_ObjectGetBckgColor(), D4D_ObjectGetForeColor(), D4D_RRect(), D4D_ScrlBrDrawArrow(), D4D_ScrlBrValue2Coor(), D4D_MESSAGE_S::draw, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_OBJECT_S::radius, D4D_OBJECT_S::size, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_ScrlBrOnMessage().
static void D4D_ScrlBrOnKeyDown (D4D_MESSAGE * pMsg) static
Definition at line 330 of file d4d_scroll_bar.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_GET_SCROLL_BAR, D4D_KEY_SCANCODE_DOWN, D4D_KEY_SCANCODE_LEFT, D4D_KEY_SCANCODE_RIGHT, D4D_KEY_SCANCODE_UP, D4D_ScrlBrChangePosition(), D4D_MESSAGE_S::key, D4D_SCROLL_BAR::pData, D4D_MESSAGE_S::pObject, D4D_MESSAGE_S::prm, D4D_OBJECT_S::size, and D4D_SCRLBAR_DATA_S::step.
Referenced by D4D_ScrlBrOnMessage().
void D4D_ScrlBrOnMessage (D4D_MESSAGE * pMsg) static
THE INTERNAL API FUNCTIONS
Definition at line 506 of file d4d_scroll_bar.c.
References D4D_CaptureKeys(), D4D_FALSE, D4D_GetMouseCoordinates, D4D_GetTouchScreenCoordinates(), D4D_InvalidateObject(), D4D_MSG_DRAW, D4D_MSG_KEYDOWN, D4D_MSG_KILLCAPTURE, D4D_MSG_KILLFOCUS, D4D_MSG_MOUSE_BTN_LEFT_UP, D4D_MSG_MOUSE_BTN_WHEEL_DOWN, D4D_MSG_MOUSE_BTN_WHEEL_UP, D4D_MSG_SETCAPTURE, D4D_MSG_SETFOCUS, D4D_MSG_TOUCH_AUTO, D4D_MSG_TOUCHED, D4D_ObjOnMessage(), D4D_ScrlBrChangePosition(), D4D_ScrlBrOnDraw(), D4D_ScrlBrOnKeyDown(), D4D_MESSAGE_S::nMsgId, NULL, and D4D_MESSAGE_S::pObject.
static void D4D_ScrlBrValue2Coor (D4D_OBJECT * pThis) static
Definition at line 83 of file d4d_scroll_bar.c.
References _calc, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ComputeGeometry(), D4D_GET_SCROLL_BAR, D4D_GetClientToScreenPoint(), D4D_MulDivUU16(), D4D_SCRLBAR_MIN_TAB_SIZE, D4D_SCRLBAR_DATA_S::maximum, D4D_SCRLBAR_DATA_S::minimum, D4D_SCRLBAR_DATA_S::page, D4D_SCROLL_BAR::pData, D4D_SCRLBAR_DATA_S::position, D4D_OBJECT_S::position, D4D_OBJECT_S::radius, and D4D_OBJECT_S::size.
Referenced by D4D_ScrlBrOnDraw().
Variable Documentation
const D4D_OBJECT_SYS_FUNCTION d4d_scroll_barSysFunc
Definition at line 61 of file d4d_scroll_bar.c.