Freescale's eGUI: D4D SCHEME API Functions Specification
D4D SCHEME API Functions Specification
D4D SCHEME Handler
Functions
D4D_CLR_SCHEME * D4D_ObjectGetScheme (D4D_OBJECT *pObj)
Function return the pointer to current use object scheme of object.
D4D_CLR_SCHEME * D4D_GetDefaultScheme (void)
Function return the pointer to default color scheme.
void D4D_SetDefaultScheme (D4D_CLR_SCHEME *pScheme)
Function sets the new default color scheme.
D4D_COLOR D4D_ObjectGetForeColor (D4D_OBJECT *pObj, D4D_OBJECT_DRAWFLAGS draw)
Function return object current fore color.
D4D_COLOR D4D_ObjectGetBckgColor (D4D_OBJECT *pObj, D4D_OBJECT_DRAWFLAGS draw)
Function return object current background color.
D4D_COLOR D4D_ObjectGetForeFillColor (D4D_OBJECT *pObj)
Function return object current fill fore color.
D4D_COLOR D4D_ObjectGetBckgFillColor (D4D_OBJECT *pObj)
Function return object current fill background color.
D4D_COLOR D4D_GetCrossColor (D4D_COLOR startColor, D4D_COLOR endColor, Byte value)
Compute cross color between two basic color in 256 steps.
D4D_COLOR D4D_ChangeColorIntesity (D4D_COLOR color, sByte intensity)
Compute change of color intesity.
D4D_COLOR D4D_GetGreyScale (D4D_COLOR color)
Compute the grayscale color.
Detailed Description
This section specifies the exact usage for each API function.
Function Documentation
D4D_COLOR D4D_ChangeColorIntesity (D4D_COLOR color, sByte intensity)
Compute change of color intesity.
Parameters
color - input color to change intesity
intensity - change of intesity - signed <-100 .. 100>
Returns
New color computed from input color and intensity change.
Note
Function compute by simple proportion the color with changed intesity in +-100% scale.
Definition at line 286 of file d4d_scheme.c.
References D4D_Abs(), D4D_COLOR_GET_B, D4D_COLOR_GET_G, D4D_COLOR_GET_R, D4D_COLOR_RGB, and D4D_MulDivUU8().
Referenced by D4D_Bevel(), and D4D_GroupBoxOnDraw().
D4D_COLOR D4D_GetCrossColor (D4D_COLOR startColor, D4D_COLOR endColor, Byte value)
Compute cross color between two basic color in 256 steps.
Parameters
startColor - starting color for computing cross color
endColor - ending color for computing cross color
value - crossing value <0-255>
Returns
Crrossing color between begin and end color handled in parameters by handled step(value).
Note
Function compute by simple proportion the cross color between two colors by handled step.
Definition at line 243 of file d4d_scheme.c.
References D4D_COLOR_GET_B, D4D_COLOR_GET_G, D4D_COLOR_GET_R, D4D_COLOR_RGB, and D4D_MulDivUU8().
Referenced by D4D_FillRectColorScaleXY(), D4D_FillRRectColorScaleXY(), D4D_PrgrsBarComputeColorBar(), and D4D_SldrComputeColorBar().
D4D_CLR_SCHEME* D4D_GetDefaultScheme (void)
Function return the pointer to default color scheme.
Returns
pointer to screen current use of color scheme
Note
This function just return current used default color scheme pointer
Definition at line 133 of file d4d_scheme.c.
D4D_COLOR D4D_GetGreyScale (D4D_COLOR color)
Compute the grayscale color.
Parameters
color - input color to change to grey scale
Returns
New grey scale color computed from input color
Note
Function compute the grey scale color from input color.
Definition at line 333 of file d4d_scheme.c.
References D4D_COLOR_GET_B, D4D_COLOR_GET_G, D4D_COLOR_GET_R, and D4D_COLOR_RGB.
Referenced by D4D_DrawScreenNC(), D4D_GaugOnDraw(), D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), D4D_PrgrsBarOnDraw(), D4D_PrintPixel(), and D4D_SldrOnDraw().
D4D_COLOR D4D_ObjectGetBckgColor (D4D_OBJECT * pObj, D4D_OBJECT_DRAWFLAGS draw)
Function return object current background color.
Parameters
pObj - pointer to object
draw - draw runtime flags handled to object by D4D_MSG_ONDRAW
Returns
Current used background color of object.
Note
Function by object flags and also draw parameter return one of object color from color scheme - normal/disable/focus/capture colors.
Definition at line 185 of file d4d_scheme.c.
References D4D_CLR_SCHEME_S::bckg, D4D_CLR_SCHEME_S::bckgCapture, D4D_CLR_SCHEME_S::bckgDis, D4D_CLR_SCHEME_S::bckgFocus, D4D_IsEnabled(), D4D_OBJECT_DRAWFLAGS_CAPTURING, D4D_OBJECT_DRAWFLAGS_FOCUSED, and D4D_ObjectGetScheme().
Referenced by D4D_BtnOnDraw(), D4D_CheckBoxOnDraw(), D4D_ComboBoxButtonMsgFeedBack(), D4D_IconOnDraw(), D4D_LabelOnDraw(), D4D_RadioButtonOnDraw(), D4D_ScrlBrOnDraw(), and D4D_SldrOnDraw().
D4D_COLOR D4D_ObjectGetBckgFillColor (D4D_OBJECT * pObj)
Function return object current fill background color.
Parameters
pObj - pointer to object
Returns
Current used fill background color of object.
Note
Function by object flags return one of object color from color scheme - normal/disable colors.
Definition at line 225 of file d4d_scheme.c.
References D4D_CLR_SCHEME_S::bckg, D4D_CLR_SCHEME_S::bckgDis, D4D_IsEnabled(), and D4D_ObjectGetScheme().
Referenced by D4D_CheckBoxOnDraw(), D4D_ConsoleOnDraw(), D4D_GaugOnDraw(), D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), D4D_GraphPrintLabel(), D4D_GroupBoxOnDraw(), D4D_ListBoxOnDraw(), D4D_MenuOnDraw(), D4D_PictOnDraw(), D4D_PrgrsBarOnDraw(), D4D_RadioButtonOnDraw(), D4D_SldrOnDraw(), and D4D_TextBoxOnDraw().
D4D_COLOR D4D_ObjectGetForeColor (D4D_OBJECT * pObj, D4D_OBJECT_DRAWFLAGS draw)
Function return object current fore color.
Parameters
pObj - pointer to object
draw - draw runtime flags handled to object by D4D_MSG_ONDRAW
Returns
Current used fore color of object.
Note
Function by object flags and also draw parameter return one of object color from color scheme - normal/disable/focus/capture colors.
Definition at line 161 of file d4d_scheme.c.
References D4D_IsEnabled(), D4D_OBJECT_DRAWFLAGS_CAPTURING, D4D_OBJECT_DRAWFLAGS_FOCUSED, D4D_ObjectGetScheme(), D4D_CLR_SCHEME_S::fore, D4D_CLR_SCHEME_S::foreCapture, D4D_CLR_SCHEME_S::foreDis, and D4D_CLR_SCHEME_S::foreFocus.
Referenced by D4D_BtnOnDraw(), D4D_CheckBoxOnDraw(), D4D_ComboBoxButtonMsgFeedBack(), D4D_EditBoxOnDraw(), D4D_GaugOnDraw(), D4D_GraphOnDraw(), D4D_GroupBoxOnDraw(), D4D_IconOnDraw(), D4D_LabelOnDraw(), D4D_ListBoxOnDraw(), D4D_PictOnDraw(), D4D_PrgrsBarOnDraw(), D4D_RadioButtonOnDraw(), D4D_ScrlBrOnDraw(), and D4D_SldrOnDraw().
D4D_COLOR D4D_ObjectGetForeFillColor (D4D_OBJECT * pObj)
Function return object current fill fore color.
Parameters
pObj - pointer to object
Returns
Current used fill fore color of object.
Note
Function by object flags return one of object color from color scheme - normal/disable colors.
Definition at line 208 of file d4d_scheme.c.
References D4D_IsEnabled(), D4D_ObjectGetScheme(), D4D_CLR_SCHEME_S::fore, and D4D_CLR_SCHEME_S::foreDis.
Referenced by D4D_ConsoleOnDraw(), D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), D4D_GraphPrintLabel(), D4D_ListBoxOnDraw(), D4D_MenuOnDraw(), and D4D_TextBoxOnDraw().
D4D_CLR_SCHEME* D4D_ObjectGetScheme (D4D_OBJECT * pObj)
Function return the pointer to current use object scheme of object.
Parameters
pObj - pointer to object
Returns
pointer to object current use of color scheme
Note
This function find out the current use object scheme of object. It handles with standard default scheme, screen color scheme and also directly with user object color scheme.
Definition at line 109 of file d4d_scheme.c.
References D4D_OBJECT_S::clrScheme, D4D_GetParentObject(), D4D_ObjectGetScheme(), D4D_ScreenGetScheme(), NULL, D4D_OBJECT_S::pData, D4D_OBJECT_S::pRelations, and D4D_OBJECT_DATA_S::pScreen.
Referenced by D4D_CheckBoxOnDraw(), D4D_EditBoxOnDraw(), D4D_GaugOnDraw(), D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), D4D_ListBoxOnDraw(), D4D_MenuOnDraw(), D4D_ObjectGetBckgColor(), D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetForeFillColor(), D4D_ObjectGetScheme(), D4D_PrgrsBarComputeColorBar(), D4D_PrgrsBarOnDraw(), D4D_PrgrsBarOnMessage(), D4D_RadioButtonOnDraw(), D4D_SldrComputeColorBar(), D4D_SldrOnDraw(), and D4D_SldrOnMessage().
void D4D_SetDefaultScheme (D4D_CLR_SCHEME * pScheme)
Function sets the new default color scheme.
Parameters
pScheme - pointer to object
Returns
none
Note
This function sets the new default color scheme. If by parameter is handled NULL, then it's used default color scheme defined in d4d_usrcfg.h file.
Definition at line 145 of file d4d_scheme.c.
References NULL.