Freescale's eGUI: D4D SLIDER API Functions Specification
D4D SLIDER API Functions Specification
D4D Slider Widget
Functions
void D4D_SldrSetValue (D4D_OBJECT_PTR pThis, D4D_SLIDER_VALUE value)
Function Sets the slider value.
D4D_SLIDER_VALUE D4D_SldrGetValue (D4D_OBJECT_PTR pThis)
Function Gets the slider value.
void D4D_SldrSetBarColor (D4D_OBJECT_PTR pThis, D4D_COLOR color)
Function Sets the slider bar color.
D4D_COLOR D4D_SldrGetBarColor (D4D_OBJECT_PTR pThis)
void D4D_SldrChangeValue (D4D_OBJECT_PTR pThis, D4D_SLIDER_VALUE incr)
Function change the slider value by signed increment.
void D4D_SldrSetLimits (D4D_OBJECT_PTR pThis, const D4D_SLIDER_LIMITS *pLimits)
Function set the new limits of slider object.
void D4D_SldrGetLimits (D4D_OBJECT_PTR pThis, D4D_SLIDER_LIMITS *pLimits)
Function get the current limits of slider object.
Detailed Description
This section specifies the exact usage for each API function.
Function Documentation
void D4D_SldrChangeValue (D4D_OBJECT_PTR pThis, D4D_SLIDER_VALUE incr)
Function change the slider value by signed increment.
Parameters
pThis - pointer to the slider object
incr - signed increment value
Returns
none
Note
none
Definition at line 567 of file d4d_slider.c.
References D4D_GET_SLIDER, D4D_LimitS8(), and D4D_SldrSetValue().
Referenced by D4D_SldrOnKeyUp(), and D4D_SldrOnMessage().
D4D_COLOR D4D_SldrGetBarColor (D4D_OBJECT_PTR pThis)
Definition at line 553 of file d4d_slider.c.
References D4D_SLIDER_DATA::colorBar, D4D_GET_SLIDER, and D4D_SLIDER::pData.
void D4D_SldrGetLimits (D4D_OBJECT_PTR pThis, D4D_SLIDER_LIMITS * pLimits)
Function get the current limits of slider object.
Parameters
pThis - pointer to the slider object
pLimits - pointer to limits structure where will be copied current values what slider is using
Returns
none
Note
none
Definition at line 604 of file d4d_slider.c.
References D4D_GET_SLIDER, D4D_SLIDER_DATA::limits, and D4D_SLIDER::pData.
D4D_SLIDER_VALUE D4D_SldrGetValue (D4D_OBJECT_PTR pThis)
Function Gets the slider value.
Parameters
pThis - pointer to the slider object
Returns
value of slider.
Note
none
Definition at line 523 of file d4d_slider.c.
References D4D_GET_SLIDER, D4D_SLIDER::pData, and D4D_SLIDER_DATA::value.
void D4D_SldrSetBarColor (D4D_OBJECT_PTR pThis, D4D_COLOR color)
Function Sets the slider bar color.
Parameters
pThis - pointer to the slider object
color - new slider bar color
Returns
none
Note
none
Definition at line 536 of file d4d_slider.c.
References D4D_SLIDER_DATA::colorBar, D4D_FALSE, D4D_GET_SLIDER, D4D_InvalidateObject(), D4D_SLDR_F_BAR_AUTOCOLOR, D4D_SLDR_F_BAR_SCALECOLOR, D4D_OBJECT_S::initFlags, and D4D_SLIDER::pData.
void D4D_SldrSetLimits (D4D_OBJECT_PTR pThis, const D4D_SLIDER_LIMITS * pLimits)
Function set the new limits of slider object.
Parameters
pThis - pointer to the slider object
pLimits - pointer to new limits structure
Returns
none
Note
none
Definition at line 584 of file d4d_slider.c.
References D4D_GET_SLIDER, D4D_SldrSetValue(), D4D_SLIDER_DATA::limits, D4D_SLIDER::pData, D4D_SLIDER_DATA::value, D4D_SLIDER_LIMITS::valueMax, D4D_SLIDER_LIMITS::valueMin, and D4D_SLIDER_LIMITS::valueOrg.
void D4D_SldrSetValue (D4D_OBJECT_PTR pThis, D4D_SLIDER_VALUE value)
Function Sets the slider value.
Parameters
pThis - pointer to the slider object
value - new value of slider
Returns
none.
Note
The values must fit in to slider linits, if not is limit to valid range
Definition at line 492 of file d4d_slider.c.
References D4D_SLIDER_DATA::colorBar, D4D_FALSE, D4D_GET_SLIDER, D4D_InvalidateObject(), D4D_LimitS8(), D4D_SLDR_F_BAR_AUTOCOLOR, D4D_SLDR_F_BAR_SCALECOLOR, D4D_SldrComputeColorBar(), D4D_OBJECT_S::initFlags, D4D_SLIDER_DATA::limits, D4D_SLIDER::OnValueChanged, D4D_SLIDER::pData, D4D_SLIDER_DATA::value, D4D_SLIDER_LIMITS::valueMax, and D4D_SLIDER_LIMITS::valueMin.
Referenced by D4D_SldrChangeValue(), and D4D_SldrSetLimits().