Freescale's eGUI: D4D EDIT BOX API Functions Specification
D4D EDIT BOX API Functions Specification
D4D Edit Box Widget
Functions
D4D_BOOL D4D_EditBoxPutChar (D4D_OBJECT_PTR pObj, D4D_TCHAR ch)
The function puts one char on cursor position and updates cursor.
D4D_BOOL D4D_EditBoxPutString (D4D_OBJECT_PTR pObj, D4D_TCHAR *pText)
The function puts string on cursor position and updates cursor.
D4D_INDEX D4D_EditBoxSetCursor (D4D_OBJECT_PTR pObj, D4D_INDEX newPos)
The function chenge the cursor position to new one.
D4D_INDEX D4D_EditBoxGetCursor (D4D_OBJECT_PTR pObj)
The function returns the cursor position.
void D4D_EditBoxClearAll (D4D_OBJECT_PTR pObj)
The function clear whole edit box data.
D4D_TCHAR * D4D_EditBoxGetText (D4D_OBJECT_PTR pObj)
The function returns the pointer to the edit box text buffer.
Detailed Description
This section specifies the exact usage for each API function.
Function Documentation
void D4D_EditBoxClearAll (D4D_OBJECT_PTR pObj)
The function clear whole edit box data.
Parameters
pObj - pointer to the edit box object
Returns
none
Note
none
Definition at line 621 of file d4d_edit_box.c.
References D4D_STRING_S::buffSize, D4D_EDIT_BOX_DATA::curPos, D4D_EDIT_BOX_FLAGS_CHANGETEXT, D4D_EDIT_BOX_FLAGS_FULL, D4D_EDIT_BOX_FLAGS_REDRAWCURSOR, D4D_EDIT_BOX_FLAGS_REDRAWTEXT, D4D_EVENT_ONCLEAR, D4D_FALSE, D4D_GET_EDIT_BOX, D4D_InvalidateObject(), D4D_EDIT_BOX_DATA::flags, D4D_EDIT_BOX::pData, D4D_EDIT_BOX::pOnEvent, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_STRING_S::pText, and D4D_EDIT_BOX_DATA::string.
Referenced by D4D_ComboBoxListFeedBack(), and D4D_ComboBoxOnMessage().
D4D_INDEX D4D_EditBoxGetCursor (D4D_OBJECT_PTR pObj)
The function returns the cursor position.
Parameters
pObj - pointer to the edit box object
Returns
the position of cursor
Note
none
Definition at line 604 of file d4d_edit_box.c.
References D4D_EDIT_BOX_DATA::curPos, D4D_GET_EDIT_BOX, NULL, and D4D_EDIT_BOX::pData.
D4D_TCHAR* D4D_EditBoxGetText (D4D_OBJECT_PTR pObj)
The function returns the pointer to the edit box text buffer.
Parameters
pObj - pointer to the edit box object
Returns
pointer to edit box text
Note
none
Definition at line 652 of file d4d_edit_box.c.
References D4D_GET_EDIT_BOX, D4D_EDIT_BOX::pData, D4D_STRING_S::pText, and D4D_EDIT_BOX_DATA::string.
Referenced by D4D_ComboBoxEditFeedBack().
D4D_BOOL D4D_EditBoxPutChar (D4D_OBJECT_PTR pObj, D4D_TCHAR ch)
The function puts one char on cursor position and updates cursor.
Parameters
pObj - pointer to the edit box object
ch - char that will be puts on edit box
Returns
D4D_TRUE - character has been add / D4D_FALSE - character hasn't been add
Note
The result returns if the character was add or not (non printed characters, max count of characters achived).
Definition at line 393 of file d4d_edit_box.c.
References D4D_EDIT_BOX_DATA::curPos, D4D_SIZE::cx, D4D_EDIT_BOX_FLAGS_CHANGETEXT, D4D_EDIT_BOX_FLAGS_REDRAWCURSOR, D4D_EDIT_BOX_FLAGS_REDRAWTEXT, D4D_EditBoxPutCharInt(), D4D_EditBoxSetCursor(), D4D_EVENT_ONCHANGE, D4D_FALSE, D4D_GET_EDIT_BOX, D4D_GetTextMaxLength(), D4D_InvalidateObject(), D4D_TRUE, D4D_EDIT_BOX_DATA::flags, D4D_MARGIN::left, D4D_EDIT_BOX::pData, D4D_OBJECT_S::pMargin, D4D_EDIT_BOX::pOnEvent, D4D_STRING_S::printLen, D4D_STRING_S::pText, D4D_MARGIN::right, D4D_OBJECT_S::size, and D4D_EDIT_BOX_DATA::string.
Referenced by D4D_EditBoxOnKeyUp(), and D4D_EditBoxPutString().
D4D_BOOL D4D_EditBoxPutString (D4D_OBJECT_PTR pObj, D4D_TCHAR * pText)
The function puts string on cursor position and updates cursor.
Parameters
pObj - pointer to the edit box object
pText - pointer to string that should be added
Returns
D4D_TRUE - string has been completely add / D4D_FALSE - string hasn't ben complete add
Note
The result returns if the string was add or not (non printed characters, max count of characters achived).
Definition at line 455 of file d4d_edit_box.c.
References D4D_EDIT_BOX_FLAGS_CHANGETEXT, D4D_EditBoxPutChar(), D4D_EVENT_ONCHANGEDONE, D4D_FALSE, D4D_GET_EDIT_BOX, D4D_GetActiveScreen(), D4D_GetFocusedObject(), D4D_GetInternalStringPointer(), D4D_TRUE, D4D_EDIT_BOX_DATA::flags, NULL, D4D_EDIT_BOX::pData, and D4D_EDIT_BOX::pOnEvent.
Referenced by D4D_ComboBoxListFeedBack(), and D4D_ComboBoxOnMessage().
D4D_INDEX D4D_EditBoxSetCursor (D4D_OBJECT_PTR pObj, D4D_INDEX newPos)
The function chenge the cursor position to new one.
Parameters
pObj - pointer to the edit box object
newPos - new position index
Returns
the real position of cursor after this operation
Note
The real position could be different to request one in case the the limits are exceed.
Definition at line 490 of file d4d_edit_box.c.
References D4D_STRING_S::buffSize, D4D_EDIT_BOX_DATA::curPos, D4D_SIZE::cx, D4D_EDIT_BOX_FLAGS_FULL, D4D_EDIT_BOX_FLAGS_MOVECURSOR, D4D_EDIT_BOX_FLAGS_REDRAWCURSOR, D4D_EDIT_BOX_FLAGS_REDRAWTEXT, D4D_FALSE, D4D_GET_EDIT_BOX, D4D_GetCharWidth(), D4D_GetTextBuffWidthTab(), D4D_GetTextMaxLength(), D4D_InvalidateObject(), D4D_EDIT_BOX_DATA::flags, D4D_STRING_S::fontId, D4D_MARGIN::left, NULL, D4D_EDIT_BOX::pData, D4D_OBJECT_S::pMargin, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_STRING_S::pText, D4D_MARGIN::right, D4D_OBJECT_S::size, and D4D_EDIT_BOX_DATA::string.
Referenced by D4D_EditBoxOnInit(), D4D_EditBoxOnKeyUp(), D4D_EditBoxPutChar(), and D4D_EditBoxPutCharInt().