Freescale's eGUI: D4D OBJECT API Functions Specification
D4D OBJECT API Functions Specification
D4D OBJECT Handler
Functions
void D4D_InvalidateObject (D4D_OBJECT_PTR pObject, D4D_BOOL bComplete)
Function invalidate object to redraw on screen.
void D4D_ShowObject (D4D_OBJECT_PTR pObject, D4D_BOOL bShow)
Function control visibility of object on screen.
void * D4D_GetUserPointer (D4D_OBJECT *pThis)
Function return the object user data.
void D4D_EnableTouchScreen (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable, D4D_BOOL bFastTouch)
Function enables touchs screen capability and sets also mode of touch event.
void D4D_EnableTimeTicks (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable)
Function enable or diasble receiving timeticks for an OBJECT.
void D4D_CaptureKeys (D4D_OBJECT_PTR pObj)
Function switch on capturing the keys to objects.
D4D_OBJECT * D4D_GetCapturedObject (void)
Function returns the current keys capturing object pointer.
void D4D_EnableTabStop (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable)
Function enables TabStop on the object.
void D4D_EnableObject (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable)
Function enables object.
D4D_BOOL D4D_IsEnabled (D4D_OBJECT *pObject)
Function find out if the object is enabled or not.
D4D_BOOL D4D_IsVisible (D4D_OBJECT *pObject)
Function find out if the object is visible or not.
D4D_BOOL D4D_IsMineFocus (D4D_OBJECT *pObject)
Function find out if the object (including compounded objects) is focused.
D4D_SIZE D4D_GetClientScreenSize (D4D_OBJECT *pObject)
The function return the real client size of object.
Detailed Description
This section specifies the exact usage for each API function.
Global variables
Function Documentation
void D4D_CaptureKeys (D4D_OBJECT_PTR pObj)
Function switch on capturing the keys to objects.
Parameters
pObj - pointer to the object. if the parameter is handled as NULL, the function switch off the capturing the keys to object.
Returns
none.
Note
This function sets the object to the capture keys state. In this state the object obtains all the keys inputs including system navigation keys (escape, up, and down). In this state the object is using capture colors from a color scheme. To switch off from this state the active screen has to be changed or this function has to be called with the input parameter set to NULL.
Definition at line 190 of file d4d_object.c.
References D4D_FALSE, D4D_FocusSet(), D4D_GetActiveScreen(), D4D_IsEnabled(), D4D_MSG_KILLCAPTURE, D4D_MSG_SETCAPTURE, D4D_OBJECT_F_ENABLED, D4D_OBJECT_F_REDRAWSTATE, D4D_OBJECT_F_TABSTOP, D4D_OBJECT_F_VISIBLE, d4d_pKeysCapturer, d4d_scratchPad, D4D_SendMessage(), D4D_SetObjectFlags(), D4D_OBJECT_DATA_S::flags, D4D_MESSAGE_S::nMsgId, NULL, D4D_OBJECT_S::pData, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_ActivateScreen(), D4D_ComboBoxButtonFeedBack(), D4D_ConsoleOnMessage(), D4D_EditBoxOnKeyUp(), D4D_EditBoxOnMessage(), D4D_EnableObject(), D4D_EscapeScreen(), D4D_EscapeToBaseScreen(), D4D_ListBoxOnKeyUp(), D4D_MenuOnKeyUp(), D4D_ScrlBrOnMessage(), D4D_ShowObject(), D4D_SldrOnKeyUp(), D4D_SldrOnMessage(), and D4D_TextBoxOnMessage().
void D4D_EnableObject (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable)
Function enables object.
Parameters
pObj - pointer to the object
bEnable - <D4D_TRUE - object enabled, D4D_FALSE - enabled disabled>
Returns
none.
Note
This function sets the enabled property. When the object is enabled, it can accept all user inputs and use normal colors. In the disable state the object is redrawn by grayscale colors and all user inputs are ignored. The initialization state is set by parameter flags in the object declaration. This function is targeted for using at run-time.
Definition at line 273 of file d4d_object.c.
References D4D_CaptureKeys(), D4D_FALSE, D4D_FocusNextObject(), D4D_GetFocusedObject(), D4D_InvalidateObject(), D4D_LOG_EXOR, D4D_OBJECT_F_ENABLED, d4d_pKeysCapturer, D4D_TRUE, D4D_OBJECT_DATA_S::flags, NULL, D4D_OBJECT_S::pData, and D4D_OBJECT_DATA_S::pScreen.
void D4D_EnableTabStop (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable)
Function enables TabStop on the object.
Parameters
pObj - pointer to the object
bEnable - <D4D_TRUE - tabStop enabled, D4D_FALSE - tabStop disabled>
Returns
none.
Note
This function sets the tab stop property. When the tab stop is enabled, the object can be focused. The initialization state is set by the parameter flags in the object declaration. This function is targeted at using for run-time.
Definition at line 255 of file d4d_object.c.
References D4D_OBJECT_F_TABSTOP, D4D_OBJECT_DATA_S::flags, and D4D_OBJECT_S::pData.
void D4D_EnableTimeTicks (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable)
Function enable or diasble receiving timeticks for an OBJECT.
Parameters
pObj - pointer to the object.
bEnable - <D4D_TRUE - object will receive periodic time ticks events, D4D_FALSE - object won't receive the time ticks events>
Returns
none.
Note
This function enables gettings the time tick events to object.
Definition at line 172 of file d4d_object.c.
References D4D_OBJECT_F_TIMETICK, D4D_OBJECT_DATA_S::flags, and D4D_OBJECT_S::pData.
Referenced by D4D_EditBoxOnMessage(), D4D_IconAnimationStart(), and D4D_IconAnimationStop().
void D4D_EnableTouchScreen (D4D_OBJECT_PTR pObj, D4D_BOOL bEnable, D4D_BOOL bFastTouch)
Function enables touchs screen capability and sets also mode of touch event.
Parameters
pObj - pointer to the object.
bEnable - <D4D_TRUE - touch event enabled, D4D_FALSE - touch event disabled>
bFastTouch - <D4D_TRUE - fast touch mode, D4D_FALSE -standard touch event>
Returns
none.
Note
This function enables touch event for the object and also sets the mode of touch event:
standard mode and fast touch mode. For example for object button the first touch just focused the obejct and second one do click action.
fast touch mode - do both actions at once (more user friendly for touch control).
Definition at line 151 of file d4d_object.c.
References D4D_OBJECT_F_FASTTOUCH, D4D_OBJECT_F_TOUCHENABLE, D4D_OBJECT_DATA_S::flags, and D4D_OBJECT_S::pData.
D4D_OBJECT* D4D_GetCapturedObject (void)
Function returns the current keys capturing object pointer.
Returns
Pointer to object that is capturing keys or NULL if no object is capturing keys.
Note
This function returns the pointer to the current object and sets it as a capture keys object. If neither object is set as capture keys, the function returns NULL..
Definition at line 241 of file d4d_object.c.
References d4d_pKeysCapturer.
Referenced by D4D_EditBoxOnKeyUp(), D4D_ListBoxOnKeyUp(), D4D_MenuOnKeyDown(), D4D_MenuOnKeyUp(), and D4D_SldrOnKeyUp().
D4D_SIZE D4D_GetClientScreenSize (D4D_OBJECT * pObject)
The function return the real client size of object.
Parameters
pObject - the pointer to object
Returns
client area object size
Note
The function already handles also the compounded objects.
Definition at line 382 of file d4d_object.c.
References D4D_MARGIN::bottom, D4D_SIZE::cx, D4D_SIZE::cy, D4D_BEVEL_WIDTH, D4D_GetScrHeaderSize(), D4D_OBJECT_USR_DATA_PARENT_IX, D4D_SCR_F_BEVEL, D4D_SCR_F_OUTLINE, D4D_SCREEN_S::flags, D4D_MARGIN::left, NULL, D4D_OBJECT_S::pData, D4D_OBJECT_S::pMargin, D4D_OBJECT_S::pRelations, D4D_OBJECT_DATA_S::pScreen, D4D_MARGIN::right, D4D_OBJECT_S::size, D4D_SCREEN_S::size, and D4D_MARGIN::top.
void* D4D_GetUserPointer (D4D_OBJECT * pThis)
Function return the object user data.
Parameters
pThis - pointer to the object.
Returns
User data of object.
Note
Each object has user data that could be used what ever user needs and this function returns it.
Definition at line 131 of file d4d_object.c.
References NULL, and D4D_OBJECT_S::userData.
void D4D_InvalidateObject (D4D_OBJECT_PTR pObject, D4D_BOOL bComplete)
Function invalidate object to redraw on screen.
Parameters
pObject - pointer to the object that should be invalidate.
bComplete - force complete redraw of object.
Returns
none.
Note
This function invalidate object what in fact is that force eGUI to redraw object on screen. By the bComplete parameter is select that will be redraw also static parts of object.
Definition at line 71 of file d4d_object.c.
References D4D_OBJECT_F_REDRAW, D4D_OBJECT_F_REDRAWC, D4D_SCR_FINT_CHECKOBJECTS, D4D_SetObjectFlags(), D4D_TRUE, D4D_OBJECT_S::pData, and D4D_OBJECT_DATA_S::pScreen.
Referenced by D4D_BtnKillFocus(), D4D_BtnOnKeyDown(), D4D_BtnOnKeyUp(), D4D_BtnOnMessage(), D4D_CheckBoxOnKeyDown(), D4D_CheckBoxOnKeyUp(), D4D_CheckBoxSetValue(), D4D_CnslClearAll(), D4D_CnslPutChar(), D4D_CnslScrollBarsFeedBack(), D4D_ComboBoxButtonFeedBack(), D4D_ConsoleOnMessage(), D4D_ConsoleTimeTick(), D4D_EditBoxClearAll(), D4D_EditBoxOnInit(), D4D_EditBoxOnMessage(), D4D_EditBoxPutChar(), D4D_EditBoxSetCursor(), D4D_EditBoxTimeTick(), D4D_EnableObject(), D4D_GaugSetDir(), D4D_GaugSetLimits(), D4D_GaugSetValue(), D4D_GraphAddTraceData(), D4D_GraphAddTracesData(), D4D_GraphClearAll(), D4D_GraphSetDataWidth(), D4D_GraphSetScaleX(), D4D_IconSetIndex(), D4D_ListBoxFocusNextItem(), D4D_ListBoxFocusPreviousItem(), D4D_ListBoxOnInit(), D4D_ListBoxScrollBarsFeedBack(), D4D_ListBoxSetIndex(), D4D_MenuOnInit(), D4D_MenuOnKeyDown(), D4D_MenuOnKeyUp(), D4D_MenuScrollBarsFeedBack(), D4D_PrgrsBarSetBarColor(), D4D_PrgrsBarSetValue(), D4D_RadioButtonOnKeyDown(), D4D_RadioButtonOnKeyUp(), D4D_RadioButtonSetValue(), D4D_ScrlBrOnMessage(), D4D_ScrlBrSetPosition(), D4D_ScrlBrSetRange(), D4D_ScrlBrSetStep(), D4D_SetFontProperties(), D4D_SetText(), D4D_SetTextProperties(), D4D_ShowObject(), D4D_SldrSetBarColor(), D4D_SldrSetValue(), D4D_TextBoxOnInit(), and D4D_TextBoxScrollBarsFeedBack().
D4D_BOOL D4D_IsEnabled (D4D_OBJECT * pObject)
Function find out if the object is enabled or not.
Parameters
pObject - pointer to the object
Returns
<D4D_TRUE - object is enabled, D4D_FALSE - object is disabled>.
Note
This function gets the current status of object enabled / disabled. The function control the object itself and also all parents objects..
Definition at line 303 of file d4d_object.c.
References D4D_FALSE, D4D_GetParentObject(), D4D_IsEnabled(), D4D_OBJECT_F_ENABLED, D4D_TRUE, D4D_OBJECT_DATA_S::flags, D4D_OBJECT_S::pData, and D4D_OBJECT_S::pRelations.
Referenced by D4D_BtnOnDraw(), D4D_CaptureKeys(), D4D_CheckBoxOnDraw(), D4D_FocusSet(), D4D_GaugOnDraw(), D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), D4D_HandleKeys(), D4D_IconOnDraw(), D4D_IsEnabled(), D4D_ListBoxOnDraw(), D4D_MenuOnDraw(), D4D_ObjectGetBckgColor(), D4D_ObjectGetBckgFillColor(), D4D_ObjectGetForeColor(), D4D_ObjectGetForeFillColor(), D4D_PictOnDraw(), D4D_PrgrsBarOnDraw(), D4D_RadioButtonOnDraw(), and D4D_SldrOnDraw().
D4D_BOOL D4D_IsMineFocus (D4D_OBJECT * pObject)
Function find out if the object (including compounded objects) is focused.
Parameters
pObject - pointer to the object
Returns
<D4D_TRUE - object has focus, D4D_FALSE - object hasn't focus>.
Note
This function gets the focused object and check if it belong this object or any other object in compounded set.
Definition at line 348 of file d4d_object.c.
References D4D_FALSE, D4D_GetActiveScreen(), D4D_GetFocusedObject(), D4D_GetParentObject(), D4D_TRUE, NULL, D4D_OBJECT_S::pData, D4D_OBJECT_S::pRelations, and D4D_OBJECT_DATA_S::pScreen.
Referenced by D4D_ComboBoxListBoxMsgFeedBack().
D4D_BOOL D4D_IsVisible (D4D_OBJECT * pObject)
Function find out if the object is visible or not.
Parameters
pObject - pointer to the object
Returns
<D4D_TRUE - object is visible, D4D_FALSE - object is invisible>.
Note
This function gets the current status of object visible / invisible. The function control the object itself and also all parents objects..
Definition at line 325 of file d4d_object.c.
References D4D_FALSE, D4D_GetParentObject(), D4D_IsVisible(), D4D_OBJECT_F_VISIBLE, D4D_TRUE, D4D_OBJECT_DATA_S::flags, D4D_OBJECT_S::pData, and D4D_OBJECT_S::pRelations.
Referenced by D4D_ComboBoxButtonFeedBack(), D4D_ComboBoxStornoSelection(), D4D_IsVisible(), and D4D_ListBoxValue2Coor().
void D4D_ShowObject (D4D_OBJECT_PTR pObject, D4D_BOOL bShow)
Function control visibility of object on screen.
Parameters
pObject - pointer to the object.
bShow - <D4D_TRUE - visible, D4D_FALSE - hidden>
Returns
none.
Note
This function control the visibility of object on screen. The hide action force invalidate of whole screen.
Definition at line 92 of file d4d_object.c.
References D4D_CaptureKeys(), D4D_FALSE, D4D_FocusNextObject(), D4D_GetFocusedObject(), D4D_GetParentObject(), D4D_InvalidateObject(), D4D_InvalidateScreen(), D4D_OBJECT_F_VISIBLE, d4d_pKeysCapturer, D4D_TRUE, D4D_OBJECT_DATA_S::flags, NULL, D4D_OBJECT_S::pData, D4D_OBJECT_S::pRelations, and D4D_OBJECT_DATA_S::pScreen.
Referenced by D4D_CnslOnInit(), D4D_ComboBoxButtonFeedBack(), D4D_ComboBoxListFeedBack(), D4D_ComboBoxStornoSelection(), and D4D_ListBoxOnInit().