Freescale's eGUI: D4D LIST BOX API Functions Specification
D4D LIST BOX API Functions Specification
D4D List Box Widget
Functions
void D4D_ListBoxEnsureVisible (D4D_OBJECT *pThis)
Function ensure that the selected item in list will be scrolled to visible area.
D4D_LIST_BOX_INDEX D4D_ListBoxGetIndex (D4D_OBJECT *pThis)
Function returns the current selected item index.
void D4D_ListBoxSetIndex (D4D_OBJECT *pThis, D4D_LIST_BOX_INDEX ix)
Function select new item by index.
D4D_LIST_BOX_INDEX D4D_ListBoxGetItemCount (D4D_OBJECT_PTR pThis)
Function gets the count of list box items.
D4D_LIST_BOX_INDEX D4D_ListBoxFindUserDataItem (D4D_OBJECT_PTR pThis, void *pUser)
Function finds the index of items with specified user data.
void * D4D_ListBoxGetItemUserData (D4D_OBJECT_PTR pThis)
Function gets the selected item user data.
D4D_TCHAR * D4D_ListBoxGetItemText (D4D_OBJECT_PTR pThis)
Function gets the selected item text.
D4D_TCHAR * D4D_ListBoxGetItemTextIx (D4D_OBJECT_PTR pThis, D4D_LIST_BOX_INDEX ix)
Function gets the text of item choosed by item index.
void D4D_ListBoxChangeItemList (D4D_OBJECT_PTR pThis, const D4D_LIST_BOX_ITEM *pItems)
Function change the items list using by list box.
D4D_LIST_BOX_ITEM * D4D_ListBoxGetItemList (D4D_OBJECT_PTR pThis)
Function gets the current using item list.
Detailed Description
This section specifies the exact usage for each API function.
Function Documentation
void D4D_ListBoxChangeItemList (D4D_OBJECT_PTR pThis, const D4D_LIST_BOX_ITEM * pItems)
Function change the items list using by list box.
Parameters
pThis - pointer to the list box object
pItems - pointer to the new item list
Returns
none
Note
none
Definition at line 637 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, D4D_ListBoxOnInit(), NULL, D4D_LIST_BOX::pData, and D4D_LIST_BOX_DATA::pItems.
void D4D_ListBoxEnsureVisible (D4D_OBJECT * pThis)
Function ensure that the selected item in list will be scrolled to visible area.
Parameters
pThis - pointer to the list box object
Returns
none
Note
none
Definition at line 494 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, D4D_GetItemsCount(), D4D_GetPositionCount(), D4D_LIST_BOX_CHILD_SCROLL_BAR_IX, D4D_ScrlBrSetPosition(), D4D_LIST_BOX_DATA::ix, D4D_LIST_BOX_DATA::page_ix, D4D_LIST_BOX::pData, and D4D_OBJECT_S::pRelations.
Referenced by D4D_ListBoxFocusNextItem(), and D4D_ListBoxFocusPreviousItem().
D4D_LIST_BOX_INDEX D4D_ListBoxFindUserDataItem (D4D_OBJECT_PTR pThis, void * pUser)
Function finds the index of items with specified user data.
Parameters
pThis - pointer to the list box object
pUser - user data that is used to look for the item index (must match)
Returns
index of item if it's found, if not, it returns -1.
Note
none
Definition at line 574 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, D4D_GetItemsCount(), D4D_LIST_BOX::pData, D4D_LIST_BOX_DATA::pItems, and D4D_LIST_BOX_ITEM::pUser.
D4D_LIST_BOX_INDEX D4D_ListBoxGetIndex (D4D_OBJECT * pThis)
Function returns the current selected item index.
Parameters
pThis - pointer to the list box object
Returns
index on current selct item
Note
none
Definition at line 516 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, D4D_LIST_BOX_DATA::ix, NULL, and D4D_LIST_BOX::pData.
Referenced by D4D_ComboBoxListFeedBack(), D4D_ComboBoxOnMessage(), and D4D_ComboBoxSetIndex().
D4D_LIST_BOX_INDEX D4D_ListBoxGetItemCount (D4D_OBJECT_PTR pThis)
Function gets the count of list box items.
Parameters
pThis - pointer to the list box object
Returns
count of list box items.
Note
none
Definition at line 560 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, and D4D_GetItemsCount().
D4D_LIST_BOX_ITEM* D4D_ListBoxGetItemList (D4D_OBJECT_PTR pThis)
Function gets the current using item list.
Parameters
pThis - pointer to the list box object
Returns
pointer to current using item list
Note
none
Definition at line 655 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, NULL, D4D_LIST_BOX::pData, and D4D_LIST_BOX_DATA::pItems.
D4D_TCHAR* D4D_ListBoxGetItemText (D4D_OBJECT_PTR pThis)
Function gets the selected item text.
Parameters
pThis - pointer to the list box object
Returns
pointer to selected item text
Note
none
Definition at line 607 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, D4D_GetInternalStringPointer(), D4D_LIST_BOX_DATA::ix, D4D_LIST_BOX::pData, D4D_LIST_BOX_DATA::pItems, and D4D_LIST_BOX_ITEM::pText.
Referenced by D4D_ComboBoxListFeedBack(), and D4D_ComboBoxOnMessage().
D4D_TCHAR* D4D_ListBoxGetItemTextIx (D4D_OBJECT_PTR pThis, D4D_LIST_BOX_INDEX ix)
Function gets the text of item choosed by item index.
Parameters
pThis - pointer to the list box object
ix - index to item array
Returns
pointer to item text
Note
It returns none if the input index is out of list box range.
Definition at line 620 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, D4D_GetInternalStringPointer(), D4D_GetItemsCount(), NULL, D4D_LIST_BOX::pData, D4D_LIST_BOX_DATA::pItems, and D4D_LIST_BOX_ITEM::pText.
void* D4D_ListBoxGetItemUserData (D4D_OBJECT_PTR pThis)
Function gets the selected item user data.
Parameters
pThis - pointer to the list box object
Returns
user data of selected item.
Note
none
Definition at line 595 of file d4d_list_box.c.
References D4D_GET_LIST_BOX, D4D_LIST_BOX_DATA::ix, D4D_LIST_BOX::pData, D4D_LIST_BOX_DATA::pItems, and D4D_LIST_BOX_ITEM::pUser.
void D4D_ListBoxSetIndex (D4D_OBJECT * pThis, D4D_LIST_BOX_INDEX ix)
Function select new item by index.
Parameters
pThis - pointer to the list box object
ix - index of item that should be selected
Returns
none
Note
none
Definition at line 533 of file d4d_list_box.c.
References D4D_EVENT_ONCHANGE, D4D_FALSE, D4D_GET_LIST_BOX, D4D_GetItemsCount(), D4D_InvalidateObject(), D4D_LIST_BOX_DATA::ix, NULL, D4D_LIST_BOX::OnEvent, and D4D_LIST_BOX::pData.
Referenced by D4D_ComboBoxSetIndex(), and D4D_ComboBoxStornoSelection().