Freescale's eGUI: D4D SCREEN API Functions Specification
D4D SCREEN API Functions Specification
D4D SCREEN Handler
Functions
D4D_SCREEN * D4D_GetActiveScreen (void)
Returns pointer to current active screen.
void D4D_ActivateScreen (D4D_SCREEN *pNewScreen, D4D_BOOL bReplaceCurrent)
The function activate the new screen.
void D4D_EscapeScreen (void)
The function return to previous screen recorded in the history.
void D4D_EscapeToBaseScreen (void)
The function return to base screen recorded in the history.
void D4D_InitScreen (D4D_SCREEN *pScreen)
The function inits the screen and its objects for first time case.
void D4D_InvalidateScreen (D4D_SCREEN *pScreen, D4D_BOOL bComplete)
The function mark the screen and its abject as "redraw pending".
D4D_OBJECT_PTR D4D_GetFocusedObject (D4D_SCREEN *pScreen)
The function returns pointer to object that is focused in given screen.
void D4D_FocusNextObject (D4D_SCREEN *pScreen, D4D_BOOL bInitialSearch)
The function change focus to the next object in the given screen.
void D4D_FocusPrevObject (D4D_SCREEN *pScreen)
The function change focus to the previous object in the given screen.
void D4D_FocusSet (D4D_SCREEN *pScreen, D4D_OBJECT_PTR pObject)
The function set the obejct focus to new object.
void D4D_SetScreenFontProperties (D4D_SCREEN *pScreen, D4D_FONT_PROPERTIES property)
The function sets the screen font properties.
void D4D_SetScreenTextProperties (D4D_SCREEN *pScreen, D4D_TEXT_PROPERTIES property)
The function sets the screen text properties.
D4D_POINT D4D_GetClientToScreenPoint (D4D_OBJECT *pObject, D4D_POINT *nClientPoint)
The function convert client point on the screen to the global screen point.
D4D_POINT D4D_GetScreenToClientPoint (D4D_OBJECT *pObject, D4D_POINT *nScreenPoint)
The function convert global screen point on the screen to the client point.
D4D_BOOL D4D_ScrCheckCoor (D4D_SCREEN *pScreen, D4D_POINT *point)
The function check if the coordination are in screen area.
Detailed Description
This section specifies the exact usage for each API function.
Function Documentation
void D4D_ActivateScreen (D4D_SCREEN * pNewScreen, D4D_BOOL bReplaceCurrent)
The function activate the new screen.
Parameters
pNewScreen - the pointer to new screen
bReplaceCurrent - the flag to tell function if the new screen should replace previous one in screen buffer
Returns
None
Note
Enter new screen, remember the history if not only replacing
Definition at line 94 of file d4d_screen.c.
References D4D_CaptureKeys(), D4D_ChangeScreen(), D4D_GetActiveScreen(), D4D_SCREEN_HISTORY, d4d_screenHistory, d4d_screenHistoryIndex, and NULL.
Referenced by D4D_Init().
void D4D_EscapeScreen (void)
The function return to previous screen recorded in the history.
Returns
None
Note
Recall the previous screen in screen history buffer
Definition at line 130 of file d4d_screen.c.
References D4D_CaptureKeys(), D4D_ChangeScreen(), D4D_GetActiveScreen(), d4d_screenHistoryIndex, and NULL.
Referenced by D4D_HandleKeys().
void D4D_EscapeToBaseScreen (void)
The function return to base screen recorded in the history.
Returns
None
Note
Recall the base (first) screen in screen history buffer
Definition at line 156 of file d4d_screen.c.
References D4D_CaptureKeys(), D4D_ChangeScreen(), D4D_GetActiveScreen(), d4d_screenHistoryIndex, and NULL.
void D4D_FocusNextObject (D4D_SCREEN * pScreen, D4D_BOOL bInitialSearch)
The function change focus to the next object in the given screen.
Parameters
pScreen - the pointer to screen
bInitialSearch - flag force start looking from the first object in screen object table
Returns
None
Note
In case that there is no other usable object (visible, enable ...) the focus is not changed
Definition at line 286 of file d4d_screen.c.
References D4D_FALSE, D4D_FindNextObject(), d4d_msg, D4D_MSG_KILLFOCUS, D4D_MSG_SETFOCUS, D4D_OBJECT_F_ENABLED, D4D_OBJECT_F_REDRAWSTATE, D4D_OBJECT_F_TABSTOP, D4D_OBJECT_F_VISIBLE, D4D_SendMessage(), D4D_SetObjectFlags(), D4D_OBJECT_DATA_S::flags, D4D_SCREEN_DATA::flags, D4D_SCREEN_DATA::focusedObject, D4D_MESSAGE_S::nMsgId, NULL, D4D_OBJECT_S::pData, D4D_SCREEN_S::pData, D4D_MESSAGE_S::pObject, D4D_SCREEN_S::pObjects, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_EnableObject(), D4D_HandleKeys(), D4D_InitScreen(), and D4D_ShowObject().
void D4D_FocusPrevObject (D4D_SCREEN * pScreen)
The function change focus to the previous object in the given screen.
Parameters
pScreen - the pointer to screen
Returns
None
Note
In case that there is no other usable object (visible, enable ...) the focus is not changed
Definition at line 356 of file d4d_screen.c.
References D4D_FALSE, D4D_FindPreviousObject(), D4D_GetParentObject(), d4d_msg, D4D_MSG_KILLFOCUS, D4D_MSG_SETFOCUS, D4D_OBJECT_F_ENABLED, D4D_OBJECT_F_REDRAWSTATE, D4D_OBJECT_F_TABSTOP, D4D_OBJECT_F_VISIBLE, D4D_SendMessage(), D4D_SetObjectFlags(), D4D_TRUE, D4D_OBJECT_DATA_S::flags, D4D_SCREEN_DATA::focusedObject, D4D_MESSAGE_S::nMsgId, NULL, D4D_OBJECT_S::pData, D4D_SCREEN_S::pData, D4D_MESSAGE_S::pObject, D4D_SCREEN_S::pObjects, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_HandleKeys().
void D4D_FocusSet (D4D_SCREEN * pScreen, D4D_OBJECT_PTR pObject)
The function set the obejct focus to new object.
Parameters
pScreen - the pointer to screen
pObject - the pointer to object that should be focused
Returns
None
Note
In case that there is no other issue (obejct exists, visible, enable ...) the focus is changed to given one
Definition at line 430 of file d4d_screen.c.
References D4D_FALSE, D4D_FindObject(), D4D_IsEnabled(), d4d_msg, D4D_MSG_KILLFOCUS, D4D_MSG_SETFOCUS, D4D_OBJECT_F_ENABLED, D4D_OBJECT_F_REDRAWSTATE, D4D_OBJECT_F_TABSTOP, D4D_SendMessage(), D4D_SetObjectFlags(), D4D_OBJECT_DATA_S::flags, D4D_SCREEN_DATA::focusedObject, D4D_MESSAGE_S::nMsgId, NULL, D4D_OBJECT_S::pData, D4D_SCREEN_S::pData, D4D_MESSAGE_S::pObject, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_CaptureKeys(), D4D_ConsoleOnMessage(), D4D_GaugOnMessage(), D4D_GraphOnMessage(), D4D_IconOnMessage(), D4D_LabelOnMessage(), and D4D_TextBoxOnMessage().
D4D_SCREEN* D4D_GetActiveScreen (void)
Returns pointer to current active screen.
Returns
pointer to current active screen
Note
none
Definition at line 78 of file d4d_screen.c.
References d4d_screenHistory, d4d_screenHistoryIndex, and NULL.
Referenced by D4D_ActivateScreen(), D4D_CaptureKeys(), D4D_EditBoxPutString(), D4D_EscapeScreen(), D4D_EscapeToBaseScreen(), D4D_HandleKeys(), D4D_ImgDecBmpDraw(), D4D_ImgDecExtD4DDraw(), D4D_ImgDecIntD4DDraw(), D4D_IsMineFocus(), D4D_Poll(), and D4D_SetOrientation().
D4D_POINT D4D_GetClientToScreenPoint (D4D_OBJECT * pObject, D4D_POINT * nClientPoint)
The function convert client point on the screen to the global screen point.
Parameters
pObject - the pointer to object
nClientPoint - pointer to client point structure
Returns
global screen point
Note
The function already handles also the compounded objects.
Definition at line 536 of file d4d_screen.c.
References D4D_BEVEL_WIDTH, D4D_GetScrHeaderSize(), D4D_OBJECT_USR_DATA_PARENT_IX, D4D_SCR_F_BEVEL, D4D_SCR_F_OUTLINE, D4D_SCREEN_S::flags, D4D_MARGIN::left, NULL, D4D_OBJECT_S::pData, D4D_OBJECT_S::pMargin, D4D_OBJECT_S::position, D4D_SCREEN_S::position, D4D_OBJECT_S::pRelations, D4D_OBJECT_DATA_S::pScreen, D4D_MARGIN::top, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_BtnValue2Coor(), D4D_CheckBoxValue2Coor(), D4D_CnslValue2Coor(), D4D_ComputeGeometry(), D4D_DrawFrame(), D4D_EditBoxValue2Coor(), D4D_GaugValue2Point(), D4D_GraphValue2Coor(), D4D_GroupBoxOnDraw(), D4D_IconValue2Coor(), D4D_LblValue2Coor(), D4D_ListBoxValue2Coor(), D4D_MenuValue2Coor(), D4D_PrgrsBarValue2Coor(), D4D_RadioButtonValue2Coor(), D4D_ScrlBrValue2Coor(), D4D_SldrValue2Coor(), and D4D_TextBoxValue2Coor().
D4D_OBJECT_PTR D4D_GetFocusedObject (D4D_SCREEN * pScreen)
The function returns pointer to object that is focused in given screen.
Parameters
pScreen - the pointer to screen
Returns
pointer of focused object in given screen
Note
None.
Definition at line 266 of file d4d_screen.c.
References D4D_SCREEN_DATA::focusedObject, NULL, and D4D_SCREEN_S::pData.
Referenced by D4D_DrawFrame(), D4D_EditBoxPutString(), D4D_EnableObject(), D4D_HandleKeys(), D4D_IsMineFocus(), and D4D_ShowObject().
D4D_POINT D4D_GetScreenToClientPoint (D4D_OBJECT * pObject, D4D_POINT * nScreenPoint)
The function convert global screen point on the screen to the client point.
Parameters
pObject - the pointer to object
nScreenPoint - pointer to global screen point structure
Returns
client screen point
Note
The function already handles also the compounded objects.
Definition at line 586 of file d4d_screen.c.
References D4D_BEVEL_WIDTH, D4D_GetScrHeaderSize(), D4D_OBJECT_USR_DATA_PARENT_IX, D4D_SCR_F_BEVEL, D4D_SCR_F_OUTLINE, D4D_SCREEN_S::flags, D4D_MARGIN::left, NULL, D4D_OBJECT_S::pData, D4D_OBJECT_S::pMargin, D4D_OBJECT_S::position, D4D_SCREEN_S::position, D4D_OBJECT_S::pRelations, D4D_OBJECT_DATA_S::pScreen, D4D_MARGIN::top, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_MenuScrollBarSetup().
void D4D_InitScreen (D4D_SCREEN * pScreen)
The function inits the screen and its objects for first time case.
Parameters
pScreen - the pointer to screen
Returns
None
Note
Initialize the the screen. This is keep as a public API to allow user application initialize the screen before it native first use.
Definition at line 184 of file d4d_screen.c.
References D4D_FocusNextObject(), D4D_MSG_ONINIT, D4D_OBJECT_F_NOTINIT, D4D_SCR_F_EXIT, D4D_SCR_FINT_INITDONE, D4D_SCR_FINT_TOUCHENABLE, D4D_SendMessageMask(), D4D_SetObjectScreenPointer(), D4D_TRUE, D4D_SCREEN_DATA::flags, D4D_SCREEN_S::flags, D4D_MESSAGE_S::nMsgId, NULL, D4D_SCREEN_S::OnInit, D4D_SCREEN_S::pData, D4D_MESSAGE_S::pObject, D4D_SCREEN_S::pObjects, and D4D_MESSAGE_S::pScreen.
Referenced by D4D_ChangeScreen().
void D4D_InvalidateScreen (D4D_SCREEN * pScreen, D4D_BOOL bComplete)
The function mark the screen and its abject as "redraw pending".
Parameters
pScreen - the pointer to screen that should be invalidate
bComplete - flag to mark the the screen and object MUST be redrawed completely, not only the active areas
Returns
None
Note
Invalidate screen and its object in two ways - complete or active areas only.
Definition at line 238 of file d4d_screen.c.
References D4D_OBJECT_F_REDRAW, D4D_SCR_FINT_CHECKOBJECTS, D4D_SCR_FINT_REDRAWC, D4D_SetObjectFlags(), D4D_TRUE, D4D_SCREEN_DATA::flags, NULL, D4D_SCREEN_S::pData, and D4D_SCREEN_S::pObjects.
Referenced by D4D_ChangeScreen(), D4D_ComboBoxListFeedBack(), D4D_ComboBoxStornoSelection(), D4D_SetOrientation(), D4D_SetScreenFontProperties(), D4D_SetScreenTextProperties(), and D4D_ShowObject().
D4D_BOOL D4D_ScrCheckCoor (D4D_SCREEN * pScreen, D4D_POINT * point)
The function check if the coordination are in screen area.
Parameters
pScreen - the pointer to screen
point - pointer to input point structure
Returns
D4D_TRUE - in case that the coordination fits to the screen area, D4D_FALSE if not
Note
None
Definition at line 634 of file d4d_screen.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_FALSE, D4D_GetScrHeaderSize(), D4D_TRUE, D4D_SCREEN_S::position, D4D_SCREEN_S::size, D4D_POINT::x, and D4D_POINT::y.
void D4D_SetScreenFontProperties (D4D_SCREEN * pScreen, D4D_FONT_PROPERTIES property)
The function sets the screen font properties.
Parameters
pScreen - the pointer to screen
property - font property
Returns
None
Note
Sets the font property for text used natively by screen (title)
Definition at line 503 of file d4d_screen.c.
References D4D_FALSE, D4D_InvalidateScreen(), D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::str_properties, and D4D_SCREEN_S::textBuff.
void D4D_SetScreenTextProperties (D4D_SCREEN * pScreen, D4D_TEXT_PROPERTIES property)
The function sets the screen text properties.
Parameters
pScreen - the pointer to screen
property - text property
Returns
None
Note
Sets the text property for text used natively by screen (title)
Definition at line 519 of file d4d_screen.c.
References D4D_FALSE, D4D_InvalidateScreen(), D4D_STRING_S::str_properties, D4D_STR_PROPERTIES_S::text_properties, and D4D_SCREEN_S::textBuff.