Freescale's eGUI: D4D BMP DRAW API Functions Specification
D4D BMP DRAW API Functions Specification
D4D BITMAP functionality
Functions
D4D_EXTIMG_TYPE D4D_GetImgSrcType (D4D_BMP *pBmp)
Function returns the type of image source.
void D4D_DrawRBmpXY (D4D_COOR x, D4D_COOR y, const D4D_BMP *pBmp, D4D_BOOL greyScale, D4D_COOR radius)
Function draw the bitmap on the specify coordination.
void D4D_DrawBmpRect (D4D_POINT *ppt, D4D_SIZE *psz, const D4D_BMP *pBmp, D4D_BMP_PROPERTIES bmpProp, D4D_COLOR colorBkgd, D4D_BOOL greyScale)
Function draw the bitmap on the specify coordination into rectangle.
D4D_SIZE D4D_GetBmpSize (const D4D_BMP *pBmp)
Function gets information about bitmap size.
D4D_COOR D4D_GetBmpWidth (const D4D_BMP *pBmp)
Function gets information about bitmap width.
D4D_COOR D4D_GetBmpHeight (const D4D_BMP *pBmp)
Function gets information about bitmap height.
int D4D_GetBmpHeader (D4D_BMP *pBmp, void *pBuff, int max_size)
Function gets image file header.
Detailed Description
This section specifies the exact usage for each API function.
Function Documentation
void D4D_DrawBmpRect (D4D_POINT * ppt, D4D_SIZE * psz, const D4D_BMP * pBmp, D4D_BMP_PROPERTIES bmpProp, D4D_COLOR colorBkgd, D4D_BOOL greyScale)
Function draw the bitmap on the specify coordination into rectangle.
Parameters
ppt - pointer on point structure of top left corner on screen to specify rectangle
psz - pointer on the size structure that defines size of the rectangle
pBmp - pointer on the bitmap structure
bmpProp - bitmap properties
colorBkgd - background color of bitmap
greyScale - drawing in greyScale
Returns
none
Note
This function draws bitmap in specified rectangle, it can draw colors in grey scale, and with round corners. There is optin to align bitmap inside the rectangle.
Definition at line 243 of file d4d_bmp.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_ALIGN_H_CENTER_MASK, D4D_ALIGN_H_LEFT_MASK, D4D_ALIGN_H_MASK, D4D_ALIGN_H_RIGHT_MASK, D4D_ALIGN_V_BOTTOM_MASK, D4D_ALIGN_V_CENTER_MASK, D4D_ALIGN_V_MASK, D4D_ALIGN_V_TOP_MASK, D4D_DrawRBmpXY(), D4D_FillRect(), D4D_FillRectXY(), D4D_GetBmpHeight(), D4D_GetBmpWidth(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawRBmpXY (D4D_COOR x, D4D_COOR y, const D4D_BMP * pBmp, D4D_BOOL greyScale, D4D_COOR radius)
Function draw the bitmap on the specify coordination.
Parameters
x - coordination in X axis
y - coordination in Y axis
pBmp - pointer on the bitmap structure
greyScale - drawing in greyScale
radius - round corner radius
Returns
none
Note
This function draws bitmap on specified coordination, it can draw colors in grey scale, and with round corners.
Definition at line 208 of file d4d_bmp.c.
References D4D_EXTIMG_INTD4D, D4D_EXTIMG_UNKNOWN, D4D_GetImgSrcType(), D4D_EXTIMG_FUNC::D4D_ImgDecDraw, and D4D_BMP::pParam.
Referenced by D4D_DrawBmpRect().
int D4D_GetBmpHeader (D4D_BMP * pBmp, void * pBuff, int max_size)
Function gets image file header.
Parameters
pBmp - pointer on the bitmap structure
pBuff - buffer in application code that is prepared to store the image header
max_size - max_buffer size
Returns
count of byte copied to buffer
Note
Function return the image header. The size and type of image header depends on input image source typeZ.
Definition at line 518 of file d4d_bmp.c.
References D4D_EXTIMG_INTD4D, D4D_GetImgSrcType(), D4D_EXTIMG_FUNC::D4D_ImgDecGetHeader, and D4D_BMP::pParam.
D4D_COOR D4D_GetBmpHeight (const D4D_BMP * pBmp)
Function gets information about bitmap height.
Parameters
pBmp - pointer on the bitmap structure
Returns
none
Note
Function tries get the height information of bitmap handled in D4D_BMP parameter. In case that there is no chance get the height, it return height 0.
Definition at line 484 of file d4d_bmp.c.
References D4D_EXTIMG_INTD4D, D4D_EXTIMG_UNKNOWN, D4D_GetImgSrcType(), D4D_EXTIMG_FUNC::D4D_ImgDecGetHeight, and D4D_BMP::pParam.
Referenced by D4D_DrawBmpRect(), D4D_DrawScreenNC(), D4D_GetIconsMaxSize(), D4D_GetScrHeaderSize(), D4D_GetTitleBarHeight(), and D4D_MenuOnDraw().
D4D_SIZE D4D_GetBmpSize (const D4D_BMP * pBmp)
Function gets information about bitmap size.
Parameters
pBmp - pointer on the bitmap structure
Returns
none
Note
Function tries get the size information of bitmap handled in D4D_BMP parameter. In case that there is no chance get the size, it return size 0,0.
Definition at line 421 of file d4d_bmp.c.
References D4D_EXTIMG_INTD4D, D4D_EXTIMG_UNKNOWN, D4D_GetImgSrcType(), D4D_EXTIMG_FUNC::D4D_ImgDecGetSize, d4d_size_zero, and D4D_BMP::pParam.
Referenced by D4D_CheckBoxValue2Coor(), and D4D_RadioButtonValue2Coor().
D4D_COOR D4D_GetBmpWidth (const D4D_BMP * pBmp)
Function gets information about bitmap width.
Parameters
pBmp - pointer on the bitmap structure
Returns
none
Note
Function tries get the width information of bitmap handled in D4D_BMP parameter. In case that there is no chance get the width, it return width 0.
Definition at line 453 of file d4d_bmp.c.
References D4D_EXTIMG_INTD4D, D4D_EXTIMG_UNKNOWN, D4D_GetImgSrcType(), D4D_EXTIMG_FUNC::D4D_ImgDecGetWidth, and D4D_BMP::pParam.
Referenced by D4D_DrawBmpRect(), D4D_GetIconsMaxSize(), and D4D_GetScrHeaderTitleOffset().
D4D_EXTIMG_TYPE D4D_GetImgSrcType (D4D_BMP * pBmp)
Function returns the type of image source.
External Bitmap support
Parameters
pBmp - pointer on the bitmap structure
Returns
type of image
Note
This function find out the type of the image source. In case of not supported image it returns D4D_EXTIMG_UNKNOWN.
Definition at line 143 of file d4d_bmp.c.
References D4D_BMP_EXTSRC_SUPPORT_D4D_EXT, D4D_CompareStrings(), D4D_EXTIMG_BMP, D4D_EXTIMG_D4D, D4D_EXTIMG_INTD4D, D4D_EXTIMG_UNKNOWN, D4D_GetFileExtension(), D4D_ToUpper(), NULL, D4D_BMP::pData, and D4D_BMP::pParam.
Referenced by D4D_DrawRBmpXY(), D4D_GetBmpHeader(), D4D_GetBmpHeight(), D4D_GetBmpSize(), and D4D_GetBmpWidth().