Freescale's eGUI: D4D BASIC DRAW API Functions Specification
D4D BASIC DRAW API Functions Specification
D4D BASIC DRAWING functionality
Functions
void D4D_MoveTo (D4D_POINT *ppt)
Function move logic cursor to new position.
void D4D_MoveToXY (D4D_COOR x, D4D_COOR y)
Function move logic cursor to new position.
void D4D_PutPixel (D4D_POINT *ppt, D4D_LINETYPE type, D4D_COLOR color)
Function puts one pixel on the screen.
void D4D_PutPixelTo (D4D_LINETYPE type, D4D_COLOR color)
Function puts one pixel on the screen.
void D4D_PutPixelXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE type, D4D_COLOR color)
Function puts one pixel on the screen.
void D4D_ClearScreen (D4D_COLOR color)
Function readraw complete screen by one color.
void D4D_LineTo (D4D_POINT *ppt, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw line on the screen.
void D4D_LineToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw line on the screen.
void D4D_Rect (D4D_POINT *ppt, D4D_SIZE *psz, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
void D4D_RectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
void D4D_RectTo (D4D_POINT *ppt, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
void D4D_RectToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
void D4D_FillRect (D4D_POINT *ppt, D4D_SIZE *psz, D4D_COLOR color)
Function draw filled rectangle on the screen.
void D4D_FillRectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color)
Function draw filled rectangle on the screen.
void D4D_FillRectTo (D4D_POINT *ppt, D4D_COLOR color)
Function draw filled rectangle on the screen.
void D4D_FillRectToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR color)
Function draw filled rectangle on the screen.
void D4D_Box (D4D_POINT *ppt, D4D_SIZE *psz, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
void D4D_BoxXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
void D4D_BoxTo (D4D_POINT *ppt, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
void D4D_BoxToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
void D4D_FillRectColorScale (D4D_POINT *ppt, D4D_SIZE *psz, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
void D4D_FillRectColorScaleXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
void D4D_FillRectColorScaleTo (D4D_POINT *ppt, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
void D4D_FillRectColorScaleToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
void D4D_FillCircle (D4D_POINT *pCenter, D4D_COOR r, D4D_COLOR color)
Function draw filled circle on the screen.
void D4D_FillCircleXY (D4D_COOR x, D4D_COOR y, D4D_COOR r, D4D_COLOR color)
Function draw filled circle on the screen.
void D4D_Circle (D4D_POINT *pCenter, D4D_COOR r, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw circle on the screen.
void D4D_CircleXY (D4D_COOR x, D4D_COOR y, D4D_COOR r, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw circle on the screen.
void D4D_DrawTextTabXY (D4D_COOR x, D4D_COOR y, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text on XY coordination with TAB function.
void D4D_DrawTextRectTab (D4D_POINT *ppt, D4D_SIZE *psz, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text with TAB function in rectangle.
void D4D_DrawTextRectTabTo (D4D_POINT *ppt, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text on XY coordination with TAB function in rectangle.
void D4D_DrawTextRectTabXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text with TAB function in rectangle.
void D4D_DrawTextRectTabToXY (D4D_COOR x, D4D_COOR y, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text on XY coordination with TAB function in rectangle.
void D4D_RRect (D4D_POINT *ppt, D4D_SIZE *psz, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
void D4D_RRectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
void D4D_RRectTo (D4D_POINT *ppt, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
void D4D_RRectToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
void D4D_FillRRect (D4D_POINT *ppt, D4D_SIZE *psz, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
void D4D_FillRRectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
void D4D_FillRRectTo (D4D_POINT *ppt, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
void D4D_FillRRectToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
void D4D_RBox (D4D_POINT *ppt, D4D_SIZE *psz, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
void D4D_RBoxXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
void D4D_RBoxTo (D4D_POINT *ppt, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
void D4D_RBoxToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
void D4D_FillQuadrant (D4D_POINT *pCenter, D4D_COOR radius, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw fill quadrant of circle on the screen.
void D4D_FillQuadrantXY (D4D_COOR x, D4D_COOR y, D4D_COOR radius, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw fill quadrant of circle on the screen.
void D4D_Quadrant (D4D_POINT *pCenter, D4D_COOR radius, D4D_LINETYPE ltype, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw quadrant of circle on the screen.
void D4D_QuadrantXY (D4D_COOR x, D4D_COOR y, D4D_COOR radius, D4D_LINETYPE ltype, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw quadrant of circle on the screen.
void D4D_FillRRectColorScale (D4D_POINT *ppt, D4D_SIZE *psz, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
void D4D_FillRRectColorScaleXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
void D4D_FillRRectColorScaleTo (D4D_POINT *ppt, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
void D4D_FillRRectColorScaleToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
D4D_COOR D4D_RndCornerGetNonPrintedPxl (D4D_COOR radius, D4D_COOR line)
Function that counts number of printed pixels in specified line of circle quadrant.
void D4D_DrawTextRRectTab (D4D_POINT *ppt, D4D_SIZE *psz, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text with TAB function in rectangle with round corners.
void D4D_DrawTextRRectTabTo (D4D_POINT *ppt, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text on XY coordination with TAB function in rectangle with round corners.
void D4D_DrawTextRRectTabXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text with TAB function in rectangle with round corners.
void D4D_DrawTextRRectTabToXY (D4D_COOR x, D4D_COOR y, D4D_STRING *buffText, D4D_TAB *pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text on XY coordination with TAB function in rectangle with round corners.
void D4D_Bevel (D4D_POINT *ppt, D4D_SIZE *psz, D4D_COLOR color, D4D_BEVEL type, D4D_COOR radius)
Function draw standard object bevel specified by parameters.
void D4D_DrawFrame (D4D_OBJECT *pObject, D4D_COLOR clrT, D4D_COLOR clrB)
Function draw standard object frame based on the object settings and current state.
Detailed Description
This section specifies the exact usage for each API function.
Function Documentation
void D4D_Bevel (D4D_POINT * ppt, D4D_SIZE * psz, D4D_COLOR color, D4D_BEVEL type, D4D_COOR radius)
Function draw standard object bevel specified by parameters.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the bevel
color - base color of bevel (the eal used color are computed from this color)
type - type of bevel
radius - round corner radius
Returns
none
Note
Function draws the standard eGUI bevel specified by parameters. The used colors are computed from D4D_BEVEL_FORE_INTENSITY & D4D_BEVEL_BCKG_INTENSITY constants. The logical last draw cursor is not moved.
Definition at line 1565 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_BEVEL_BCKG_INTENSITY, D4D_BEVEL_DENTED, D4D_BEVEL_FORE_INTENSITY, D4D_BEVEL_NONE, D4D_BEVEL_RAISED, D4D_BEVEL_RESERVED, D4D_BEVEL_WIDTH, D4D_ChangeColorIntesity(), D4D_FillRect(), D4D_LINE_THICK, D4D_QUAD_1, D4D_QUAD_2, D4D_QUAD_3, D4D_QUAD_4, D4D_Quadrant(), D4D_UNUSED, D4D_SCREEN_S::radius, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_DrawFrame(), and D4D_DrawScreenNC().
void D4D_Box (D4D_POINT * ppt, D4D_SIZE * psz, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
Returns
none
Note
Function draws the rectangle with outline on the screen in any colors. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 346 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_BoxXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_BoxTo (D4D_POINT * ppt, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
Parameters
ppt - pointer on point structure of bottm right corner on screen
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
Returns
none
Note
Function draws the rectangle with outline on the screen in any colors. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 388 of file d4d_basic_draw.c.
References D4D_BoxToXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_BoxToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
Returns
none
Note
Function draws the rectangle with outline on the screen in any colors. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 405 of file d4d_basic_draw.c.
References D4D_LCD_Box(), D4D_LCD_Rect(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_BoxTo().
void D4D_BoxXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill)
Function draw filled rectangle with outline on the screen.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
Returns
none
Note
Function draws the rectangle with outline on the screen in any colors. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 365 of file d4d_basic_draw.c.
References D4D_LCD_Box(), D4D_LCD_Rect(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_Box(), D4D_GraphDrawEmptyGraph(), D4D_ImgDecBmpDraw(), D4D_ImgDecExtD4DDraw(), and D4D_ImgDecIntD4DDraw().
void D4D_Circle (D4D_POINT * pCenter, D4D_COOR r, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw circle on the screen.
Parameters
pCenter - pointer to point structure that defines circle center
r - radius of circle
ltype - type of the line (thin/thick)
color - color of circle
Returns
none
Note
Function draws the circle on the screen in any color. The logical last draw cursor is not moved.
Definition at line 569 of file d4d_basic_draw.c.
References D4D_FALSE, D4D_LCD_Circle(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_RadioButtonOnDraw().
void D4D_CircleXY (D4D_COOR x, D4D_COOR y, D4D_COOR r, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw circle on the screen.
Parameters
x - coordination in axis X that defines circle center
y - coordination in axis Y that defines circle center
ltype - coordination in axis Y that defines circle center
r - radius of circle
ltype - type of the line (thin/thick)
color - color of circle
Returns
none
Note
Function draws the circle on the screen in any color. The logical last draw cursor is not moved.
Definition at line 586 of file d4d_basic_draw.c.
References D4D_FALSE, and D4D_LCD_Circle().
void D4D_ClearScreen (D4D_COLOR color)
Function readraw complete screen by one color.
Parameters
color - screen color
Returns
none
Note
Function redraw complete screen by one color. The logic draw cursor is moved to 0,0 coordination.
Definition at line 147 of file d4d_basic_draw.c.
References D4D_DisplayHeight(), D4D_DisplayWidth(), D4D_LCD_Box(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawFrame (D4D_OBJECT * pObject, D4D_COLOR clrT, D4D_COLOR clrB)
Function draw standard object frame based on the object settings and current state.
Parameters
pObject - pointer on object which Frame should be draw
clrT - fore color of frame
clrB - background color of frame
Returns
none
Note
Function draws the Frame of object depending on object settings and current state
Definition at line 1654 of file d4d_basic_draw.c.
References D4D_Bevel(), D4D_GetClientToScreenPoint(), D4D_GetFocusedObject(), D4D_LINE_THIN, D4D_OBJECT_F_BEVEL_MASK, D4D_OBJECT_F_FOCUSRECT, D4D_OBJECT_FLAGS2BEVEL, D4D_RRect(), D4D_OBJECT_DATA_S::flags, D4D_OBJECT_S::pData, D4D_OBJECT_S::position, D4D_SCREEN_S::position, D4D_OBJECT_DATA_S::pScreen, D4D_OBJECT_S::radius, and D4D_OBJECT_S::size.
Referenced by D4D_BtnOnDraw(), D4D_CheckBoxOnDraw(), D4D_ConsoleOnDraw(), D4D_EditBoxOnDraw(), D4D_GaugOnDraw(), D4D_GraphOnDraw(), D4D_GroupBoxOnDraw(), D4D_IconOnDraw(), D4D_LabelOnDraw(), D4D_ListBoxOnDraw(), D4D_MenuOnDraw(), D4D_PictOnDraw(), D4D_PrgrsBarOnDraw(), D4D_RadioButtonOnDraw(), D4D_ScrlBrOnDraw(), D4D_SldrOnDraw(), and D4D_TextBoxOnDraw().
void D4D_DrawTextRectTab (D4D_POINT * ppt, D4D_SIZE * psz, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text with TAB function in rectangle.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The logical last draw cursor is not moved.
Definition at line 634 of file d4d_basic_draw.c.
References D4D_PRINT_DESC::colorBack, D4D_PRINT_DESC::colorText, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ALIGN_H_CENTER_MASK, D4D_ALIGN_H_LEFT_MASK, D4D_ALIGN_H_MASK, D4D_ALIGN_H_RIGHT_MASK, D4D_ALIGN_V_BOTTOM_MASK, D4D_ALIGN_V_CENTER_MASK, D4D_ALIGN_V_MASK, D4D_ALIGN_V_TOP_MASK, D4D_FillRectXY(), D4D_FNT_PRTY_TRANSPARENT_MASK, D4D_GetFont(), D4D_GetFontHeight(), D4D_GetTextBuffWidthTab(), D4D_LCD_PrintStr(), D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, D4D_PRINT_DESC::maxWidth, D4D_PRINT_DESC::pFontType, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_PRINT_DESC::properties, D4D_PRINT_DESC::pTab, D4D_STRING_S::pText, D4D_PRINT_DESC::pText, D4D_STRING_S::str_properties, D4D_STR_PROPERTIES_S::text_properties, D4D_PRINT_DESC::textLength, D4D_PRINT_DESC::textOffset, D4D_PRINT_DESC::x, D4D_POINT::x, D4D_PRINT_DESC::y, and D4D_POINT::y.
Referenced by D4D_DrawTextRectTabTo(), D4D_DrawTextRectTabToXY(), D4D_DrawTextRectTabXY(), D4D_DrawTextRRectTab(), and D4D_TextBoxOnDraw().
void D4D_DrawTextRectTabTo (D4D_POINT * ppt, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text on XY coordination with TAB function in rectangle.
Parameters
ppt - pointer on point structure of bottom right corner on screen
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The rectangle is defined by draw cursor (top, left) and ppt parameter. The logical last draw cursor is not moved.
Definition at line 758 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_DrawTextRectTab(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawTextRectTabToXY (D4D_COOR x, D4D_COOR y, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text on XY coordination with TAB function in rectangle.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The rectangle is defined by draw cursor (top, left) and x,y parameter. The logical last draw cursor is not moved.
Definition at line 812 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_DrawTextRectTab(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawTextRectTabXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text with TAB function in rectangle.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The logical last draw cursor is not moved.
Definition at line 783 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_DrawTextRectTab(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawTextRRectTab (D4D_POINT * ppt, D4D_SIZE * psz, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text with TAB function in rectangle with round corners.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
radius - radius of round corners
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The logical last draw cursor is not moved.
Definition at line 1343 of file d4d_basic_draw.c.
References D4D_PRINT_DESC::colorBack, D4D_PRINT_DESC::colorText, D4D_SIZE::cx, D4D_SIZE::cy, D4D_ALIGN_H_CENTER_MASK, D4D_ALIGN_H_LEFT_MASK, D4D_ALIGN_H_MASK, D4D_ALIGN_H_RIGHT_MASK, D4D_ALIGN_V_BOTTOM_MASK, D4D_ALIGN_V_CENTER_MASK, D4D_ALIGN_V_MASK, D4D_ALIGN_V_TOP_MASK, D4D_DrawTextRectTab(), D4D_FillQuadrant(), D4D_FillRectXY(), D4D_FillRRect(), D4D_FNT_PRTY_TRANSPARENT_MASK, D4D_GetFont(), D4D_GetFontHeight(), D4D_GetTextBuffWidthTab(), D4D_LCD_PrintStr(), D4D_QUAD_1, D4D_QUAD_2, D4D_QUAD_3, D4D_QUAD_4, D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, D4D_PRINT_DESC::maxWidth, D4D_PRINT_DESC::pFontType, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_PRINT_DESC::properties, D4D_PRINT_DESC::pTab, D4D_STRING_S::pText, D4D_PRINT_DESC::pText, D4D_SCREEN_S::radius, D4D_STRING_S::str_properties, D4D_STR_PROPERTIES_S::text_properties, D4D_PRINT_DESC::textLength, D4D_PRINT_DESC::textOffset, D4D_PRINT_DESC::x, D4D_POINT::x, D4D_PRINT_DESC::y, and D4D_POINT::y.
Referenced by D4D_BtnOnDraw(), D4D_DrawTextRRectTabTo(), D4D_DrawTextRRectTabToXY(), and D4D_DrawTextRRectTabXY().
void D4D_DrawTextRRectTabTo (D4D_POINT * ppt, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text on XY coordination with TAB function in rectangle with round corners.
Parameters
ppt - pointer on point structure of bottom right corner on screen
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
radius - round corner radius
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The rectangle is defined by draw cursor (top, left) and ppt parameter. The logical last draw cursor is not moved.
Definition at line 1484 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_DrawTextRRectTab(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawTextRRectTabToXY (D4D_COOR x, D4D_COOR y, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text on XY coordination with TAB function in rectangle with round corners.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
radius - round corner radius
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The rectangle is defined by draw cursor (top, left) and x,y parameter. The logical last draw cursor is not moved.
Definition at line 1540 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_DrawTextRRectTab(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawTextRRectTabXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd, D4D_COOR radius)
Function draw text with TAB function in rectangle with round corners.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
radius - round corner radius
Returns
none
Note
Function draws the text on the screen in any color of text and background. The text is drawed in rectangle so it also use the align options in text buffer structure. The logical last draw cursor is not moved.
Definition at line 1510 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_DrawTextRRectTab(), D4D_POINT::x, and D4D_POINT::y.
void D4D_DrawTextTabXY (D4D_COOR x, D4D_COOR y, D4D_STRING * buffText, D4D_TAB * pTab, D4D_COLOR colorText, D4D_COLOR colorBkgd)
Function draw text on XY coordination with TAB function.
Parameters
x - coordination in axis X that defines left corner of text
y - coordination in axis Y that defines top corner of text
buffText - pointer to text buffer
pTab - pointer to tab table
colorText - color of text
colorBkgd - color of background
Returns
none
Note
Function draws the text on the screen in any color of text and background. The logical last draw cursor is not moved.
Definition at line 603 of file d4d_basic_draw.c.
References D4D_PRINT_DESC::colorBack, D4D_PRINT_DESC::colorText, D4D_GetFont(), D4D_LCD_PrintStr(), D4D_STR_PROPERTIES_S::font_properties, D4D_STRING_S::fontId, D4D_PRINT_DESC::maxWidth, D4D_PRINT_DESC::pFontType, D4D_STRING_S::printLen, D4D_STRING_S::printOff, D4D_PRINT_DESC::properties, D4D_PRINT_DESC::pTab, D4D_STRING_S::pText, D4D_PRINT_DESC::pText, D4D_STRING_S::str_properties, D4D_PRINT_DESC::textLength, D4D_PRINT_DESC::textOffset, D4D_PRINT_DESC::x, and D4D_PRINT_DESC::y.
void D4D_FillCircle (D4D_POINT * pCenter, D4D_COOR r, D4D_COLOR color)
Function draw filled circle on the screen.
Parameters
pCenter - pointer on point structure of circle center
r - radius of circle
color - color of circle
Returns
none
Note
Function draws the filled circle on the screen in any color. The logical last draw cursor is not moved.
Definition at line 539 of file d4d_basic_draw.c.
References D4D_LCD_Circle(), D4D_LINE_THIN, D4D_TRUE, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GaugOnDraw(), and D4D_RadioButtonOnDraw().
void D4D_FillCircleXY (D4D_COOR x, D4D_COOR y, D4D_COOR r, D4D_COLOR color)
Function draw filled circle on the screen.
Parameters
x - X coordination of circle center
y - Y coordination of circle center
r - radius of circle
color - color of circle
Returns
none
Note
Function draws the filled circle on the screen in any color. The logical last draw cursor is not moved.
Definition at line 554 of file d4d_basic_draw.c.
References D4D_LCD_Circle(), D4D_LINE_THIN, and D4D_TRUE.
void D4D_FillQuadrant (D4D_POINT * pCenter, D4D_COOR radius, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw fill quadrant of circle on the screen.
Parameters
pCenter - pointer to coordination that defines quadrant center
radius - radius of quadrant
color - color of filling of quadrant
quadrant - specify which quadrant will be draw
Returns
none
Note
Function draws the fill quadrant on the screen in any color. The logical last draw cursor is not moved.
Definition at line 1079 of file d4d_basic_draw.c.
References D4D_LCD_QCircle(), D4D_LINE_THIN, D4D_TRUE, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_BtnOnDraw(), and D4D_DrawTextRRectTab().
void D4D_FillQuadrantXY (D4D_COOR x, D4D_COOR y, D4D_COOR radius, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw fill quadrant of circle on the screen.
Parameters
x - coordination in axis X that defines center point of quadrant
y - coordination in axis Y that defines center point of quadrant
radius - radius of quadrant
color - color of filling of quadrant
quadrant - specify which quadrant will be draw
Returns
none
Note
Function draws the fill quadrant on the screen in any color. The logical last draw cursor is not moved.
Definition at line 1095 of file d4d_basic_draw.c.
References D4D_LCD_QCircle(), D4D_LINE_THIN, and D4D_TRUE.
void D4D_FillRect (D4D_POINT * ppt, D4D_SIZE * psz, D4D_COLOR color)
Function draw filled rectangle on the screen.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 274 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_LCD_Box(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_Bevel(), D4D_BtnOnDraw(), D4D_ConsoleOnDraw(), D4D_DrawBmpRect(), D4D_EditBoxOnDraw(), D4D_ListBoxOnDraw(), and D4D_ScrlBrOnDraw().
void D4D_FillRectColorScale (D4D_POINT * ppt, D4D_SIZE * psz, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
Returns
none
Note
Function draws the rectangle on the screen with crossing color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 429 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_FillRectColorScaleXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_FillRectColorScaleTo (D4D_POINT * ppt, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
Parameters
ppt - pointer on point structure of bottm right corner on screen
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
Returns
none
Note
Function draws the rectangle on the screen with crossing color. The logical last draw cursor is keep on the same position of top left corner of rectangle.
Definition at line 508 of file d4d_basic_draw.c.
References D4D_FillRectColorScaleXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_FillRectColorScaleToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
Returns
none
Note
Function draws the rectangle on the screen with crossing color. The logical last draw cursor is keep on the same position of top left corner of rectangle.
Definition at line 524 of file d4d_basic_draw.c.
References D4D_FillRectColorScaleXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_FillRectColorScaleXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction)
Function draw filled rectangle with changing color (cross color from start to end color) on the screen.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
Returns
none
Note
Function draws the rectangle on the screen with crossing color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 448 of file d4d_basic_draw.c.
References D4D_DIR_DOWN, D4D_DIR_LEFT, D4D_DIR_RIGHT, D4D_DIR_UP, D4D_GetCrossColor(), D4D_LCD_Box(), D4D_MulDivUU, D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_FillRectColorScale(), D4D_FillRectColorScaleTo(), D4D_FillRectColorScaleToXY(), and D4D_FillRRectColorScaleXY().
void D4D_FillRectTo (D4D_POINT * ppt, D4D_COLOR color)
Function draw filled rectangle on the screen.
Parameters
ppt - pointer on point structure of bottm right corner on screen
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 310 of file d4d_basic_draw.c.
References D4D_LCD_Box(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GraphOnDraw().
void D4D_FillRectToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR color)
Function draw filled rectangle on the screen.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color and could be defined type. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 327 of file d4d_basic_draw.c.
References D4D_LCD_Box(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GraphOnDraw().
void D4D_FillRectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color)
Function draw filled rectangle on the screen.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 293 of file d4d_basic_draw.c.
References D4D_LCD_Box(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_DrawBmpRect(), D4D_DrawTextRectTab(), D4D_DrawTextRRectTab(), and D4D_LCD_PrintStr().
void D4D_FillRRect (D4D_POINT * ppt, D4D_SIZE * psz, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 920 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_LCD_RBox(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_BtnOnDraw(), D4D_CheckBoxOnDraw(), D4D_ConsoleOnDraw(), D4D_DrawScreenNC(), D4D_DrawTextRRectTab(), D4D_EditBoxOnDraw(), D4D_GaugOnDraw(), D4D_GraphOnDraw(), D4D_GroupBoxOnDraw(), D4D_ListBoxOnDraw(), D4D_MenuOnDraw(), D4D_RadioButtonOnDraw(), D4D_ScrlBrOnDraw(), D4D_SldrOnDraw(), and D4D_TextBoxOnDraw().
void D4D_FillRRectColorScale (D4D_POINT * ppt, D4D_SIZE * psz, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
radius - radius of round corners
Returns
none
Note
Function draws the rectangle with round corners on the screen with crossing color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 1146 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_FillRRectColorScaleXY(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_SldrOnDraw().
void D4D_FillRRectColorScaleTo (D4D_POINT * ppt, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
Parameters
ppt - pointer on point structure of bottm right corner on screen
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
radius - radius of round corners
Returns
none
Note
Function draws the rectangle with round corners on the screen with crossing color. The logical last draw cursor is keep on the same position of top left corner of rectangle.
Definition at line 1252 of file d4d_basic_draw.c.
References D4D_FillRRectColorScaleXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_FillRRectColorScaleToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
radius - radius of round corners
Returns
none
Note
Function draws the rectangle with round corners on the screen with crossing color. The logical last draw cursor is keep on the same position of top left corner of rectangle.
Definition at line 1269 of file d4d_basic_draw.c.
References D4D_FillRRectColorScaleXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_FillRRectColorScaleXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR startColor, D4D_COLOR endColor, D4D_DIRECTION direction, D4D_COOR radius)
Function draw filled rectangle with round corners with changing color (cross color from start to end color) on the screen.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
startColor - start color of rectangle
endColor - end color of rectangle
direction - the direction of color crossing
radius - radius of round corners
Returns
none
Note
Function draws the rectangle with round corners on the screen with crossing color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 1166 of file d4d_basic_draw.c.
References D4D_DIR_DOWN, D4D_DIR_LEFT, D4D_DIR_RIGHT, D4D_DIR_UP, D4D_FillRectColorScaleXY(), D4D_GetCrossColor(), D4D_LCD_Box(), D4D_MulDivUU, D4D_RndCornerGetNonPrintedPxl(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_FillRRectColorScale(), D4D_FillRRectColorScaleTo(), D4D_FillRRectColorScaleToXY(), and D4D_PrgrsBarOnDraw().
void D4D_FillRRectTo (D4D_POINT * ppt, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
Parameters
ppt - pointer on point structure of bottm right corner on screen
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 957 of file d4d_basic_draw.c.
References D4D_LCD_RBox(), D4D_POINT::x, and D4D_POINT::y.
void D4D_FillRRectToXY (D4D_COOR x, D4D_COOR y, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color and could be defined type. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 975 of file d4d_basic_draw.c.
References D4D_LCD_RBox(), D4D_POINT::x, and D4D_POINT::y.
void D4D_FillRRectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_COLOR color, D4D_COOR radius)
Function draw filled rectangle on the screen with round corners.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 939 of file d4d_basic_draw.c.
References D4D_LCD_RBox(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_PrgrsBarOnDraw().
void D4D_LineTo (D4D_POINT * ppt, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw line on the screen.
Parameters
ppt - pointer on point structure of end of line.
ltype - type of the line (thin/thick)
color - color of line
Returns
none
Note
Function draws the line from logical draw cursor to defined point on the screen in any color and could be defined type. The logical last draw cursor is moved on the position of draw pixel.
Definition at line 164 of file d4d_basic_draw.c.
References D4D_LCD_Line(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_DrawScreenNC(), D4D_GaugOnDraw(), D4D_GraphOnDraw(), and D4D_ScrlBrDrawArrow().
void D4D_LineToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw line on the screen.
Parameters
x - coordination in axis X on screen to draw line
y - coordination in axis Y on screen to draw line
ltype - type of the line (thin/thick)
color - color of line
Returns
none
Note
Function draws the line from logical draw cursor to defined point on the screen in any color and could be defined type. The logical last draw cursor is moved on the position of draw pixel.
Definition at line 182 of file d4d_basic_draw.c.
References D4D_LCD_Line(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GraphDrawEmptyGraph(), D4D_ImgDecExtD4DDraw(), D4D_ImgDecIntD4DDraw(), and D4D_MenuOnDraw().
void D4D_MoveTo (D4D_POINT * ppt)
Function move logic cursor to new position.
Parameters
ppt - pointer on point structure that defines point on screen to move cursor
Returns
none
Note
Function just move the last draw cursor to new position.
Definition at line 77 of file d4d_basic_draw.c.
Referenced by D4D_DrawScreenNC(), D4D_GaugOnDraw(), D4D_GraphOnDraw(), and D4D_ScrlBrDrawArrow().
void D4D_MoveToXY (D4D_COOR x, D4D_COOR y)
Function move logic cursor to new position.
Parameters
x - coordination in axis X that defines left corner for cursor move
y - coordination in axis Y that defines top corner for cursor move
Returns
none
Note
Function just move the last draw cursor to new position.
Definition at line 89 of file d4d_basic_draw.c.
References D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GraphDrawEmptyGraph(), D4D_GraphOnDraw(), D4D_ImgDecExtD4DDraw(), D4D_ImgDecIntD4DDraw(), and D4D_MenuOnDraw().
void D4D_PutPixel (D4D_POINT * ppt, D4D_LINETYPE type, D4D_COLOR color)
Function puts one pixel on the screen.
Parameters
ppt - pointer on point structure that defines point on screen to draw pixel
type - type of the pixel (thin/thick)
color - color of pixel
Returns
none
Note
Function just puts pixel on the screen in any color and could be defined type. The logical last draw cursor is moved on the position of draw pixel.
Definition at line 104 of file d4d_basic_draw.c.
References D4D_LCD_PutPixel(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_ScrlBrDrawArrow().
void D4D_PutPixelTo (D4D_LINETYPE type, D4D_COLOR color)
Function puts one pixel on the screen.
Parameters
type - type of the pixel (thin/thick)
color - color of pixel
Returns
none
Note
Function just puts pixel on the screen in any color and could be defined type. The pixel is puts on the draw cursor position
Definition at line 118 of file d4d_basic_draw.c.
References D4D_LCD_PutPixel(), D4D_POINT::x, and D4D_POINT::y.
void D4D_PutPixelXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE type, D4D_COLOR color)
Function puts one pixel on the screen.
Parameters
x - coordination in axis X on screen to draw pixel
y - coordination in axis Y on screen to draw pixel
type - type of the pixel (thin/thick)
color - color of pixel
Returns
none
Note
Function just puts pixel on the screen in any color and could be defined type. The logical last draw cursor is moved on the position of draw pixel.
Definition at line 133 of file d4d_basic_draw.c.
References D4D_LCD_PutPixel(), D4D_POINT::x, and D4D_POINT::y.
void D4D_Quadrant (D4D_POINT * pCenter, D4D_COOR radius, D4D_LINETYPE ltype, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw quadrant of circle on the screen.
Parameters
pCenter - pointer to coordination that defines quadrant center
radius - radius of quadrant
ltype - type of the line (thin/thick)
color - color of line of quadrant
quadrant - specify which quadrant will be draw
Returns
none
Note
Function draws the quadrant on the screen in any color. The logical last draw cursor is not moved.
Definition at line 1111 of file d4d_basic_draw.c.
References D4D_FALSE, D4D_LCD_QCircle(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_Bevel().
void D4D_QuadrantXY (D4D_COOR x, D4D_COOR y, D4D_COOR radius, D4D_LINETYPE ltype, D4D_COLOR color, D4D_QUADRANT quadrant)
Function draw quadrant of circle on the screen.
Parameters
x - coordination in axis X that defines center point of quadrant
y - coordination in axis Y that defines center point of quadrant
radius - radius of quadrant
ltype - type of the line (thin/thick)
color - color of line of quadrant
quadrant - specify which quadrant will be draw
Returns
none
Note
Function draws the quadrant on the screen in any color. The logical last draw cursor is not moved.
Definition at line 1128 of file d4d_basic_draw.c.
References D4D_FALSE, and D4D_LCD_QCircle().
void D4D_RBox (D4D_POINT * ppt, D4D_SIZE * psz, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle with outline on the screen with round corners in any colors. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 995 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_RBoxXY(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_CheckBoxOnDraw(), D4D_DrawScreenNC(), and D4D_PrgrsBarOnDraw().
void D4D_RBoxTo (D4D_POINT * ppt, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
Parameters
ppt - pointer on point structure of bottm right corner on screen
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle with outline on the screen with round corners in any colors. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 1039 of file d4d_basic_draw.c.
References D4D_RBoxToXY(), D4D_POINT::x, and D4D_POINT::y.
void D4D_RBoxToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle with outline on the screen with round corners in any colors. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 1057 of file d4d_basic_draw.c.
References D4D_LCD_RBox(), D4D_LCD_RRect(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_RBoxTo().
void D4D_RBoxXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR colorLine, D4D_COLOR colorFill, D4D_COOR radius)
Function draw filled rectangle with outline on the screen with round corners.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
colorLine - color of rectangle outline
colorFill - color of rectangle fill
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle with outline on the screen with round corners in any colors. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 1015 of file d4d_basic_draw.c.
References D4D_LCD_RBox(), D4D_LCD_RRect(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_ImgDecBmpDraw(), D4D_ImgDecExtD4DDraw(), D4D_ImgDecIntD4DDraw(), and D4D_RBox().
void D4D_Rect (D4D_POINT * ppt, D4D_SIZE * psz, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
ltype - type of the line (thin/thick)
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color and could be defined type. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 200 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_LCD_Rect(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_GroupBoxOnDraw().
void D4D_RectTo (D4D_POINT * ppt, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
Parameters
ppt - pointer on point structure of bottm right corner on screen
ltype - type of the line (thin/thick)
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color and could be defined type. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 238 of file d4d_basic_draw.c.
References D4D_LCD_Rect(), D4D_POINT::x, and D4D_POINT::y.
void D4D_RectToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color and could be defined type. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 256 of file d4d_basic_draw.c.
References D4D_LCD_Rect(), D4D_POINT::x, and D4D_POINT::y.
void D4D_RectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR color)
Function draw rectangle on the screen.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
color - color of rectangle
Returns
none
Note
Function draws the rectangle on the screen in any color and could be defined type. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 220 of file d4d_basic_draw.c.
References D4D_LCD_Rect(), D4D_POINT::x, and D4D_POINT::y.
D4D_COOR D4D_RndCornerGetNonPrintedPxl (D4D_COOR radius, D4D_COOR line)
Function that counts number of printed pixels in specified line of circle quadrant.
Parameters
radius - radius of quadrant to count the printed pixels
line - line of quadrant to count the pixels numbers that should be printed
Returns
count of pixels that should be printed on this line of specified quadrant
Note
Helping function that could be used with printing the circle arcs.
Definition at line 1282 of file d4d_basic_draw.c.
References D4D_FALSE, D4D_TRUE, and D4D_SCREEN_S::radius.
Referenced by D4D_FillRRectColorScaleXY(), D4D_ImgDecBmpDraw(), D4D_ImgDecExtD4DDraw(), D4D_ImgDecIntD4DDraw(), and D4D_SldrValue2Coor().
void D4D_RRect (D4D_POINT * ppt, D4D_SIZE * psz, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
Parameters
ppt - pointer on point structure of top left corner on screen
psz - pointer on the size structure that defines size of the rectangle
ltype - type of the line (thin/thick)
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color and could be defined type. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 843 of file d4d_basic_draw.c.
References D4D_SIZE::cx, D4D_SIZE::cy, D4D_LCD_RRect(), D4D_POINT::x, and D4D_POINT::y.
Referenced by D4D_BtnOnDraw(), D4D_CheckBoxOnDraw(), D4D_DrawFrame(), D4D_DrawScreenNC(), D4D_GroupBoxOnDraw(), D4D_ScrlBrOnDraw(), and D4D_SldrOnDraw().
void D4D_RRectTo (D4D_POINT * ppt, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
Parameters
ppt - pointer on point structure of bottm right corner on screen
ltype - type of the line (thin/thick)
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color and could be defined type. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 883 of file d4d_basic_draw.c.
References D4D_LCD_RRect(), D4D_POINT::x, and D4D_POINT::y.
void D4D_RRectToXY (D4D_COOR x, D4D_COOR y, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
Parameters
x - coordination in axis X that defines right corner of retangle
y - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color and could be defined type. As the start point of the drawed rectangle is used logical draw cursor. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 902 of file d4d_basic_draw.c.
References D4D_LCD_RRect(), D4D_POINT::x, and D4D_POINT::y.
void D4D_RRectXY (D4D_COOR x1, D4D_COOR y1, D4D_COOR x2, D4D_COOR y2, D4D_LINETYPE ltype, D4D_COLOR color, D4D_COOR radius)
Function draw rectangle on the screen with round corners.
Parameters
x1 - coordination in axis X that defines left corner of retangle
y1 - coordination in axis Y that defines top corner of retangle
x2 - coordination in axis X that defines right corner of retangle
y2 - coordination in axis Y that defines bottom corner of retangle
ltype - type of the line (thin/thick)
color - color of rectangle
radius - radius of rectangle
Returns
none
Note
Function draws the rectangle on the screen with round corners in any color and could be defined type. The logical last draw cursor is moved on the position of top left corner of rectangle.
Definition at line 864 of file d4d_basic_draw.c.
References D4D_LCD_RRect(), D4D_POINT::x, and D4D_POINT::y.