var modules =
[
    [ "D4D BASE functionality", "group__doxd4d__base.html", "group__doxd4d__base" ],
    [ "D4D BASIC DRAWING functionality", "group__doxd4d__basic__draw.html", "group__doxd4d__basic__draw" ],
    [ "D4D BITMAP functionality", "group__doxd4d__bmp.html", "group__doxd4d__bmp" ],
    [ "D4D EXTERNAL RESOURCE functionality", "group__doxd4d__extsrc.html", "group__doxd4d__extsrc" ],
    [ "D4D FONTS functionality", "group__doxd4d__font.html", "group__doxd4d__font" ],
    [ "D4D LOW LEVEL DRIVER API functionality", "group__doxd4d__lldapi.html", "group__doxd4d__lldapi" ],
    [ "D4D MATH functionality", "group__doxd4d__math.html", "group__doxd4d__math" ],
    [ "D4D MOUSE Handler", "group__doxd4d__mouse.html", "group__doxd4d__mouse" ],
    [ "D4D OBJECT Handler", "group__doxd4d__object.html", "group__doxd4d__object" ],
    [ "D4D SCHEME Handler", "group__doxd4d__scheme.html", "group__doxd4d__scheme" ],
    [ "D4D SCREEN Handler", "group__doxd4d__screen.html", "group__doxd4d__screen" ],
    [ "D4D STRING Handler", "group__doxd4d__string.html", "group__doxd4d__string" ],
    [ "D4D TYPES Definition", "group__doxd4d__types.html", "group__doxd4d__types" ],
    [ "D4D Button Widget", "group__doxd4d__button.html", "group__doxd4d__button" ],
    [ "D4D Check Box Widget", "group__doxd4d__check__box.html", "group__doxd4d__check__box" ],
    [ "D4D Combo Box Widget", "group__doxd4d__combo__box.html", "group__doxd4d__combo__box" ],
    [ "D4D Console Widget", "group__doxd4d__console.html", "group__doxd4d__console" ],
    [ "D4D Edit Box Widget", "group__doxd4d__edit__box.html", "group__doxd4d__edit__box" ],
    [ "D4D Gauge Widget", "group__doxd4d__gauge.html", "group__doxd4d__gauge" ],
    [ "D4D Graph Widget", "group__doxd4d__graph.html", "group__doxd4d__graph" ],
    [ "D4D Group Box Widget", "group__doxd4d__group__box.html", "group__doxd4d__group__box" ],
    [ "D4D Icon Widget", "group__doxd4d__icon.html", "group__doxd4d__icon" ],
    [ "D4D Label Widget", "group__doxd4d__label.html", "group__doxd4d__label" ],
    [ "D4D List Box Widget", "group__doxd4d__list__box.html", "group__doxd4d__list__box" ],
    [ "D4D Menu Widget", "group__doxd4d__menu.html", "group__doxd4d__menu" ],
    [ "D4D Picture Widget", "group__doxd4d__picture.html", "group__doxd4d__picture" ],
    [ "D4D Progress Bar Widget", "group__doxd4d__progress__bar.html", "group__doxd4d__progress__bar" ],
    [ "D4D Radio Button Widget", "group__doxd4d__radio__button.html", "group__doxd4d__radio__button" ],
    [ "D4D Scroll Bar Widget", "group__doxd4d__scroll__bar.html", "group__doxd4d__scroll__bar" ],
    [ "D4D Slider Widget", "group__doxd4d__slider.html", "group__doxd4d__slider" ],
    [ "D4D Text Box Widget", "group__doxd4d__text__box.html", "group__doxd4d__text__box" ],
    [ "D4D LCD driver Template", "group__doxd4d__lcd.html", "group__doxd4d__lcd" ],
    [ "D4D LCD HW  INTERFACE driver Template", "group__doxd4d__lcdhw.html", "group__doxd4d__lcdhw" ],
    [ "D4D LCD HW INTERFACE Frame Buffer driver Template", "group__doxd4d__lcdhwfb.html", "group__doxd4d__lcdhwfb" ],
    [ "D4D TCHSCR driver Template", "group__doxd4d__tch.html", "group__doxd4d__tch" ],
    [ "D4D TCHSCR HW INTERFACE driver Template", "group__doxd4d__tchhw.html", "group__doxd4d__tchhw" ]
];